### ISSUE TITLE
ddev config destroys comments (including commented hook configuration)

### ISSUE THREAD

**Issue by mfrieling** [drud/ddev#1074]
**Describe the bug**
Scenario is having `config.yaml` in Git because several hooks are configured.

Now when I (temporarily) disable some hooks because they cannot work in a specific state like setting up (cloning) the project on a new computer or due to other conditions not yet fulfilled and then do a `ddev config` to generate the files (`docker-compose.yml`, `settings.ddev.php`, ...) it does unwanted things with the `hooks` section of `config.yaml`:
1. It reorders the commands alphabetically (while I defined them in logically order). While this only produces an unwanted change for git the next ones are worse.
2. It removes all comments from the hooks section, no matter if this are explaining comments or disabled hooks.

As the developer/projetc maintainer added comments there with a purpose, DDEV should not remove them but as its best, not touch the hooks section at all when doing its configuration.

**To Reproduce**
1. Add some comments to the hooks section in `config.yaml` and if you do not have any hooks add  dummy hooks there like `echo "Executing post-start hook."`
2. Run `ddev config` and check changes in your config.yaml.

**Expected behavior**
`config.yaml` basically has two parts. One which can be maintained by `ddev config` (but as well by the user) and the other part an only be maintained by the user (e. g. defining hooks). This part should never be touched by `ddev config`. If that is not possible like with adding services split the config up in several files like `config.hooks.yml` (to define hooks) and maybe `config.overrides.yml` (for overriding PHP version, debugging etc.) or `config.*.yaml` in general.

**Screenshots**
![ddev_config_demolishing](https://user-images.githubusercontent.com/8668756/44410643-2f618400-a565-11e8-9ecc-0bf873ef31a1.jpg)

**Version and configuration information (please complete the following information):**
 - Windows 10 Professional
 - Docker 18.06.0-ce, build 0ffa825
 - ddev version information:
```domain  ddev.local
cli     v1.1.1
web     drud/ddev-webserver:v1.1.0
db      drud/ddev-dbserver:v1.1.0
dba     drud/phpmyadmin:v1.1.0
router  drud/ddev-router:v1.1.0
commit  v1.1.1
```
 - config.yaml contents for the misbehaving project
```
APIVersion: v1.1.1
name: trinitec
type: drupal8
docroot: web
php_version: "7.1"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
provider: default
hooks:
  post-start:
  - exec: sh /mnt/ddev_config/init-ssh.sh
  pre-start:
  - exec-host: cmd /c .ddev\pre-start.cmd
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? Increasing PHP memory limit to 1024M
