### ISSUE TITLE
/usr/sbin/policy-rc.d prevents service restart after PHP module installation (specifically php-ldap)

### ISSUE THREAD

**Issue by jfastnacht** [drud/ddev#1117]
**Describe the bug**
When installing php-ldap with post-start hooks (as recommended) the restart of the services to activate the LDAP module fails due to the `/usr/sbin/policy-rc.d` (https://people.debian.org/~hmh/invokerc.d-policyrc.d-specification.txt) which is set to `exit 101` by default.

```
Setting up php7.1-ldap (7.1.20-1+0~20180910100430.3+jessie~1.gbp17c613) ...

Creating config file /etc/php/7.1/mods-available/ldap.ini with new version
Processing triggers for php7.1-fpm (7.1.20-1+0~20180910100430.3+jessie~1.gbp17c613) ...
/usr/sbin/invoke-rc.d: 1: /usr/sbin/invoke-rc.d: /sbin/runlevel: not found
invoke-rc.d: policy-rc.d denied execution of restart.
```

**To Reproduce**
1. Add post-start hook to install `php-ldap` into `config.yaml`
```yaml
hooks:
  post-start:
  - exec: "apt-get update"
  - exec: "apt-get -y install php7.1-ldap"
```
2. Run ddev with `ddev start`
3. Wait until the LDAP module is installed
5. `ddev ssh` into machine and check `php -m`, the module is installed
6. Check `phpinfo()` on webserver, the module is not activated

You can `ddev stop` and `ddev start` again, the module should be active after the restart.

**Expected behavior**
The service should restart properly and the PHP module should work without restarting the whole project.

Since I assume that this is not only a problem of the LDAP module, it might be good to think about implementing a way to properly configure PHP modules over the `config.yaml` and to unify the installation process of PHP modules.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 8.1
 - Docker version information (use `docker version`) and insert it here.
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.06.1-ce
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   e68fc7a
  Built:        Tue Aug 21 17:28:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
 - ddev version information (use `ddev version`)
```
web     drud/ddev-webserver:v1.1.0
db      drud/ddev-dbserver:v1.1.0
dba     drud/phpmyadmin:v1.1.0
router  drud/ddev-router:v1.1.0
commit  v1.1.1
domain  ddev.local
cli     v1.1.1
```
 - config.yaml contents for the misbehaving project
```yaml
APIVersion: v1.1.1
name: projectnamechanged
type: php
docroot: web/
php_version: "7.1"
router_http_port: "9080"
router_https_port: "9443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
hooks:
  post-start:
  - exec: "apt-get update"
  - exec: "apt-get -y install php7.1-ldap"
  - exec: "composer install -d /var/www/html/"
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

A custom nginx-site.conf for Symfony. Would post only if necessary.

**Additional context**
~~Add any other context about the problem here. Thanks!~~
