### ISSUE TITLE
Problem with drush commands on the terminal (auto yes selected) when exporting/importing configurations

### ISSUE THREAD

**Issue by Gonzalo2683** [drud/ddev#1118]
**Describe the bug**
When I execute tasks such as drush cex or cim (actually in any command that involves the user taking a decision), when the console appears if i want(or not want) to export/apply the changes, it selects itself in the Yes option and applies/exports the configurations, that is, I do not have the way of saying NO to the process that will be carried out.

I'm using Windows 10 Pro and I'm using the **Cmder** terminal.

**To Reproduce**
1. Go to server ddev ssh -s web
2. run drush @siteAlias cex
3. See error

**Expected behavior**
That allows me to select whether or not I want to apply the changes.

**Version and configuration information (please complete the following information):**
 - Windows 10 Pro
 
**Docker version information (use `docker version`)**
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 ```
**ddev version information (use `ddev version`)**
```
commit  v1.0.0
domain  ddev.local
cli     v1.0.0
```

**config.yaml contents for the misbehaving project**

```
APIVersion: v1.0.0
name: project-one
type: drupal8
docroot: ""
php_version: "7.1"
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
- site-a
- site-b
additional_fqdns: []
provider: default
```
**Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?**

The only thing I have additional is a file called **docker-compose.drush.yaml** to have the aliases of the site in local volume.

```
version: '3'
services:
  web:
    volumes:
      - "$HOME/.projectname/.drush/:/home/.drush/"
      - "$HOME/.projectname/.drush/aliases:/home/.drush/aliases"
      - "$HOME/.projectname/.drush/commands:/home/.drush/commands"
```
