### ISSUE TITLE
Selenium testing

### ISSUE THREAD

**Issue by ogrosko** [drud/ddev#1153]
Hi, I'm trying to run Selenium tests with selenium server inside my ddev

This is my `config.yaml`:
```
APIVersion: v1.2.0
name: myproject
type: typo3
docroot: web
php_version: "7.0"
webserver_type: apache-fpm
router_http_port: "81"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
provider: default
webimage: drud/ddev-webserver:20180922_apache_https
```
This is my `docker-compose.selenium.yaml`:
```
version: '3.6'

services:
    selenium:
        container_name: ddev-${DDEV_SITENAME}-selenium
        image: selenium/standalone-chrome:latest
        ports:
            - 4444
        labels:
            com.ddev.site-name: ${DDEV_SITENAME}
            com.ddev.approot: $DDEV_APPROOT
            com.ddev.app-url: $DDEV_URL
        environment:
            - VIRTUAL_HOST=$DDEV_HOSTNAME
            - HTTP_EXPOSE=4444
    web:
        links:
            - selenium:$DDEV_HOSTNAME
```
This is my test:
```
class UserTest extends TestCase
{

    /**
     * @var RemoteWebDriver
     */
    protected $webDriver;

    public function setUp()
    {
        $capabilities = DesiredCapabilities::chrome();
        $capabilities->setCapability('acceptSslCerts', false);
        $this->webDriver = RemoteWebDriver::create('myproject.ddev.local:4444/wd/hub', $capabilities);
    }

//    protected $url = 'https://myproject.ddev.local';
    protected $url = 'http://127.0.0.1';
//    protected $url = 'https://google.com';

    public function testFormSubmissionWithUsername()
    {
        $this->webDriver->get($this->url);
        \file_put_contents('test.html', $this->webDriver->getPageSource());
        $this->assertContains('Google', $this->webDriver->getTitle());
    }

    public function tearDown()
    {
        $this->webDriver->quit();
    }
}
```

When I try to test some public url like `https://google.com` all works fine. But when I try to test some local url like `localhost` or `https://myproject.ddev.local` I'm getting:
**This site can’t be reached
127.0.0.1 refused to connect**

Do you have any idea what I'm doing wrong?
Thx for any advice

```
$ ddev version
db    	drud/ddev-dbserver:v1.2.0 
dba   	drud/phpmyadmin:v1.2.0    
router	drud/ddev-router:v1.2.0   
commit	v1.2.0                    
domain	ddev.local                
cli   	v1.2.0                    
web   	drud/ddev-webserver:v1.2.0 
```

**Comment by rfay** [comment]
You're using URLs that require access via the router. So your selenium container has no idea where the router is, and is using an unresolveable name. Please use the technique suggested in https://github.com/drud/ddev/issues/842#issuecomment-426398780

Try removing the
```
    web:
        links:
            - selenium:$DDEV_HOSTNAME
```

and  adding this to your selenium service:

```
    external_links:
      - ddev-router:$DDEV_HOSTNAME
```

This will make the selenium container router requests through the router (which terminates SSL and actually listens on the right ports). Make sure that the correct port is specified in the URL.

**Comment by ogrosko** [comment]
@rfay awesome works like charm. Thank you for your help

**Comment by Gonzalo2683** [comment]
Hi @ogrosko, I'm trying to configure selenium with dev, but the DDEV_URL variable appears to me as undefined, what value should I go there?

**Comment by rfay** [comment]
DDEV_URL has been obsolete for a few versions now, you should be able to just delete that line.

**Comment by infabo** [comment]
> You're using URLs that require access via the router. So your selenium container has no idea where the router is, and is using an unresolveable name. Please use the technique suggested in [#842 (comment)](https://github.com/drud/ddev/issues/842#issuecomment-426398780)
> 
> Try removing the
> 
> ```
>     web:
>         links:
>             - selenium:$DDEV_HOSTNAME
> ```
> 
> and adding this to your selenium service:
> 
> ```
>     external_links:
>       - ddev-router:$DDEV_HOSTNAME
> ```
> 
> This will make the selenium container router requests through the router (which terminates SSL and actually listens on the right ports). Make sure that the correct port is specified in the URL.

Should this still work in 1.16? I had my config working back then with xxx.ddev.local but now it seems not to work anymore. Just get a connection refused in headless chrome.

**Comment by rfay** [comment]
@infabo There is a selenium recipe at https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/drupal8-behat-selenium

There's also a Stack Overflow at https://stackoverflow.com/questions/51527663/running-selenium-tests-using-behat-drupal-extension-inside-ddev-containers

It's been a long time since *.ddev.local! But I doubt that has anything to do with it.

**Comment by infabo** [comment]
Thanks Randy! All these configurations assume that one can "just" use "http://web" to access the application. That already worked.
But that is not for TYPO3 as it decides by the domain (aka base) which page-tree is used.

**Comment by infabo** [comment]
I figured out what went wrong.

As long you haven't defined `additional_hostnames` in config.yaml the following config works:

```yaml
version: '3.6'
services:
    selenium:
        container_name: ddev-${DDEV_SITENAME}-chrome
        image: selenium/standalone-chrome:3.12
        environment:
            - VIRTUAL_HOST=$DDEV_HOSTNAME
            - HTTP_EXPOSE=4444
        external_links:
            - ddev-router:$DDEV_HOSTNAME
```

As this resolves to:

```yaml
  selenium:
    container_name: ddev-typo3-website-chrome
    environment:
      HTTP_EXPOSE: '4444'
      VIRTUAL_HOST: typo3-website.ddev.site
    external_links:
    - ddev-router:typo3-website.ddev.site
    image: selenium/standalone-chrome:3.12
```

But once you define `additional_hostnames` it starts getting invalid and resulting in this config:

```yaml
  selenium:
    container_name: ddev-typo3-website-chrome
    environment:
      HTTP_EXPOSE: '4444'
      VIRTUAL_HOST: typo3-website.ddev.site,another.typo3-website.ddev.site
    external_links:
    - ddev-router:typo3-website.ddev.site,another.typo3-website.ddev.site
    image: selenium/standalone-chrome:3.12
```

That's why it did not work anymore as I added an additional hostname some time ago - but haven't run acceptance tests in a while now.

Hope this helps anyone having the same problem.

**Comment by infabo** [comment]
This is what works for me now:

```yaml
version: '3.6'
services:
    selenium:
        container_name: ddev-${DDEV_SITENAME}-chrome
        image: selenium/standalone-chrome:3.12
        environment:
            - VIRTUAL_HOST=${DDEV_SITENAME}.${DDEV_TLD}
            - HTTP_EXPOSE=4444
        external_links:
            - ddev-router:${DDEV_SITENAME}.${DDEV_TLD}
```

**Comment by infabo** [comment]
Just one more thing, @rfay :

DDEV itself is capable to generate multiple lines depending on `additional_hostnames`.
Is this possible possible to achieve with simple YAML too? I guess that needs some scripting if one wants to automate it, right?

```yaml
web:
    external_links:
    - ddev-router:typo3-website.ddev.site
    - ddev-router:additional.typo3-website.ddev.site
```
