### ISSUE TITLE
Elasticsearch container crashes when used with ddev

### ISSUE THREAD

**Issue by paulvandermeijs** [drud/ddev#1164]
**Describe the bug**
Elasticsearch container crashes when used with ddev.

**To Reproduce**
1. Create `docker-composer.elasticsearch.yaml` with content below in `.ddev` folder
```yaml
version: '3.6'
services:
  elasticsearch:
    container_name: ddev-${DDEV_SITENAME}-elasticsearch
    image: elasticsearch:5.6
    ports:
      - "9200"
      - "9300"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9200
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_URL
  web:
    links:
      - elasticsearch:elasticsearch
```
2. Run `ddev start`
3. Run `docker ps` to see that everything is running
4. Make a few requests to `http://<projectname>.ddev.local:9200/`
5. After a few requests the server stops responding and when running `docker ps` the elasticsearch container is gone.

**Expected behavior**
The container should keep running and responding to requests.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS High Sierra
 - Docker version information:
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
 - ddev version information:
```
db    	drud/ddev-dbserver:v1.2.0
dba   	drud/phpmyadmin:v1.2.0
router	drud/ddev-router:v1.2.0
commit	v1.2.0
domain	ddev.local
cli   	v1.2.0
web   	drud/ddev-webserver:v1.2.0
```
 - config.yaml contents for the misbehaving project:
```
APIVersion: v1.2.0
name: elastictest
type: php
docroot: ""
php_version: "7.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? Nothing except the `docker-composer.elasticsearch.yaml` file mentioned earlier.

**Additional context**
Running the Elasticsearch container by itself using `docker run -p 9200:9200 elasticsearch:5.6` or with a simple `docker-compose.yaml` file like the one below works just fine. The problem only seems to occur when using ddev.
```yaml
version: '3'
services:
  web:
    image: nginx
  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
```
