### ISSUE TITLE
As a developer, I want the ability to use custom containers.

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#121]
## What happened (or feature request):

Feature Request

## What you expected to happen:

Many end-users will need additional services beyond a webserver and database container. Examples include Solr, Redis, Varnish, and/or memcache. Additionally, end-users may need to specify their own containers that match a variety of hosting providers OR their specific production environments.

# Acceptance Criteria
- Modify ddev to write the docker-compose.yaml file during the `ddev config` step instead of waiting on application start
- `ddev config` should prompt before overwriting an existing docker-compose.yaml file.
- Create a DRUD maintained SOLR container.
- Write documentation for modifying the docker-compose.yaml to add SOLR
  - Cover configuring Drupal / Wordpress to use the SOLR instance, or (preferably) link to relevant documentation.
- For now, documentation should assume the user will be accessing the container port directly if they need a SOLR UI. Follow-ups are planned to create a system where it could listen on the site hostname.

## Testing criteria:
- Commit an example docker-compose.yaml to the ddev repo, which can be copied over an example site during testing to ensure our end-user docs stay up to date. From there, we should be able to assert the config works and solr has started correctly.

## Followups required
* [ ] Create tickets and determine level of effort for supporting other popular services (memcache, varnish, redis)

**Comment by tannerjfco** [comment]
docker-compose supports overriding/extending a docker-compose.yml with multiple other compose files: https://docs.docker.com/compose/extends/ I feel like this would be a great way to handle customization, as we could leave our `docker-compose.yml` in our control, and provide 2 possible options for handling customization: 

- we could instruct that customization/extend goes to `docker-compose.override.yml`, which docker-compose supports reading by default; 

- or we could allow users to define any docker-compose.foo.yml file, which could be nice to allow users to download a "recipe" file and drop in (e.g. docker-compose.solr.yml to get solr on your site).

**Comment by tannerjfco** [comment]
While working to get a solr setup working with ddev projects, I explored using multiple compose files as mentioned above. I'm pretty convinced it's the right approach to provide simple extension/customization of the compose file for a ddev project. What I propose is that we support the ability for users to place many docker-compose files in the .ddev folder. This would allow us to provide a recipe for something like solr like so:

(hypothetical docker-compose.solr.yml)
```
# ddev apache solr recipe file
#
# To use this in your own project: Copy this file to your project's .ddev folder,
# and create the folder path .ddev/solr/conf. Then, copy the solr configuration
# files for your project to .ddev/solr/conf. E.g., using Drupal Search API Solr, 
# you would copy the solr-conf/5.x/ contents into .ddev/solr/conf. The configuration
# files must be present before running `ddev start`.

version: '2'

services:
  solr:
    container_name: local-${DDEV_SITENAME}-solr
    image: solr:5.4
    restart: always
    ports:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.container-type: db
      com.ddev.platform: local
      com.ddev.app-type: drupal7
      com.ddev.docroot: $DDEV_DOCROOT
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_URL
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - VIRTUAL_PORT=8983
    volumes:
      - "./solr:/solr-conf"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - dev
      - /solr-conf
  web:
    links:
      - solr:$DDEV_HOSTNAME
 ```

To achieve this, we would need to do the following. I believe all are reasonable and worthwhile efforts:
- Update ddev to find any additional compose files in .ddev folder and add them as -f file args to the docker-compose calls.
- Rename services in the main docker-compose.yml from `platform-sitename-service` to just `service`. In my testing this seems to be a safe change, as the service names seem to be docker-compose project-specific. This would also allow us to deprecate our `com.ddev.container-type` label in favor of docker's `com.docker.compose.service` label.
- Decide how and where to store "recipes", and how we would enable users to contribute their own recipes.
