### ISSUE TITLE
Duplicate output from exec in config.yml post-start hook

### ISSUE THREAD

**Issue by begroff** [drud/ddev#1358]
**Describe the bug**
After setting up a post-start hook in the config.yml file for a drush task to be run on the web container the output of the drush command looks to be duplicated with the final line of the command outputted first, then the details of the rest of the commands (including the final line) outputted next.

**To Reproduce**
1. Go to a new project folder (drupal 7/8) and run 'ddev config'
2. In the .ddev/config.yml file setup a drush task for post-start hook
3. Run 'ddev start'
4. Inspect output

**Expected behavior**
Only one set of output statements should be listed instead of two.

**Screenshots**
![image](https://user-images.githubusercontent.com/12364330/50495853-d82f5c80-09f9-11e9-9c01-d52b3d3d7728.png)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Windows 10 Home
 
- Docker version information (use `docker version`) and insert it here.
![image](https://user-images.githubusercontent.com/12364330/50495914-51c74a80-09fa-11e9-942c-c701b72b624f.png)

 - ddev version information (use `ddev version`)
![image](https://user-images.githubusercontent.com/12364330/50495928-64da1a80-09fa-11e9-91dd-cfd134f3dc90.png)

 - config.yaml contents for the misbehaving project
```
APIVersion: v1.5.0
name: orchidtreeyoga
type: drupal7
docroot: web
php_version: "7.1"
webserver_type: apache-cgi
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns:
- orchidtreeyoga.local
mariadb_version: "10.2"
webcache_enabled: false
provider: default
hooks:
  # Only runs when web container is created/recreated.
  post-start:
   - exec: "drush site-install -y"
   - exec: "drush en orchid_deploy -y"
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them? No

**Additional context**
Add any other context about the problem here. Thanks!
