### ISSUE TITLE
Documentation: neos.flow setup with ddev

### ISSUE THREAD

**Issue by kaystrobach** [drud/ddev#1367]
Hi, i usually use ddev for local development. We often use neos.flow for business projects. Flow works perfectly in ddev if some adjustments are made. If you are interested I would contribute the needed documentation.

**Comment by rfay** [comment]
Thanks so much for this! 
* Do you think it would be better to document it on the neos side, or perhaps on Stack Overflow?
* Is there any explicit support that ddev needs to add for neos.flow? Really our explicit CMS support for fully supported CMSs is just 1) Creating settings files for ddev usage, 2) Providing alternate nginx/apache configs and that's about it.

**Comment by kaystrobach** [comment]
As mentioned earlier it’s just setting some env vars and an easy recipe how to tell flow where the db is.

and thats it, the rest is just using plain php project settings.

**Comment by rfay** [comment]
I'm not entirely familiar with how extensively neos.flow is used, whether it's different from neos, or whether most users are familiar with TYPO3 already. 

I would propose an question-and-answer style article on [Stack Overflow](https://stackoverflow.com/tags/ddev) while the approach matures, allowing easy editing and community involvement.  What do you think?

**Comment by kaystrobach** [comment]
ok, i keep this open, if it's ok for you i would start to write it in markdown here in that ticket and then we can push it to stackoverflow afterwards

**Comment by kaystrobach** [comment]
## configure ddev

To use ddev together with neos or flow you need to configure ddev first:

```bash
ddev config
```

give the project a name and choose `php` as project type

## preparations in flow

if you are using flow 5.x you are fine with the defaults for the php project type, if you are using flow 4.x or lower you may need to adjust the php version in `.ddev/config.yaml` to 7.1 or 7.0

place the following code in `.ddev/docker-compose.env.yaml`

```yaml
version: '3.6'

services:
  web:
    environment:
      - FLOW_CONTEXT=Development/Ddev
      - FLOW_PATH_TEMPORARY_BASE=/tmp/Flow
```

It does two things

1. it defines a development context for ddev, which allows us to have special settings for ddev
1. it moves the temporary files into the docker container to speed things up dramatically

place the following code in `Configuration/Development/Ddev/Settings.yaml`

```yaml
Neos:
  Flow:
    persistence:
      backendOptions:
        host:     'db'
        dbname:   'db'  # adjust to your database name
        user:     'db'  # adjust to your database user
        password: 'db'  # adjust to your database password
        port:     3306
      doctrine:
        sqlLogger: 'Neos\Flow\Persistence\Doctrine\Logging\SqlLogger'
  SwiftMailer:
    transport:
      type: 'Swift_MailTransport'
```

This configuration defines the context defined in the above docker configuration and ensures, that the DB can be reached and that Mails are redirected to ddev's MailHog via SwiftMailer.

## time to get it started up

now it's time to start ddev, after the command has run through, you can open your website the first time. It may take same time to load for the first hit as flow needs to fill all the caches.

```bash
ddev start
ddev exec composer install
```

## fine tuning

during the development, we found some tweaks to finetune the setup

you can set start up hooks in ddev to speed up the first run and avoid any problems or solve them easier `.ddev/config.yaml`:

```yaml
hooks:
  post-start:
  - exec: composer install
  - exec: ./flow neos.flow:package:rescan
  - exec: ./flow database:setcharset
  - exec: ./flow doctrine:migrate

```

**Comment by ochorocho** [comment]
@kaystrobach thanks. This makes FLOW fast in a docker environment.

In addition to the other envvars i had to set `FLOW_REWRITEURLS=1` in docker-compose.env.yaml .
If not set i had "index.php" in path which was causing some touble while installing e.g. SetPassword Controller was not found.

**Comment by kaystrobach** [comment]
Will add that - thanks.

**Comment by kaystrobach** [comment]
@ochorocho just pushed it to the neos docs portal:

https://docs.neos.io/neos/content?node=%2Fsites%2Fsite%2Fnode-0ioqdofmp9zx2%2Fnode-2iultm9vod202%2Fnode-2s8hnzohnlx93%40user-kaystrobach%3Blanguage%3Den

Review seems to be pending

**Comment by ochorocho** [comment]
@kaystrobach thanks for adding this to the docs. The link takes me to the Neos Login, don't have an acount.

> I'm wondering if FLOW can be configured to put the Packages/Libraries and Packages/Framework inside the docker container in custom paths
I don't think this is configurable. But maybe someone in Neos Slack channel knows better :-)

**Comment by kaystrobach** [comment]
Should be in the composer-installer if there is an option, but there is none:

https://github.com/neos/composer-plugin/blob/1.0/Classes/Installer.php

**Comment by kaystrobach** [comment]
Will keep this issue updated one the recipe is publicly available.

**Comment by kaystrobach** [comment]
snapshot of the content already written:

* [Local Development Environment with drud-ddev - Cookbooks - Neos CMS - Neos Docs.pdf.pdf](https://github.com/drud/ddev/files/2758615/Local.Development.Environment.with.drud-ddev.-.Cookbooks.-.Neos.CMS.-.Neos.Docs.pdf.pdf)

I will update the uri pointing to the document once it got published.

**Comment by ochorocho** [comment]
@kaystrobach this document looks complete to me and covers all areas needed, like xdebug and package:freeze command.

**Comment by kaystrobach** [comment]
it's published now:

* https://docs.neos.io/cms/cookbooks/local-development-environment-with-drud-ddev

@rfay 

* if you see any problems on that page, please tell me.
* maybe you can link it from the ddev documentation?

**Comment by rfay** [comment]
Awesome. Yes, it makes great sense to link to it. In fact that might be a way to link to lots of external docs. I'm going to think how to do that best.

**Comment by ftrojahn** [comment]
> it's published now:
> 
> * https://docs.neos.io/cms/cookbooks/local-development-environment-with-drud-ddev
> 
Link is not reachable - may be this is the right one:
https://docs.neos.io/cms/installation-development-setup/all-platforms-using-ddev-and-docker

Using 'start from scratch', not working:

* change to directory is missing:
    ```
    mkdir neos-example
    cd neos-example
    ddev config`
    ```

* needed to change document root (if not ... getting Forbidden error from nginx):
`docroot: "Web/" `

* don't know if webcache should work under linux or something other is missing, but I get:
    ```
    ddev logs -s bgsync -f
    No running service container bgsync was found`
    ```

* setup works smoothly, neos demo site is reachable ... but trying backend login on /neos:
    ```
    Error 40x: (400 or 401)
    ddev web container: 400 (Bad Request) or 401 (Unauthorized) errors.`
    ```

**Comment by KaffDaddy** [comment]
> * setup works smoothly, neos demo site is reachable ... but trying backend login on /neos:

Same here. I am stuck at the same point. The backend of neos is not reachable. Also I cannot access the website through ssl. Any hints?
My config.yaml
```
APIVersion: v1.6.0
name: neos.insomniaonline
type: php
docroot: Web
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
  - neos.insomniaonline
mariadb_version: "10.2"
webcache_enabled: false
nfs_mount_enabled: true
provider: default
working_dir:
  web: /var/www/html
omit_containers:
  - dba
  - ddev-ssh-agent
```


and the docker-compose.env.yaml:
```
version: '3.6'

services:
  web:
    environment:
      - FLOW_CONTEXT=Development/Ddev
      - FLOW_PATH_TEMPORARY_BASE=/tmp/Flow
      - FLOW_REWRITEURLS=1
```
