### ISSUE TITLE
Documentation: using ddev in gitlab ci

### ISSUE THREAD

**Issue by kaystrobach** [drud/ddev#1369]
**Is your feature request related to a problem? Please describe.**

we all want to test our software

**Describe the solution you'd like**

* a recipe in the docs, which describes how to use ddev together with gitlab ci

1. either with docker compose to build the app from ddev recipe
2. or better use dind and start ddev during build, run tests, e.g. behat and stop it all again.

**Describe alternatives you've considered**

* build custom service definition including custom services etc.

**Additional context**

**Comment by rfay** [comment]
Could you say what you mean by "use ddev together with gitlab ci"? What would you want to accomplish? What is the role of ddev in this? ddev is intended to be a local development tool, and everything about it is built for that, nothing for other purposes (like automated testing or production or staging deployment).

**Comment by kaystrobach** [comment]
Sure, ddev makes it easy to spin up a dev env - perfect.

The same env could potentially be used for behat and functional testing.

Just thinking of:

* ddev start
* ddev import-db
* behat

Behat could then be executed against the ddev the devs also know from local development / or atleast a very similar one.

For advanced testing one would also need chrome and firefox, but this maybe out of scope for now.

**Comment by rfay** [comment]
People have absolutely used behat and related technologies for testing in ddev context; I haven't heard of anybody using it in an automated context. Might just work.

**Comment by kaystrobach** [comment]
I use it locally a lot - that’s why i came up with the idea. 

Will investigate that further and maybe bring up an recipe for that. Would be nice to keep that open issue so long and maybe a short review by you once it’s written.

**Comment by kaystrobach** [comment]
What i found is that esp. for small side projects easy setups help people to get started with testing. And reducing redundancy also helps keeping speed.

**Comment by rfay** [comment]
See also: [behat tests in BLT](https://github.com/drud/ddev/issues/1329)

**Comment by rfay** [comment]
I'm going to close this for now because it's outside the scope of what ddev is intended for, but the conversation can certainly continue, and docs on places like blogs or Stack Overflow are way more than welcome. Thanks!

**Comment by ochorocho** [comment]
@kaystrobach did you manage to get ddev running in GitLab CI? 

```yaml
ddev-initialize:
  stage: project-template-test
  image: docker:latest
  services:
    - name: docker:dind
  when: always
  before_script:
    - apk add curl bash
    - adduser ddev --disabled-password
    - docker info
  script:
    - bash
    - su ddev
    - curl -fsSL https://ddev.com/install.sh | bash
    - ddev --version
    - whoami
    - ddev typo3-init
```

Getting `This script must NOT be run with sudo/root. Please re-run without sudo.` because switch user does not work.

**Comment by rfay** [comment]
You can just download the appropriate `ddev` binary instead of running the script. But you will have to figure out how to run `ddev` with non-root permissions to get things done.

**Comment by ochorocho** [comment]
This is not perfect, but works pretty good so far:
```
ddev-initialize:
  stage: project-template-test
  image: docker:latest
  services:
    - name: docker:dind
  when: always
  before_script:
    - apk add bash sudo
    - adduser -D ddev -g "ddev" -s /bin/bash -D ddev
    - docker info
    - |
      echo "ddev ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ddev && chmod 0440 /etc/sudoers.d/ddev
      unamearch=$(uname -m)
      case ${unamearch} in
      x86_64) ARCH="amd64";
      ;;
      aarch64) ARCH="arm64";
      ;;
      arm64) ARCH="arm64"
      ;;
      *) printf "${RED}Sorry, your machine architecture ${unamearch} is not currently supported.\n${RESET}" && exit 106
      ;;
      esac
      wget "https://github.com/ddev/ddev/releases/download/v1.23.1/ddev_linux-${ARCH}.v1.23.1.tar.gz"
      tar xfvz "ddev_linux-${ARCH}.v1.23.1.tar.gz"
      mv ddev /usr/local/bin/
  script:
    - chown -R ddev:ddev ./* # THIS IS NOT GOOD, IIRC, docker:latest should use the ddev user
    - su ddev -c "ddev --version"
    - su ddev -c "ddev typo3-init" # Initializes a TYPO3 instance using ddev
```

@rfay are you interested in having a dedicated container for ddev? 
My idea would be to extend the "docker:latest" container and include ddev in a multi-arch image.

**Comment by rfay** [comment]
Hi @ochorocho - I know that at least one team already uses https://hub.docker.com/r/ddev/ddev-gitpod-base/ for this on gitlab. I don't know how an DnD image built for gitpod works out for them, but they seem to be doing it. It's amd64 only, because gitpod only has amd64. 

I'd love to have you maintain a general gitlab solution for DDEV.

**Comment by tyler36** [comment]
We have a self-hosted Gitlab where I work. Would be interested in a solution.

**Comment by ochorocho** [comment]
Hey, made some progress.

A few issues i bumped into, if you know how to solve these, let me know :-)
https://github.com/ochorocho/ddev-docker/issues

The image is available here (or see `.gitlab-ci.yml`):
https://github.com/users/ochorocho/packages/container/package/ddev-docker

**Comment by ochorocho** [comment]
Currently i'm facing a permission issue.
I hve to set permissions using `sudo chown -R ddev:ddev /builds` to allow the `ddev` user to start the project.

Does anyone have an idea how to fix/avoid this? 

```
ddev-initialize:
  stage: project-template-test
  image:
    name: ghcr.io/ochorocho/ddev-gitlab-ci:v1.23
  services:
    - name: docker:dind
entrypoint.sh"]
  when: always
  needs: [] # Run job immediately
  script:
    - sudo chown -R ddev:ddev /builds # <-- THIS should not be needed in the final image
    - ddev start
```

**Comment by tyler36** [comment]
Something looks off in the `entrypoint` line above.

**Comment by ochorocho** [comment]
> Something looks off in the `entrypoint` line above.

Sorry, fixed that.

**Comment by ochorocho** [comment]
@tyler36 the image is working and tested on gitlab.com runners :-)
Would you mind testing it as well?

⚠️ Not tested on self-hosted GitLab instances so far. This may require additional runner config (guess the the docker:dind service needs priviliged mode).

```
ddev-initialize:
  stage: project-template-test
  image: ghcr.io/ochorocho/ddev-gitlab-ci:v1.23
  variables:
    # Remove "umask 0000" usage, so DDEV has permissions on the cloned repository
    # see https://docs.gitlab.com/runner/configuration/feature-flags.html#available-feature-flags
    FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: 1
  services:
    - name: docker:dind
  when: always
  script:
    - ddev --version
    # ... do things
```
