### ISSUE TITLE
Hook system overhaul: Access any service, support other commands, user-defined hooks

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1372]
**Is your feature request related to a problem? Please describe.**

There are a number of oversights in our hook system and fixing them up would make a lot of people happy even if it disrupted their workflow a bit:

* Allow access to any container/service. For example, one should be able to execute an exec hook on the db container, or on an arbitrary npm service. (https://github.com/drud/ddev/issues/1038)
* Allow other post-xxx hooks (like post-composer) (https://github.com/drud/ddev/issues/1071)
* Consider allowing user-defined hooks. (https://github.com/drud/ddev/issues/638)
* Allow custom commands, perhaps based on hooks.
* [Add composer to hook commands #1321](https://github.com/drud/ddev/issues/1321)
* [post hooks like snapshot, snapshot-restore, pre-ssh? #1071 ](https://github.com/drud/ddev/issues/1071)
* [Consider arbitrary commands, and perhaps thus pre and post hooks for those commands #638](https://github.com/drud/ddev/issues/638)
* [Allow users to create and trigger arbitrary hooks](https://github.com/drud/ddev/issues/638) also relates to this.

**Comment by wizonesolutions** [comment]
I'm using post-start to kick off a Docker container on the host. It's a headless Chrome container; it's hard to get working within DDEV for now because it expects pages loaded through it to be requested by IP or localhost, and DDEV internal IPs are not stable, but the `host.docker.internal` IP is.

I run it `-d --rm` and would like to kill it "`pre-rm`" (which would also remove it), but there's no hook for that.

The hook would just be in `config.yaml` like now. My start one looks like:

```
hooks:
  post-start:
  - exec: touch ./-
  - exec-host: /bin/sh run-behat-requirements.sh
```

So I'd expect it to become:

```
hooks:
  post-start:
  - exec: touch ./-
  - exec-host: /bin/sh run-behat-requirements.sh
  pre-rm: # or maybe pre-stop if the other PR gets merged
  - exec-host: docker kill ddev-fps-chromeheadless
```
