### ISSUE TITLE
Add timezone config to config.yml

### ISSUE THREAD

**Issue by RobertLang** [drud/ddev#1417]
**Is your feature request related to a problem? Please describe.**
In some php projects (plain php projects for shopware) I get warning messages that the timezones of database and php are different. I have to add additional configuration files to the .ddev folder to correct timezone settings of web and database container with our timezone settings in php. 

**Describe the solution you'd like**
I would like to have a new config value for timezone that is used in all containers (and if possible in the php.ini as well)
```
# configuration in config.yaml
timezone: Europe/Berlin
```

**Describe alternatives you've considered**
I have added two files to correct timezone settings
```
# .ddev/php/php.ini
[Date]
date.timezone = Europe/Berlin
```
```
# .ddev/docker-compose.timezone.yaml
version: '3.6'

services:
  web:
    environment:
      - TZ=Europe/Berlin
  db:
    environment:
      - TZ=Europe/Berlin
```
