### ISSUE TITLE
Connection Refused issue running javascript behat tests in DDEV on a sub-domain

### ISSUE THREAD

**Issue by mdolnik-eelzee** [drud/ddev#1602]
I have a behat test environment in Drupal 7 where everything is currently working for js and non-js behat tests.

I want to change the project url to have a subdomain (ie: `mysite.ddev.local` to `sub.mysite.ddev.local`)

So I change `.ddev/config.yaml` from:
```yml
additional_hostnames: []
```
to:
```yml
additional_hostnames:
  - sub.mysite
```

And change `behat.yml` from:
```yml
default:
  extensions:
    Behat\MinkExtension:
      base_url: 'http://mysite.ddev.local'
```
to:
```yml
default:
  extensions:
    Behat\MinkExtension:
      base_url: 'http://sub.mysite.ddev.local'
```

(I am not changing the `$base_url` in `settings.php` because it is commented out)

And when I run the same test that works on the non-sub-domain site with only the changes above, I get the error:
```
Form field with id|name|label|value|placeholder "Username" not found. (Behat\Mink\Exception\ElementNotFoundException)
```
And I get the following screenshot:
<a href="https://i.imgur.com/oYd6swc.png"><img src="https://i.imgur.com/oYd6swc.png" style="width:105px;height:88px;"></a>

I tried ssh'ing into the selenium container via `ddev ssh --service selenium-hub` and pinging the site via `ping sub.mysite.ddev.local` and it is able to make a connection. (Note: I [needed to install ping first](https://stackoverflow.com/a/39901446/11229173))

The sub-domain site works with no issues when running in a normal browser (outside of behat)

If I try and run the behat test on the regular domain when I have the sub-domain set up (ie: only change `.ddev/config.yaml` and not `behat.yml` above) the test fails with the same issue.

Un-commenting `$base_url` in `settings.php` and setting the correct url doesn't help anything.

Is there anything else I should configure when trying to run behat on a sub-domain in ddev?

**Comment by rfay** [comment]
Is this the same as or related to today's Stack Overflow question? https://stackoverflow.com/questions/56160100/how-to-fix-curl-exec-call-hanging-when-xdebug-is-enabled

I assume you have a docker-compose.selenium-hub.yaml that you're using, or something like that. Could you please provide it? It would help to know also what you patterned it off of if you have a link to that. 

And of course, the requested `ddev version` would help us a lot.  

My bet is that you have a docker-compose.selenium-hub.yaml that has a single host in the external_links part of the stanza, rather than one for each of your subdomains. 

```
    external_links:                         
    - "ddev-router:d8git.ddev.local"        
    - "ddev-router:a.ddev.local"            
    - "ddev-router:b.ddev.local"            
    - "ddev-router:c.ddev.local"            
    - "ddev-router:d.ddev.local"            
```

Also, if you're not running ddev v1.8.0 (released this week) because a key bug was fixed there that affected this type of behavior. https://github.com/drud/ddev/issues/1235

Let us know!

**Comment by mdolnik-eelzee** [comment]
> Is this the same as or related to today's Stack Overflow question?
Nope, I haven't seen that post, and it seems like it's the same setup, but I am not dealing with xdebug issues.

> I assume you have a docker-compose.selenium-hub.yaml that you're using, or something like that. Could you please provide it?
Yes I am, here is the contents of `docker-compose.selenium.yml`
```yml
version: '3.6'
services:
  selenium-hub:
    image: selenium/standalone-chrome:latest
    container_name: ddev-${DDEV_SITENAME}-selenium-standalone-chrome
    ports:
    - "4444"
    external_links:
    - ddev-router:$DDEV_HOSTNAME
  web:
    depends_on:
    - selenium-hub
    links:
    - selenium-hub:selenium-hub
```

> And of course, the requested ddev version would help us a lot.
I'm using `1.5.2`

> My bet is that you have a docker-compose.selenium-hub.yaml that has a single host in the external_links part of the stanza, rather than one for each of your subdomains.
You bet correctly, making the following change to `docker-compose.selenium.yml` fixed my issue:
```yml
    external_links:
    - ddev-router:$DDEV_HOSTNAME
```
to:
```yml
    external_links:
    - ddev-router:$DDEV_HOSTNAME
    - ddev-router:sub.mysite.ddev.local
```

And I didn't need to upgrade ddev...

Thanks so much for your support.
