### ISSUE TITLE
Missing documentation for Blackfire

### ISSUE THREAD

**Issue by Ben305** [drud/ddev#1606]
The release notes for 1.8.0 state that Blackfire is now already included. Unfortunately, I have no clue how Blackfire can be used. I tried using an additional docker-compose.yml, but profiling in Chrome fails.

```yaml
version: '3.6'
services:
  blackfire:
    container_name: ddev-${DDEV_SITENAME}-blackfire
    image: blackfire/blackfire
    ports: ['8707']
    environment:
      BLACKFIRE_SERVER_ID: my-server-id
      BLACKFIRE_SERVER_TOKEN: my-server-token
  web:
    links:
      - blackfire:$DDEV_HOSTNAME
```
