### ISSUE TITLE
Document how to install: Elasticsearch

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev#1659]
**Is your feature request related to a problem? Please describe.**
As a sub-ticket of #978, it would be useful if we could collect more details on how to install, and configure, other programs. For this issue, Elasticsearch.

**Describe the solution you'd like**
Documentation on how to install Elasticsearch.

**Comment by rfay** [comment]
There is a recipe at https://stackoverflow.com/questions/54575785/how-can-i-use-an-elasticsearch-add-on-container-service-with-ddev, it was originally presented as #1320 , but didn't get any traction or reviews.

**Comment by rfay** [comment]
This should be transplanted into drud/ddev-contrib, there's a category for services there.

**Comment by IT-Cru** [comment]
@rfay: Tested your docker-compose.elasticsearch.yaml code snippet from stackoverflow.com on DDEV 1.9 API with Drupal 8 + elasticsearch_connector + search_api modules. Works like a charme.

I only updated elasticsearch docker image to 6.8.2 in your provided code snippet.

I will also try testing with DDEV 1.10 API and elasticsearch 7.x in the next days.

**Comment by rfay** [comment]
There's also another Elasticsearch example in the ddev-contrib queue at https://github.com/drud/ddev-contrib/pull/8

**Comment by aguerrerowk** [comment]
Hello,

im facing troubles trying to upgrade the current version from 5.6 to 6.8.0

**Error**

![image](https://user-images.githubusercontent.com/58917057/75688482-92a99780-5c6d-11ea-9930-7a5cf2472290.png)

**docker-compose.elasticsearch.yaml**
```
version: '3.6'
services:
  elasticsearch:
    container_name: ddev-${DDEV_SITENAME}-elasticsearch
    hostname: ${DDEV_SITENAME}-elasticsearch
    image: elasticsearch:6.8.0
    ports:
      - "9200"
      - "9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=9200
      - node.max_local_storage_nodes=3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ".:/mnt/ddev_config"
  web:
    links:
      - elasticsearch:elasticsearch

volumes:
  elasticsearch:
    name: "${DDEV_SITENAME}-elasticsearch"
```
