### ISSUE TITLE
Bash history is not saved when container exists due to 'ddev stop'

### ISSUE THREAD

**Issue by wizonesolutions** [drud/ddev#1801]
**Describe the bug**
Bash history is not saved when container exists due to 'ddev stop'. It is only saved when explicitly `exit`ing a `ddev ssh` session. This is understandable, but my workflow is typically to just `ddev stop` when I'm done without first existing my `ssh` session. This feels natural.

**To Reproduce**
1. `ddev start`
2. `ddev ssh`
3. Run some commands within the `ssh` session, maybe `echo "Command 1."`, `echo "Command 2."`, etc.; something you can recognize easily later.
4. WITHOUT exiting the session, in another terminal run `ddev stop`.
5. Run `ddev start` again and `ddev ssh` to connect to the web container again.
6. Press the up arrow to view previously-run commands.

**Expected behavior**
The previously-run commands should appear when pressing up or searching with Ctrl-R (reverse-i-search).

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: [e.g. Windows 10, macOS High Sierra]
Manjaro Linux 18.0.4
 - Docker version information (use `docker version`) and insert it here.
```
Client:
 Version:           19.03.1-ce
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        74b1e89e8a
 Built:             Fri Aug 16 14:00:42 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.1-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       74b1e89e8a
  Built:            Fri Aug 16 13:58:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.7.m
  GitCommit:        85f6aa58b8a3170aec9824568f7a31832878b603.m
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information (use `ddev version`)
```
DDEV-Local version	v1.10.2                        
commit            	v1.10.2                        
db                	drud/ddev-dbserver:v1.10.0-10.2
dba               	drud/phpmyadmin:v1.10.0        
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.10.2    
docker            	19.03.1-ce                     
docker-compose    	1.24.1                         
os                	linux                          
router            	drud/ddev-router:v1.10.0       
web               	drud/ddev-webserver:v1.10.2    
```
 - config.yaml contents for the misbehaving project
```
APIVersion: v1.10.2
name: fps
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- dev.fillpdf-service.com
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
hooks:
  post-start:
  - exec: touch ./-
  - exec: touch ../"Standard input code"
  - exec: touch "Standard input code"
host_db_port: "32500"
use_dns_when_possible: true
timezone: ""


# This config.yaml was created with ddev version v1.10.2 
[snip]
```
> - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

I do; no. I'm near-certain that doesn't affect this :)

**Additional context**
> Add any other context about the problem here. Thanks!
