### ISSUE TITLE
mkcert error on Travis upon creating the web container

### ISSUE THREAD

**Issue by AronNovak** [drud/ddev#1848]
**Describe the bug**
In Travis CI environment, in a not steadily reproducible way, we face with the following error:

`Failed to start schuler-scholar: web container failed: log=, err=container exited, please use 'ddev logs -s web` to find out why it failed`

After adding `ddev logs` to the CI script, that's the output of that:
```
+ sudo chown -R 2000:2000 /mnt/ddev-global-cache/ /home/travis/.ssh /home/travis/.drush /home/travis/.gitconfig /home/travis/.my.cnf

+ '[' -d /mnt/ddev_config/homeadditions ']'

+ cp -r /mnt/ddev_config/homeadditions/. /home/travis/

+ mkcert -install

ERROR: failed to save CA key: open /mnt/ddev-global-cache/mkcert/rootCA-key.pem: permission denied
```

**To Reproduce**
On a Travis-based environment, start a DDEV instance with Solr aside, skipping the configuration for `mkcert` there.

**Expected behavior**
`ddev` web container should start.

**Screenshots**
![image](https://user-images.githubusercontent.com/114076/65514797-5152d600-dede-11e9-9b66-c6c5cf735da6.png)

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: 
```
Build language: php
Build group: stable
Build dist: trusty
Build id: 128908179
Job id: 238529129
Runtime kernel version: 4.4.0-101-generic
travis-build version: 24382795bc479c6eb9a0651f15dd00c2dca32750
Build image provisioning date and time
Tue Dec  5 19:58:13 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
 - Docker version information (use `docker version`) and insert it here.
```
docker-ce_18.06.3~ce~3-0~ubuntu_amd64.deb
```
 - ddev version information (use `ddev version`)
```
v1.11.0
```
 - config.yaml contents for the misbehaving project
```
APIVersion: v1.11.0
name: foobar-foobar
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "8081"
router_https_port: "8043"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
hooks:
  post-import-db:
  - exec: drush config-set system.site name Foobar
  - exec: drush en -y environment_indicator
  - exec: drush cr
  - exec: drush uli
  post-start:
  - exec: drush site-install foobar -y --db-url=mysql://db:db@db/db --account-pass=admin
      --existing-config
  - exec: drush en foobar_migrate
  - exec: drush sapi-c
  - exec: drush migrate:import --group=foobar
  # For Code sniffer
  - exec: composer global require drupal/coder:^8.3.1
  - exec: composer global require dealerdirect/phpcodesniffer-composer-installer
  # For Drupal's private files
  - exec: mkdir /var/www/private
  - exec: drush uli
use_dns_when_possible: true
timezone: ""
```
 - Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
N/A
