### ISSUE TITLE
Twig templates cached somewhere?

### ISSUE THREAD

**Issue by Ben305** [drud/ddev#1876]
I'm running Pimcore (based on Symfony) with DDEV. Everything is working fine but there are serious problems when changing Twig templates.

After DDEV has been started, the Twig template is compiled and everything is working as expected. Changes made to the twig files are immediately reflected in the container, but these changes get lost somewhere which means the first served content is always shown in the browser.

This only happens with Twig templates (file.html.twig) but it's working fine with PHP templates.

What could be wrong here?

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: macOS 10.14 / 10.15
 - Docker version information: 19.03.2
 - ddev version information: 1.11.1
 - config.yaml 

```yml
APIVersion: v1.10.2
name: pimcore
type: php
docroot: web
php_version: "7.3"
webserver_type: apache-fpm
router_http_port: "8000"
router_https_port: "8443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
```
