### ISSUE TITLE
(Windows) WordPress wpskeleton composer failure Installer::postPackageInstall handling the post-package-install event terminated with an exception

### ISSUE THREAD

**Issue by televators** [drud/ddev#1877]
**Describe the bug**
I expected DDEV to do the thing since I'm on a pretty fresh install of W10 Pro. After running the `ddev composer create wordpress/skeleton --no-interaction --prefer-dist`, it fails with no helpful error message. This is the line: 
```
> Installer::postPackageInstall
Script Installer::postPackageInstall handling the post-package-install event terminated with an exception
  [ErrorException]
  symlink(): No such file or directory
```
Literally just installed Chocolatey, then DDEV via choco, and then did the quickstart, copy+pasting so I couldn't mess it up. Everything was fine until getting to the `ddev composer create ...` line. I've tried in CMD (as admin) and PowerShell (as admin). I did not try through WSL since I still am not familiar with it but I'll do so after writing this for the heck of it.

**To Reproduce**
Follow the quickstart instructions for WordPress on Windows 10 Pro 1809 using Docker 19.0.3.1 and DDEV-Local 1.11.1.

**Expected behavior**
Complete running through the install scripts successfully and creating the project environment.

**Screenshots**
![What I'm getting in the terminal](https://i.postimg.cc/7LpGsf6h/ddev-win10pro-bug.jpg)

**Version and configuration information (please complete the following information):**
 - Windows 10 Pro v1809 (Build 17763.775)
 - Docker Engine - Community, 19.03.1
 - DDEV-Local version v1.11.1
 - config.yaml:
```yaml
APIVersion: v1.11.1
name: wp-example
type: php
docroot: ""
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""


# This config.yaml was created with ddev version v1.11.1 
# webimage: drud/ddev-webserver:v1.11.0
# dbimage: drud/ddev-dbserver:v1.11.0-10.2
# dbaimage: drud/phpmyadmin:v1.11.0
# bgsyncimage: drud/ddev-bgsync:v1.11.0
# However we do not recommend explicitly wiring these images into the
# config.yaml as they may break future versions of ddev.
# You can update this config.yaml using 'ddev config'.

# Key features of ddev's config.yaml:

# name: <projectname> # Name of the project, automatically provides
#   http://projectname.ddev.site and https://projectname.ddev.site

# type: <projecttype>  # drupal6/7/8, backdrop, typo3, wordpress, php

# docroot: <relative_path> # Relative path to the directory containing index.php.

# php_version: "7.2"  # PHP version to use, "5.6", "7.0", "7.1", "7.2", "7.3", "7.4"

# You can explicitly specify the webimage, dbimage, dbaimage lines but this
# is not recommended, as the images are often closely tied to ddev's' behavior,
# so this can break upgrades.

# webimage: <docker_image>  # nginx/php docker image.
# dbimage: <docker_image>  # mariadb docker image.
# dbaimage: <docker_image>
# bgsyncimage: <docker_image>

# router_http_port: <port>  # Port to be used for http (defaults to port 80)
# router_https_port: <port> # Port for https (defaults to 443)

# xdebug_enabled: false  # Set to true to enable xdebug and "ddev start" or "ddev restart"
# Note that for most people the commands 
# "ddev exec enable_xdebug" and "ddev exec disable_xdebug" work better,
# as leaving xdebug enabled all the time is a big performance hit.

# webserver_type: nginx-fpm  # Can be set to apache-fpm or apache-cgi as well

# timezone: Europe/Berlin
# This is the timezone used in the containers and by PHP;
# it can be set to any valid timezone, 
# see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# For example Europe/Dublin or MST7MDT

# additional_hostnames:
#  - somename
#  - someothername
# would provide http and https URLs for "somename.ddev.site"
# and "someothername.ddev.site".

# additional_fqdns:
#  - example.com
#  - sub1.example.com
# would provide http and https URLs for "example.com" and "sub1.example.com"
# Please take care with this because it can cause great confusion.

# upload_dir: custom/upload/dir
# would set the destination path for ddev import-files to custom/upload/dir.

# working_dir:
#   web: /var/www/html
#   db: /home
# would set the default working directory for the web and db services. 
# These values specify the destination directory for ddev ssh and the 
# directory in which commands passed into ddev exec are run. 

# omit_containers: ["dba", "ddev-ssh-agent"]
# would omit the dba (phpMyAdmin) and ddev-ssh-agent containers. Currently
# only those two containers can be omitted here.
# Note that these containers can also be omitted globally in the 
# ~/.ddev/global_config.yaml or with the "ddev config global" command.

# nfs_mount_enabled: false
# Great performance improvement but requires host configuration first.
# See https://ddev.readthedocs.io/en/stable/users/performance/#using-nfs-to-mount-the-project-into-the-container

# webcache_enabled: false (deprecated)
# Was only for macOS, but now deprecated. 
# See https://ddev.readthedocs.io/en/stable/users/performance/#using-webcache_enabled-to-cache-the-project-directory

# host_https_port: "59002"
# The host port binding for https can be explicitly specified. It is
# dynamic unless otherwise specified.
# This is not used by most people, most people use the *router* instead
# of the localhost port.

# host_webserver_port: "59001"
# The host port binding for the ddev-webserver can be explicitly specified. It is
# dynamic unless otherwise specified.
# This is not used by most people, most people use the *router* instead
# of the localhost port.

# host_db_port: "59002"
# The host port binding for the ddev-dbserver can be explicitly specified. It is dynamic
# unless explicitly specified.

# phpmyadmin_port: "1000"
# The PHPMyAdmin port can be changed from the default 8036

# mailhog_port: "1001"
# The MailHog port can be changed from the default 8025

# webimage_extra_packages: [php-yaml, php7.3-ldap]
# Extra Debian packages that are needed in the webimage can be added here

# dbimage_extra_packages: [telnet,netcat]
# Extra Debian packages that are needed in the dbimage can be added here

# use_dns_when_possible: true
# If the host has internet access and the domain configured can 
# successfully be looked up, DNS will be used for hostname resolution 
# instead of editing /etc/hosts
# Defaults to true

# project_tld: ddev.site
# The top-level domain used for project URLs
# The default "ddev.site" allows DNS lookup via a wildcard
# If you prefer you can change this to "ddev.local" to preserve
# pre-v1.9 behavior.

# ngrok_args: --subdomain mysite --auth username:pass
# Provide extra flags to the "ngrok http" command, see 
# https://ngrok.com/docs#http or run "ngrok http -h"

# provider: default # Currently either "default" or "pantheon"
#
# Many ddev commands can be extended to run tasks before or after the 
# ddev command is executed, for example "post-start", "post-import-db", 
# "pre-composer", "post-composer"
# See https://ddev.readthedocs.io/en/stable/users/extending-commands/ for more
# information on the commands that can be extended and the tasks you can define
# for them. Example:
#hooks:
```
 - **Custom configs?**
Nope. Literally installed Chocolatey, installed ddev, copy pasted the quickstart instructions from the docs for WordPress.*

**Additional context**
I have WSL 1 installed along with git-bash. Not using either in this scenario but they are live and on my machine.
