### ISSUE TITLE
ddev-router does not use 443 vhost?

### ISSUE THREAD

**Issue by webflo** [drud/ddev#1878]
**Describe the bug**

I had some trouble how ddev handles https connections to the backend. All https requests hit the web container on port 80. The vhost on port 443 is never used.

I tried to create a custom docker-compose.environment.yml to override the configuration.

```
version: "3.6"
services:
  web:
    environment:
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:443
```

But ddev fails to start. The router configuration is invalid with this override.

```
Failed to restart example: ddev-router failed to become ready: logOutput=2019/10/10 07:24:07 [emerg] 1649#1649: host not found in upstream "example.localhost-443" in /etc/nginx/conf.d/default.conf:178
```
