### ISSUE TITLE
instrumentation_opt_in not respected (mistaken overwrite of global_config.yaml)

### ISSUE THREAD

**Issue by rfay** [drud/ddev#1882]
**Describe the bug**

If you have a new version of ddev and you ddev start you get this prompt every time you start. Even if you say "n" every time. 

```
It looks like you have a new ddev release.
May we send anonymous ddev usage statistics and errors?
To know what we will see please take a look at
https://ddev.readthedocs.io/en/latest/users/cli-usage/#opt-in-usage-information
Permission to beam up? [Y/n] (yes):
```

**To Reproduce**

* Any environment
* Have more than one project going and listed in ~/.ddev/global_config.yaml
* Create a project of type "wordpress" (doesn't need any code, just type of wordpress)
* `ddev start`
* ~/.ddev/global_config.yaml will have been rewritten with default information.

**Expected behavior**

**Screenshots**

**Version and configuration information (please complete the following information):**

This is recreatable on Windows and macOS

**Additional context**
Add any other context about the problem here. Thanks!

**Comment by graham73may** [comment]
Having trouble with being asked multiple times, my `global_config.yaml` file: 

```
APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: true
router_bind_all_interfaces: false
last_used_version: v1.12.0
mkcert_caroot: C:\Users\xxxxx\AppData\Local\mkcert
project_info:
  sei.org:
    approot: C:\Users\xxxxx\sites\sei.org

# You can turn off usage of the dba (phpmyadmin) container and/or
# ddev-ssh-agent containers with
# omit_containers[\"dba\", \"ddev-ssh-agent\"]
# and you can opt in or out of sending instrumentation the ddev developers with
# instrumentation_opt_in: true # or false
#
# instrumentation_user: <your_username> # can be used to give ddev specific info about who you are
# developer_mode: true # (defaults to false) is not used widely at this time.
# router_bind_all_interfaces: false  # (defaults to false)
#    If true, ddev-router will bind http/s, PHPMyAdmin, and MailHog ports on all
#    network interfaces instead of just localhost, so others on your local network can
#    access those ports. Note that this exposes the PHPMyAdmin and MailHog ports as well, which
#    can be a major security issue, so choose wisely. Consider omit_containers[dba] to avoid
#    exposing PHPMyAdmin.

```

**Comment by rfay** [comment]
This annoying bug is solved by `export DDEV_NO_INSTRUMENTATION=true` I think. We'll definitely try to get it sorted out in the next release.

**Comment by rfay** [comment]
I remain unable to recreate this problem, even though I was probably the first to stumble on it. If you have this problem, please make sure to provide complete info about your operating system and ddev version.

**Comment by graham73may** [comment]
This might be a coincidence, but I thought it worth mentioning. 

I'm not being asked to opt in/out when I `ddev start` Drupal projects, it happens for all Wordpress / Custom projects. 

![image](https://user-images.githubusercontent.com/6642498/72049835-b2e55780-32b7-11ea-9921-ee491944fa99.png)

Environment info:
```
DDEV-Local version      v1.12.0
commit                  v1.12.0
db                      drud/ddev-dbserver-mariadb-10.2:v1.12.0
dba                     drud/phpmyadmin:v1.12.0
ddev-ssh-agent          drud/ddev-ssh-agent:v1.12.0
docker                  19.03.5
docker type             Docker Desktop For Windows
docker-compose          1.25.0-rc4
os                      windows
router                  drud/ddev-router:v1.12.0
web                     drud/ddev-webserver:v1.12.1
```

```
WindowsBuildLabEx                                       : 18362.1.amd64fre.19h1_release.190318-1202
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsInstallationType                                 : Client
WindowsProductName                                      : Windows 10 Pro
WindowsRegisteredOrganization                           : Microsoft
```

**Comment by unn** [comment]
Mac 10.14.6 (18G2022): I've seen this myself after upgrading to 1.12.1, but I'm being prompted from time to time when I `ddev start`.

Some what interestingly, My ~/.ddev/global_config.yaml got recreated, because a dba container came up, and I know with 100% certainty that I had `omit_containers: [dba]`.

**Comment by rfay** [comment]
Thanks for that clue @graham73may - It gives another angle to chase it from.

Thanks @unn - I have seen global_config.yaml get recreated also. Maybe that's the bottom line, it would make sense. When it happens, of course, ddev forgets about existing stopped projects (that aren't running in docker). Since I haven't been able to find a code path where the opt-out isn't respected, maybe there's a code path where the file gets destroyed and recreated.

I had been able to blame recreation of global_config.yaml on running the golang tests in my local environment, and that process removes and (tries to put back) the existing global_config.yaml, but is likely not reliable, especially when tests are stopped in the middle.

**Comment by rfay** [comment]
#2040 makes some efforts to understand this, maybe prevent it. But I'm still unable to reproduce.

In the future if this comes up ask these things:
* Are you using an alternate TLD or FQDN (not ddev.site)?
* Are you using mkcert (is there a valid mkcert root CA installed)? 
* What is your normal set of commands that you routinely do?
* Please provide your global config (~/.ddev/global_config.yaml)
* Have you manually edited ~/.ddev/global_config.yaml?
* Do you use any custom ports for http or https?
* Did you delete any projects?

**Comment by graham73may** [comment]
**Are you using an alternate TLD or FQDN (not ddev.site)?**
No, just the defaults that ddev sets up

**Are you using mkcert (is there a valid mkcert root CA installed)?**
Yes, setup and https working. 

**What is your normal set of commands that you routinely do?**
`cd` to directory
`ddev start`
`hit enter when it asks about usage statistics`

**Please provide your global config (~/.ddev/global_config.yaml)**
```
APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: true
router_bind_all_interfaces: false
last_used_version: v1.12.0
mkcert_caroot: C:\Users\name\AppData\Local\mkcert
project_info:
  project.org:
    approot: C:\Users\name\sites\project.org
```

**Have you manually edited ~/.ddev/global_config.yaml?**
No (well, yes, when you told me to earlier in this issue, but it's back to default now). 

**Do you use any custom ports for http or https?**
No

**Did you delete any projects?**
I don't very often, I have deleted a project one this machine once upon a time

**Comment by rfay** [comment]
@graham73may are you saying this is still happening to you all the time? 

But you have opted IN. It doesn't ask after you opt in. It only asks people who *haven't* opted in. 

It sounds like ddev isn't reading the global_config.yaml that you have pasted here, so that might be a great clue.  It may be looking for global config somewhere else? 

Could you please show some things like:
```
echo $HOME
ls -l $HOME/.ddev/global_config.yaml
cat $HOME/.ddev/global_config.yaml
```

**Comment by graham73may** [comment]
@rfay Yes happens every time for me at the moment. 

Correct, `instrumentation_opt_in: true` is in the config, but it still asks. 

Hopefully! Here's the output of those commands:

```
❯ echo $HOME

C:\Users\graha
```

```
❯ ls -l $HOME/.ddev/global_config.yaml

    Directory: C:\Users\graha\.ddev

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       22/01/2020     09:54           1154 global_config.yaml
```

```
❯ cat $HOME/.ddev/global_config.yaml

APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: true
router_bind_all_interfaces: false
last_used_version: v1.12.0
mkcert_caroot: C:\Users\graha\AppData\Local\mkcert
project_info:
  project.com:
    approot: C:\Users\graha\sites\project.com

# You can turn off usage of the dba (phpmyadmin) container and/or
# ddev-ssh-agent containers with
# omit_containers[\"dba\", \"ddev-ssh-agent\"]
# and you can opt in or out of sending instrumentation the ddev developers with
# instrumentation_opt_in: true # or false
#
# instrumentation_user: <your_username> # can be used to give ddev specific info about who you are
# developer_mode: true # (defaults to false) is not used widely at this time.
# router_bind_all_interfaces: false  # (defaults to false)
#    If true, ddev-router will bind http/s, PHPMyAdmin, and MailHog ports on all
#    network interfaces instead of just localhost, so others on your local network can
#    access those ports. Note that this exposes the PHPMyAdmin and MailHog ports as well, which
#    can be a major security issue, so choose wisely. Consider omit_containers[dba] to avoid#    exposing PHPMyAdmin.
```

**Comment by rfay** [comment]
Thank you so much. Could you please search your entire system for other instances of global_config.yaml?

**Comment by graham73may** [comment]
I don't trust Windows search to find **anything**! 

Using powershell, 1 result:

```

❯ gci -Recurse -Filter "global_config.yaml" -File -ErrorAction SilentlyContinue -Path "C:\"


    Directory: C:\Users\graha\.ddev


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       22/01/2020     09:54           1154 global_config.yaml

```

**Comment by rfay** [comment]
Do you use powershell to run ddev? Maybe that's the key. Could you try running in git bash (which is by far the recommended environment)

**Comment by graham73may** [comment]
I tend to use Powershell for most things if I can, just had a go with git bash, same result:

```
$ ddev start
It looks like you have a new ddev release.
May we send anonymous ddev usage statistics and errors?
To know what we will see please take a look at
https://ddev.readthedocs.io/en/stable/users/cli-usage/#opt-in-usage-information
Permission to beam up? [Y/n] (yes):
Starting ipdet.org...
```

**Comment by rfay** [comment]
Well, sorry to say this but it's absolutely fantastic that you can recreate this so easily :) It's clear that it's either unable to read the file or unable to write it, or it's reading the wrong file.

Would you mind `ddev poweroff` and then `mv~/.ddev ~/.ddev.bak` and then `ddev start` ?

**Comment by graham73may** [comment]
Ha, one positive...

First run, as expected it asks:
```
A new update is available! please visit https://github.com/drud/ddev/releases/tag/v1.12.2 to download the update.
For upgrade help see https://ddev.readthedocs.io/en/stable/#installation
It looks like you have a new ddev release.
May we send anonymous ddev usage statistics and errors?
To know what we will see please take a look at
https://ddev.readthedocs.io/en/stable/users/cli-usage/#opt-in-usage-information
Permission to beam up? [Y/n] (yes):
```

Moment of truth time... `ddev stop` then `ddev start` and I get the same:

```
> ddev start
It looks like you have a new ddev release.
May we send anonymous ddev usage statistics and errors?
To know what we will see please take a look at
https://ddev.readthedocs.io/en/stable/users/cli-usage/#opt-in-usage-information
Permission to beam up? [Y/n] (yes):
```

**Comment by rfay** [comment]
I think the path forward for this might be a custom build that outputs what it's doing with that global_config.yaml. Would you be open to that?  I could actually bundle that in with an environment variable controlling it also.

**Comment by graham73may** [comment]
Interesting. I've been watching my global config file:

`ddev stop`ped everything, it looks like this: 

```
APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: false
router_bind_all_interfaces: false
last_used_version: ""
mkcert_caroot: C:\Users\graha\AppData\Local\mkcert
project_info: {}
```

`ddev start` a project, it changes to this: 
```
APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: true
router_bind_all_interfaces: false
last_used_version: v1.12.0
mkcert_caroot: C:\Users\graha\AppData\Local\mkcert
project_info:
  project.org:
    approot: C:\Users\graha\sites\project.org
```

BUT, when I `ddev stop`, it goes back to: `false 
```
APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: false
router_bind_all_interfaces: false
last_used_version: ""
mkcert_caroot: C:\Users\graha\AppData\Local\mkcert
project_info: {}
```

**Comment by rfay** [comment]
Ah, so *stop* is overwriting it with empty info. 

I imagine that `ddev list`, which should show your stopped project, doesn't.

**Comment by graham73may** [comment]
> Ah, so _stop_ is overwriting it with empty info.
> 
> I imagine that `ddev list`, which should show your stopped project, doesn't.

You're correct!

```
❯ ddev list
No ddev projects were found.
```

Is this a useful clue?

**Comment by rfay** [comment]
Does this happen if you have two projects? Could you create a junk project to see?

**Comment by graham73may** [comment]
Ok so I started project one, then project two. Config looked like this: 

```
APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: true
router_bind_all_interfaces: false
last_used_version: v1.12.0
mkcert_caroot: C:\Users\graha\AppData\Local\mkcert
project_info:
  projectone.org:
    approot: C:\Users\graha\sites\projectone.org
  projecttwo.org:
    approot: C:\Users\graha\sites\projecttwo.org
```

I stopped project one and the config got wiped: 
```
APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: false
router_bind_all_interfaces: false
last_used_version: ""
mkcert_caroot: C:\Users\graha\AppData\Local\mkcert
project_info: {}
```

Note: Project two started and didn't ask me about usage stats. I guess that means it reads the config successfully when it does exist?

**Comment by rfay** [comment]
So if you start both again, but stop project 2... what happens? Config gets wiped that way too?

**Comment by graham73may** [comment]
Starting in the same order, project info is being added to: 
1 - Wordpress start
2 - Drupal start

I stopped the Drupal site, the `project_info` remains intact. 

```
project_info:
  projectone.org:
    approot: C:\Users\graha\sites\projectone.org
  projecttwo.org:
    approot: C:\Users\graha\sites\projecttwo.org
```

Ok.. let's try and swap them around. 

If I do this: 
1 - Drupal start
2 - Wordpress start

After 1, project_info has that  1 project. 
After 2... the project_info is wiped and I just have: 

```
project_info:
  project-started-second.org:
    approot: C:\Users\graha\sites\project-started-second.org
```

(I've not stopped the wordpress one at this point)

Is there an issue with ddev in the Wordpress project? 

I'm going to try doing this switcheroo with 2 wordpress projects. Will report back.

**Comment by graham73may** [comment]
I'm going to try with 2 other WP projects, in case the one above is defective somehow.

Wordpress A start, it's added to the blank config (and asks about stats)
Wordpress B start, it's overwritten the config and removed Wordpress A (and asks about stats).

**Comment by rfay** [comment]
You're making some incredible and much appreciated progress. I'm not completely tracking at this point, so if you can summarize when you completely understand it it will be appreciated.

**Comment by graham73may** [comment]
# Case 1
1. Wordpress start
1. Drupal start

Config has both sites

- Then Wordpress stop

Results in wiped config

---

# Case 2
1. Wordpress start
1. Drupal start

Config has both sites

- Then Drupal stop

Results in config that still has both sites and stats setting

---

# Case 3
1. Wordpress start
1. Wordpress start

Config only ever has one site in `project_info`, the second WP project overrides the first one. 

- Then Wordpress 2 stop

Results in wiped config

---

# Case 4
1. PHP project
1. PHP Project

Config has both projects

```
project_info:
  ddev-test-1:
    approot: C:\Users\graha\sites\ddev-test-1
  ddev-test-2:
    approot: C:\Users\graha\sites\ddev-test-2
```

Then stopping one, the config remains intact. 

---

Just to finish up, I'm going to add a new Wordpress project in to Case 4, expecting the config to have 3 projects. 

I run `ddev start` and ***right away*** the config gets wiped to: 

```
APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: false
router_bind_all_interfaces: false
last_used_version: ""
mkcert_caroot: C:\Users\graha\AppData\Local\mkcert
project_info: {}
```
Both php test's from case 4 are gone. 
The config is back to square one, so it asks me about stats again.

I enter `yes` and the config  gets updated to have ONLY the wordpress project. 

```
APIVersion: v1.12.0
omit_containers: []
instrumentation_opt_in: true
router_bind_all_interfaces: false
last_used_version: v1.12.0
mkcert_caroot: C:\Users\graha\AppData\Local\mkcert
project_info:
  wordpress-number-four.org:
    approot: C:\Users\graha\sites\wordpress-number-four.org
```

---

Is ddev start treated different for drupal/wordpress/php projects types?
`type: wordpress` seems to be the difference?
