### ISSUE TITLE
Use behat with selenium 

### ISSUE THREAD

**Issue by Gonzalo2683** [drud/ddev#1910]
## Update:
@rfay  I am close to achieving it, now I am using an image called zalenium that establishes a good base, now I am already able to run and run the browser from the ddev web container, the problem is that the site shows an error:

> This site can't be reached

I have tried several answers of different issues published here and in stackoverflow, but I can't get selenium to take the correct ddev-router route. Any ideas.

I have added the following files to try to configure selenium with ddev, behat.

```
DDEV-Local version	v1.10.2                        
commit            	v1.10.2                        
db                	drud/ddev-dbserver:v1.10.0-10.2
dba               	drud/phpmyadmin:v1.10.0        
ddev-ssh-agent    	drud/ddev-ssh-agent:v1.10.2    
docker            	19.03.2                        
docker-compose    	1.24.1                         
os                	linux                          
router            	drud/ddev-router:v1.10.0       
web               	drud/ddev-webserver:v1.10.2
```

**docker-compose.selenium.yaml**
```
version: '3.6'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    #hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "America/Montevideo"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --cbtEnabled false
            --lambdaTestEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - CBT_USERNAME
      - CBT_AUTHKEY
      - LT_USERNAME
      - LT_ACCESS_KEY
    external_links:
      - ddev-router:$DDEV_HOSTNAME
      - ddev-router:base.ddev.site


  mock:
    image: elgalu/google_adwords_mock
    depends_on:
      - zalenium
    ports:
      - 8080:8080
    tty: true
    environment:
      - MOCK_SERVER_PORT=8080

```
**docker-compose.override.yml**
```
version: '3.6'

services:
  web:
    depends_on:
      - db
      - zalenium
    links:
      - zalenium:zalenium
```

**behat.yml**
```
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  gherkin:
    cache: ~
  extensions:
    Behat\MinkExtension:
      goutte: ~
      base_url: "http://base.ddev.site"
      browser_name: chrome
      javascript_session: selenium2
      #show_cmd: "open %s"
      #selenium2: ~
      selenium2:
        wd_host: 172.18.0.1:4444/wd/hub
        capabilities: {"extra_capabilities":{"idleTimeout":300, "chromeOptions":{"w3c":false}}}
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drupal'
      drupal:
        drupal_root: ./
      drush:
        alias: '@desa.local'
```
If I run behat without making use of selenium (I don't use the @javascript tag) the validations are executed correctly, but I can't do the same validation through selenium. This site can't be reached

**prueba.feature**
```
Feature: Check aprobador role
  In order to check custom role
  As aprobador user role

  @javascript
  Scenario: Test selenium works
    Given I am on "/"
    And I should see "Sitio Base"
    And I am on "institucional/contacto"
    And I fill in "edit-nombre-completo" with "some text"
```
When I run **vendor/bin/behat ./features/prueba.feature**
As I explain, I don't see the browser running with the test.
Any ideas about this?
