### ISSUE TITLE
Fix project renaming issues - renaming project can leave global config with two projects

### ISSUE THREAD

**Issue by wolffc** [drud/ddev#1933]
**Describe the bug**
if you rename your project ddev seems to ad a new entry for the same project over and over again

Updated: If you edit an existing configured project and change its name, ddev will let you start that; it shouldn't, just as it doesn't allow the same name to be used.

**To Reproduce**
1. create a new project `ddev config` everything default 
2. run the following script (to change the project name multiple times)
```bash
#!/usr/bin/env bash

# enable error reporting and show executed commands
set -ex

changename()
{
  # stop to have a clean state
  ddev stop
  # reconfigure project name
  echo "name: $1" > .ddev/config.site.yaml
  # restart the project with the new name
  ddev start;
}

changename "foo-example"
changename "bar-example"
changename "foo-example"
changename "bar-example"
```
3 `ddev list` shows somthing like
```
bar-example             php    C:/src/ddev-namechange         https://bar-example.ddev.site     running
bar-example             php    C:/src/ddev-namechange         https://bar-example.ddev.site     running
bar-example             php    C:/src/ddev-namechange         https://bar-example.ddev.site     running
```

**Expected behavior**
ddev should not dublicate the project every time it is renamed. 

**Version and configuration information (please complete the following information):**
 - Windows 10 (19.17763 Build 17763)
- Docker
 docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 

 - ddev  v1.11.2
 - config.yaml contents for the misbehaving project
```
APIVersion: v1.11.2
name: foo-bar
type: php
docroot: ""
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: true
timezone: ""
```
 - just the config.site.yaml which is generated by the above script. 

**Additional context**
we have a Polymorph Project (one project we use to deploy multiple sites). we rename the project so docker keeps the old container data an we are able to fast-switch between different sites.

**Comment by Graloth** [comment]
I can confirm this issue, can replicate it as per the issue description, but initially encountered it when adding the same hostname twice by mistake.

An addition to this issue is that once I've removed the duplicated hostnames, it continues to appear multiple times in `ddev list` both when the project is stopped and started.

**Comment by rfay** [comment]
Could you folks please provide the contents of the project_info stanza of ~/.ddev/global_config.yaml when this happens? Thanks.

@wolffc I expect that your polymorph project does violate the concept of unique project names on the machine... There can be only one ddev project of a given name on a machine.

**Comment by Graloth** [comment]
@rfay I'm not sure what you mean, I do not have any `global_config.yaml` inside my .ddev directory, I assume it's just the default `config.yaml` that is initially generated by DDEV.

If that is the case, this is mine

```yaml
APIVersion: v1.11.2
name: foo-bar
type: drupal8
docroot: web
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
project_tld: dk.localhost
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
use_dns_when_possible: false
timezone: "Europe/Copenhagen"
```

This is a clean installed test project (Drupal in my case). The only changes was to add timezone, turn off use dns and add a custom 

I haven't been able to replicate it again manually, only using the bash script mentioned in the issue description. Though that changes the name, while I encountered it initially when changing the `additional_hostnames`, this has stopped happening.
I still have the initial project that I encountered it on showing up twice when I do `ddev list` even though it's stopped and I have no other projects with it's name. (I would like to share it, but the name could be a giveaway on what the project is about and I'm not sure I'm allowed to publicly share that).

To me it seems like the old project names aren't properly removed, as both my initial project that I encountered it on and the one I tested with here, appear several times in `ddev list` even after they have been stopped and the project removed (it only removed one of them from the list, not all).

To summarise:

- Am unable to replicate the original way I encountered this issue (by having an additional hostname with the same name as project)
- Replicating it using the bash script in issue description does indeed replicate the issue.
- Using `ddev stop --remove-data` properly removes one of the entries from `ddev list` but the rest are still left on the list.

I hope this information helps.

**Comment by Graloth** [comment]
I just re-read your comment @rfay and saw that you're referencing the .ddev directory in my user directory :) my bad.

I would like to share it, but it contains even more references to projects that I cannot share, so I have removed them from the file, one of them was the one where I encountered the issue initially.

```yaml
APIVersion: v1.11.2
omit_containers: []
instrumentation_opt_in: false
router_bind_all_interfaces: false
last_used_version: v1.11.2
mkcert_caroot: /Users/dsj/Library/Application Support/mkcert
project_info:
  donationform:
    approot: /Users/dsj/Projects/Repositories/donationform
  foo-bar:
    approot: /Users/dsj/Projects/Repositories/foo-bar
  foo-example:
    approot: /Users/dsj/Projects/Repositories/foo-bar
  graloth:
    approot: /Users/dsj/Projects/Repositories/graloth

# You can turn off usage of the dba (phpmyadmin) container and/or
# ddev-ssh-agent containers with
# omit_containers[\"dba\", \"ddev-ssh-agent\"]
# and you can opt in or out of sending instrumentation the ddev developers with
# instrumentation_opt_in: true # or false
#
# instrumentation_user: <your_username> # can be used to give ddev specific info about who you are
# developer_mode: true # (defaults to false) is not used widely at this time.
# router_bind_all_interfaces: false  # (defaults to false)
#    If true, ddev-router will bind http/s, PHPMyAdmin, and MailHog ports on all
#    network interfaces instead of just localhost, so others on your local network can
#    access those ports. Note that this exposes the PHPMyAdmin and MailHog ports as well, which
#    can be a major security issue, so choose wisely. Consider omit_containers[dba] to avoid
#    exposing PHPMyAdmin.
```

What I did notice was that the initial project I had showing double, was because when I generated the config for the project it took the folder name as project name and I changed that afterwards (while messing with the additional hostnames), I think that might have caused my initial issue, since it appeared twice in the file above, one with the folder name and one with the actual project name.

**Comment by rfay** [comment]
That would definitely do it. ddev does try its best to prevent this, but that definitely causes the behavior.

**Comment by wolffc** [comment]
same here: 
```
APIVersion: v1.11.2
omit_containers: []
instrumentation_opt_in: true
router_bind_all_interfaces: false
last_used_version: v1.6.0
mkcert_caroot: C:\Users\cwolff\AppData\Local\mkcert
project_info:
  autotranslator-console:
    approot: C:\src\autotranslator-console
  bar-example:
    approot: C:\src\ddev-namechange
  cockpit-aer-de:
    approot: C:\src\ddev-cockpit
  cockpit-best-de:
    approot: C:\src\ddev-cockpit
  cockpit-conso-de:
    approot: C:\src\ddev-cockpit
  cockpit-dtt-de:
    approot: C:\src\ddev-cockpit
  cockpit-picasso-com:
    approot: C:\src\ddev-cockpit
  foo-bar:
    approot: C:\src\ddev-namechange
  foo-example:
    approot: C:\src\ddev-namechange
```
cockpit-* are my initial polymorph project while foo/bar are the test project from above
