### ISSUE TITLE
Site very slow after upgrade to v1.12.0 because xdebug is enabled by default

### ISSUE THREAD

**Issue by facine** [drud/ddev#2008]
Every time I restart my site (on macOS Catalina), xdebug is enabled and I can't stop it if I don't use sudo.

```
$ drush php-eval "var_dump(xdebug_is_debugger_active());"
/var/www/html/vendor/drush/drush/src/Commands/core/PhpCommands.php(28) : eval()'d code:1:
bool(true)

$ disable_xdebug
touch: cannot touch '/var/lib/php/modules/7.4/fpm/disabled_by_admin/xdebug': Permission denied
Disabled xdebug

$ drush php-eval "var_dump(xdebug_is_debugger_active());"
/var/www/html/vendor/drush/drush/src/Commands/core/PhpCommands.php(28) : eval()'d code:1:
bool(true)

$ sudo disable_xdebug
Disabled xdebug

$ drush php-eval "var_dump(xdebug_is_debugger_active());"
 [error]  Error: Call to undefined function xdebug_is_debugger_active() in eval() (line 1 of /var/www/html/vendor/drush/drush/src/Commands/core/PhpCommands.php(28) : eval()'d code)
```

**Comment by rfay** [comment]
Does your project's .ddev/config.yaml perhaps have `xdebug_enabled: true` in it?

I don't see this behavior.

Please create a simple "junk" project and config and start it. Make a phpinfo.php with content `<?php phpinfo();` Then visit junk.ddev.site/phpinfo.php and review.

**Comment by rfay** [comment]
It does look like you messed up the modules directory by using sudo. But you should be able to `ddev restart` to fix that.

**Comment by facine** [comment]
Thank you @rfay 

xdebug is disabled:
```
% grep -rin xdebug .ddev/config*
.ddev/config.yaml:9:xdebug_enabled: false
.ddev/config.yaml:60:# xdebug_enabled: false  # Set to true to enable xdebug and "ddev start" or "ddev restart"
.ddev/config.yaml:62:# "ddev exec enable_xdebug" and "ddev exec disable_xdebug" work better,
.ddev/config.yaml:63:# as leaving xdebug enabled all the time is a big performance hit.
```

Creating a dummy project works fine.

ddev restart doesn't resolve the problem.

**Comment by facine** [comment]
I've stopped and removed all the containers/images but I didn't fix anything.

**Comment by rfay** [comment]
Could you post your .ddev/config.yaml please? Do you have any config.*.yaml overrides, or any docker-compose.*.yaml overrides? Or of course post-start hooks.

After `ddev restart`, please post the output of `ddev ssh` followed by `php -i | grep xdebug`

Obviously since you can create a dummy project that works correctly, it's something about your project...

**Comment by facine** [comment]
> config.yaml
```
APIVersion: v1.12.0
name: local.project
type: drupal8
docroot: docroot
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: true
provider: default
omit_containers: [dba]
webimage_extra_packages: [graphicsmagick]
project_tld: es
use_dns_when_possible: true
timezone: Europe/Madrid
```

> config.hooks.yaml
```
hooks:
  post-import-db:
    - exec: drush cr
    - exec: drush uli
  pre-start:
    # Make sure we are using our development settings.
    - exec-host: cp -f .ddev/settings.local.php docroot/sites/project.es/settings.local.php
```

> docker-compose.chrome.yaml
```
version: '3.6'

services:
  chrome:
    image: selenium/node-chrome:3.11.0-dysprosium
    container_name: "${DDEV_SITENAME}_chrome"
    volumes:
      - /dev/shm:/dev/shm
      - ./:/var/www/html:cached # User-guided caching
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_HOSTNAME
    external_links:
      - ddev-router:$DDEV_HOSTNAME
```

> docker-compose.hub.yaml
```
version: '3.6'

services:
  hub:
    image: selenium/hub:3.11.0-dysprosium
    container_name: "${DDEV_SITENAME}_hub"
    volumes:
       - ./:/var/www/html:cached # User-guided caching
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_HOSTNAME
    external_links:
      - ddev-router:$DDEV_HOSTNAME
    #ports:
    #  - "4444:4444"
```

> docker-compose.override.yaml
```
version: '3.6'

services:
  web:
    environment:
      # Fix 'Cannot parse server name for external Xdebug connection.'.
      # @see https://confluence.jetbrains.com/display/PhpStorm/Debugging+PHP+CLI+scripts+with+PhpStorm#DebuggingPHPCLIscriptswithPhpStorm-2.StarttheScriptwithDebuggerOptions
      - PHP_IDE_CONFIG=serverName=$DDEV_HOSTNAME
      # Enable Drush Launcher Xdebug compatibility.
      # @see https://github.com/drush-ops/drush-launcher#xdebug-compatibility
      - DRUSH_ALLOW_XDEBUG=1
```

> docker-compose.wkhtmltox.yaml
```
version: '3.6'

services:
  wkhtmltox:
    image: gogap/go-wkhtmltox:latest
    container_name: "${DDEV_SITENAME}_wkhtmltox"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_HOSTNAME
```

> web-build/Dockerfile
```
ARG BASE_IMAGE=drud/ddev-webserver:v1.12.1
FROM $BASE_IMAGE

# Disable redis.
RUN phpdismod redis
```

> After ddev restart, please post the output of ddev ssh followed by php -i | grep xdebug
```
/etc/php/7.2/cli/conf.d/20-xdebug.ini,
extension 'xdebug' detected
xdebug
xdebug support => enabled
xdebug.auto_trace => Off => Off
xdebug.cli_color => 0 => 0
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 0 => 0
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => On => On
xdebug.default_enable => On => On
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.file_link_format => no value => no value
xdebug.filename_format => no value => no value
xdebug.force_display_errors => Off => Off
xdebug.force_error_reporting => 0 => 0
xdebug.gc_stats_enable => Off => Off
xdebug.gc_stats_output_dir => /tmp => /tmp
xdebug.gc_stats_output_name => gcstats.%p => gcstats.%p
xdebug.halt_level => 0 => 0
xdebug.idekey => no value => no value
xdebug.max_nesting_level => 512 => 512
xdebug.max_stack_frames => -1 => -1
xdebug.overload_var_dump => 2 => 2
xdebug.profiler_aggregate => Off => Off
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => Off => Off
xdebug.profiler_enable_trigger_value => no value => no value
xdebug.profiler_output_dir => /tmp => /tmp
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_addr_header => no value => no value
xdebug.remote_autostart => On => On
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => On
xdebug.remote_handler => dbgp => dbgp
xdebug.remote_host => host.docker.internal => host.docker.internal
xdebug.remote_log => no value => no value
xdebug.remote_log_level => 7 => 7
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.remote_timeout => 200 => 200
xdebug.scream => Off => Off
xdebug.show_error_trace => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => Off => Off
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_enable_trigger_value => no value => no value
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => /tmp => /tmp
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3
```

**Comment by rfay** [comment]
That's impressive. I always love to see what people are doing with ddev.

I love how you do `    - exec-host: cp -f .ddev/settings.local.php docroot/sites/project.es/settings.local.php`  - it's a great strategy. 

I think the obvious thing to do is to remove those extra configs one at a time until you find the one that's causing the problem. I'd probably start with the `phpdismod redis` in your web-build/Dockerfile. That would be better done in a post-start hook, but I wouldn't expect this from it.

**Comment by facine** [comment]
I love all you do 😍

You are right! The problem was `phpdismod redis`, I've moved it to a post-start hook and now works fine.

Thank you!

```
hooks:
  post-import-db:
    - exec: drush cr
    - exec: drush uli
  pre-start:
    # Make sure we are using our development settings.
    - exec-host: cp -f .ddev/settings.local.php docroot/sites/project.es/settings.local.php
  post-start:
    # Disable redis.
    - exec: sudo phpdismod redis && killall -HUP php-fpm
```
