### ISSUE TITLE
PHP7.4 Project fails to start if php extensions are added

### ISSUE THREAD

**Issue by Woeler** [drud/ddev#2092]
**Describe the bug**
The project fails to start when using PHP7.4 and adding any extra php extensions to the container. All errors and configs can be found below.

**To Reproduce**
1. Create a fresh DDEV project of the type "php"
2. Set the PHP version to 7.4
3. Add `webimage_extra_packages: [php7.4-ldap]` to your config.yaml (I have also experienced the same bug with php7.4-gmp)
4. Run `ddev start`
5. See that the ddev project fails to start

**Expected behavior**
The container should start normally with php7.4-ldap installed and activated.

**Screenshots**

**Version and configuration information (please complete the following information):**
 - Host computer OS and Version: Ubuntu 18.04
 - Docker version information (use `docker version`) and insert it here.
```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
 - ddev version information (use `ddev version`)
```
DDEV-Local version      v1.13.0                                
commit                  v1.13.0                                
db                      drud/ddev-dbserver-mariadb-10.2:v1.13.0
dba                     phpmyadmin/phpmyadmin:5                
ddev-ssh-agent          drud/ddev-ssh-agent:v1.13.0            
docker                  19.03.6                                
docker-compose          1.25.0-rc4                             
os                      linux                                  
router                  drud/ddev-router:v1.13.0               
web                     drud/ddev-webserver:v1.13.0 
```
 - config.yaml contents for the misbehaving project
```yaml
APIVersion: v1.13.0
name: my-typo3-org
type: php
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
nfs_mount_enabled: false
provider: default
omit_containers: [db, dba]
webimage_extra_packages: [php7.4-gmp]
use_dns_when_possible: true
timezone: ""
```

**Additional context**
DDEV Output on `ddev start`
```
Failed to start my-typo3-org: web container failed: log=phpstatus FAILED /var/www/html: OK mailhog FAILED , err=container /ddev-my-typo3-org-web unhealthy: phpstatus FAILED /var/www/html: OK mailhog FAILED
```

**How to temporarily resolve this issue**
Add a file named `docker-compose.test.yaml` to your .ddev folder with the following content:
```yaml
version: '3.6'
services:
  web:
    volumes:
      - type: tmpfs
        target: /run/php
```

Link to TYPO3 Slack conversation: https://typo3.slack.com/archives/C8TRNQ601/p1582730930033200
