### ISSUE TITLE
ddev: Failure with groupadd and single/double quotes on webImage

### ISSUE THREAD

**Issue by garvinhicking** [drud/ddev#2109]
I've got a Windows Home 64bit and use the Docker Toolbox. I'm able to use the t3master TYPO3 ddev git, so generally ddev and docker seem to work.

Versions: Docker Client 19.03.1, Docker Engine 19.03.5. DDev:
```
DDEV-Local version      v1.13.1
commit                  v1.13.1
db                      drud/ddev-dbserver-mariadb-10.2:v1.13.0
dba                     phpmyadmin/phpmyadmin:5
ddev-ssh-agent          drud/ddev-ssh-agent:v1.13.0
docker                  19.03.5
docker type             Docker Toolbox
docker-compose          1.25.0-rc4
os                      windows
router                  drud/ddev-router:v1.13.0
web                     drud/ddev-webserver:v1.13.1
```

However, trying to run a different project fails. This is the (to me) simple ddev config:

```
APIVersion: v1.13.1
name: t3dummy
type: typo3
docroot: htdocs
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.1"
nfs_mount_enabled: false
provider: default
hooks:
  post-start:
  - exec: composer install
  - exec: ansible-playbook -i build/config/hosts build/build.yml --limit local
omit_containers: [dba]
use_dns_when_possible: true
timezone: Europe/Berlin
```

After running ddv start, I get this:

```
Service 'web' failed to build: The command '/bin/sh -c (groupadd --gid $gid "$username" || groupadd "$username" || true) && (useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' --uid $uid "$username" || useradd  -l -m -s "/bin/bash" --gid "$username" --comment '' "$userna' returned a non-zero code: 2
```

To me this looks like there's a problem because the --comment option uses single quotes, where it should use double quotes. I am not familiar enough with docker/ddev to recognize where this is coming from.

I seem to not be able to manually edit the .ddev/.webimageBuild/Dockerfile to change those chars, as the file gets re-generated everytime dynamically. So my feeling is that ddev somehow injects this wrong internally?

(In a similar issue I found a note to the mariadb container issue; I tried using both 10.1 and 10.2 as mariadb_version, without change)
