### ISSUE TITLE
Add explicit support/project type for Mautic CMS

### ISSUE THREAD

**Issue by dennisameling** [drud/ddev#2154]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Mautic is an [open-source PHP Marketing Automation platform](https://www.mautic.org/). Developers can [contribute code](https://github.com/mautic/mautic/blob/staging/.github/CONTRIBUTING.md) or create [plugins/themes](https://developer.mautic.org/) as they like.

Lately, we've been trying to get more community contributors to use DDEV for Mautic development by providing [instructions on how to set up DDEV for Mautic](https://www.mautic.org/blog/developer/local-mautic-development-with-ddev), as it features PHP/Composer/MySQL/MailHog/PHPMyAdmin right out of the box. That's a fantastic developer experience once it's set up 😄 

When running `ddev config`, the following shows up:
```
Project Type: [drupal8, wordpress, typo3, backdrop, magento, drupal6, drupal7, php, magento2]
```
We would love to have Mautic in that list as well and are willing to provide code to make that happen. We mainly use the standard DDEV config, and just add one extra package to `.ddev/config.yaml`:

```
webimage_extra_packages: [php7.3-imap]
```

If one of the core contributors here could confirm if that's OK and point me in the right direction so I can see how to make this happen, I'll go ahead and do the necessary work 😊 

**Describe alternatives you've considered**
For now we just provide a [step by step guide](https://www.mautic.org/blog/developer/local-mautic-development-with-ddev) to new developers for setting up DDEV for Mautic

**Additional context**
The above explanation should provide enough context, if not please let me know :)

**Comment by rfay** [comment]
Thanks for this! 

Does mautic require custom nginx config? Do people mostly use Apache or Nginx?

What does mautic use an imap client for?

**Comment by dennisameling** [comment]
Thanks for the quick reply!

Both Apache and Nginx [are supported](https://www.mautic.org/download/requirements), but Apache works best out of the box (we have a [.htaccess](https://github.com/mautic/mautic/blob/staging/.htaccess) for URL rewriting).

Mautic uses the IMAP client for e-mail [Bounce management](https://docs.mautic.org/en/channels/emails/bounce-management) to monitor the inbox for bounce emails. So that when a user sends an email campaign, Mautic monitors an inbox through IMAP to find which emails have bounced.

Please let me know if there's anything I can do to provide help here :blush:

**Comment by rfay** [comment]
A PR would be welcome on this. Several CMSs are the result of community PRs. The results are better when real users work on it!

**Comment by hugronaphor** [comment]
Mautic 4.4 seems to working fine with default `php` type.
```
name: mautic-test
type: php
docroot: "docroot"
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.4"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "16"
webimage_extra_packages: [php7.4-imap]
timezone: "Europe/London"
```
