### ISSUE TITLE
Allow user-provided provider for alternate hosting providers to push/pull/etc

### ISSUE THREAD

**Issue by andy-blum** [drud/ddev#2194]
**Is your feature request related to a problem? Please describe.**
`ddev pull` is one of my favorite features to use with our pantheon-hosted sites, but I wish we had that capability for sites that are hosted on other providers

**Describe the solution you'd like**
I don't have a fully-baked idea of how this would work, but my initial thoughts would be to include a yaml file similar to the following:
```yml
environments:
  dev:
    connection_type: direct
    db:
      host: 127.0.0.1
      username: db
      password: db
      database: db
      port: 3306
  test:
    connection_type: direct
    db:
      host: proof.example.com
      username: db
      password: db
      database: db
      port: 3306
  live:
    connection_type: ssh
    ssh:
      host: example.com
      username: admin
      password: pass
      key: ~/.ssh/id_rsa.pub
      port: 
    db:
      host: localhost
      username: db
      password: db
      database: db
      port: 3306
```
and to include this in the config file with `provider: path/to/environments.yml`.

In this project running ddev pull would export a copy of the DB to the local machine and then import it into the project
