### ISSUE TITLE
.ddev/.gitignore not updated/maintained on start with projects of type 'php'

### ISSUE THREAD

**Issue by gilbertsoft** [drud/ddev#2200]
I had a little issue today with the DDEV RC:

On ddev start the new xdebug command was created as expected. But because you removed the api version check there was no warning and in the first place the .gitignore was not updated with the new command. So my first tought was you forgot to add the new command to the .gitignore generator but ofc the mistake was from my site not running ddev config.

My suggestion is now to also recreate the .gitignore at the startup to avoid this kind of error and this will make the devs life easier....

**Comment by rfay** [comment]
I'm unable to recreate this. I just did this test with v1.14.0-rc2

1. Edit .ddev/.gitignore (added a line)
2. ddev start

It was put back to the default .gitignore. 

Could you try that and see if you can figure out the difference between your experience and mine?

If you happened to accidentally have v1.14.0-rc1, there was a bug there where xdebug was in listed in the wrong directory in the .gitignore. Just to humor me, please do check `ddev --version`

**Comment by rfay** [comment]
Is there any chance that you've removed the #ddev-generated line at the top of the .gitignore, and thus taken over management of the .gitignore?

**Comment by gilbertsoft** [comment]
I'm working on a project last used with DDEV 1.13.1 and just executed `ddev start`. Then Git showed me the new xdebug command file. Will try it again...

**Comment by gilbertsoft** [comment]
Ok, still the same, `ddev start` does not create the .gitignore here. Checked the ddev version again `ddev version v1.14.0-rc2` which looks fine to me.
Tests I did:

- ddev stop
- removed the xdebug from .gitignore
- ddev start

- ddev stop
- removed .gitignore
- ddev start

Both did not create / update my .gitignore. Very strange....

**Comment by gilbertsoft** [comment]
Here's my current config, I started with this commit https://github.com/TYPO3/get.typo3.org/commit/0b948946e0d0e3f5f56d7be54027bcfe82f1a684:
```
name: get.typo3.org
type: php
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
- composer.typo3.org
additional_fqdns: []
mariadb_version: "10.2"
provider: default
hooks:
  post-start:
  - composer: install
  - composer: install -d satis
  - exec: /mnt/ddev_config/scripts/setup-db
  pre-start:
  - exec-host: .ddev/scripts/copy-dotenv
omit_containers: [db, dba]
use_dns_when_possible: true
timezone: Europe/Zurich
```
