### ISSUE TITLE
additional service breaks ddev describe with "panic: interface conversion: interface {} is int, not string"

### ISSUE THREAD

**Issue by ulrichmathes** [drud/ddev#2266]
A additional service broke the `ddev describe` command since ddev v1.14.0

```
$ ddev describe
panic: interface conversion: interface {} is int, not string

goroutine 1 [running]:
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).Describe(0xc00052e000, 0x0, 0x0, 0x8000100)
	/workdir/pkg/ddevapp/ddevapp.go:281 +0x34cb
github.com/drud/ddev/cmd/ddev/cmd.glob..func16(0x1598120, 0x15d3e20, 0x0, 0x0)
	/workdir/cmd/ddev/cmd/describe.go:38 +0x12d
github.com/spf13/cobra.(*Command).execute(0x1598120, 0x15d3e20, 0x0, 0x0, 0x1598120, 0x15d3e20)
	/workdir/vendor/github.com/spf13/cobra/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x159a1a0, 0x0, 0x0, 0x0)
	/workdir/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/workdir/vendor/github.com/spf13/cobra/command.go:864
github.com/drud/ddev/cmd/ddev/cmd.Execute()
	/workdir/cmd/ddev/cmd/root.go:140 +0x3c
main.main()
	/workdir/cmd/ddev/main.go:8 +0x20
```

**To Reproduce**
add .ddev/docker-compose.documentation.yaml with content:
```yaml
version: '3.6'
services:
  documentation:
    container_name: ddev-${DDEV_SITENAME}-documentation
    image: swaggerapi/swagger-ui
    ports:
      - 8080
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      VIRTUAL_HOST: $DDEV_HOSTNAME
      HTTP_EXPOSE: 8080
```

**Expected behavior**
No panic error.
And in best case: "Recognition of third-party services and describe them in `ddev describe`"

**Version and configuration information:**
 - Ubuntu 18.04
 - Docker version: 19.03.9
 - ddev version: v1.14.2

**Additional context**
Maybe there is some configuration for the new feature _Recognition of third-party services_ missing?
