### ISSUE TITLE
Environment variable DDEV_SITENAME no longer available?

### ISSUE THREAD

**Issue by NicoHaase** [drud/ddev#2382]
**Describe the bug**
In a project started with ddev 1.12.0, I'm using the following configuration file to run cronjobs in the existing web container:

config.akeneo-cronjobs.yaml

```
webimage_extra_packages: [--no-install-recommends cron]

hooks:
    post-start:
        - exec: echo -e "WEBSERVER_DOCROOT=${WEBSERVER_DOCROOT}\nDOCROOT=${DOCROOT}\nPHP_IDE_CONFIG=serverName=${DDEV_SITENAME}.ddev.site\n* * * * * ~/akeneo-cronrunner.sh > /tmp/cron" | crontab -
        - exec: sudo service cron start
        - exec: bin/console akeneo:batch:job-queue-consumer-daemon --env=prod >/dev/null 2>&1 &
```

Using the most current ddev 1.15.0, this does not longer work. The env variable `WEBSERVER_DOCROOT` no longer exists (as documented), but `DDEV_SITENAME` neither does. Through `ddev exec env`, I see a lot of env variables set (also those from ddev), but the site name is missing.

Is this intended behaviour?
