### ISSUE TITLE
Unable to use gulp-livereload on macOS

### ISSUE THREAD

**Issue by graham73may** [drud/ddev#2410]
**Describe the bug**
I've just moved from Windows to macOS, the only thing I'm having trouble with is getting [gulp-livereload](https://www.npmjs.com/package/gulp-livereload) to apply the updated styles. 

Does anyone have any experience setting up a Gulp watch task in a ddev site on macOS?
(For reference, it worked fine on Windows, usually these problems are the opposite way round :joy: )

**To Reproduce**
Start a WordPress project with the default ddev configs for a WP site. 

I've taken this from a WordPress project, structure is:

```
/wp-content/themes/{THEME_NAME}/assets/src/package.json
/wp-content/themes/{THEME_NAME}/assets/src/gulpfile.js
```
[gulp.zip](https://github.com/drud/ddev/files/4961057/gulp.zip)

From the host Run `npm install` inside the `src` folder to install all of our node_modules...

Once that's ready, run the gulp watch task on the host, when finished livereload will be ready to use!
Personally I'm running this all through PhpStorm -> Right click gulpfile.js -> Show Tasks -> Click the Watch task. 

This is the recommended Chrome extension to go along with livereload: 
https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei

Watched files:
```
/wp-content/themes/{THEME_NAME}/assets/scss/style.scss
/wp-content/themes/{THEME_NAME}/assets/scss/{loads of other .scss files that are included in to style.scss}
```

When a change is detected are compiling to:
```
/wp-content/themes/{THEME_NAME}/assets/css/style.css
/wp-content/themes/{THEME_NAME}/assets/css/style.min.css
```

**Expected behavior**

- [x] You make a change in an .scss file
- [x] This triggers the watch task, triggering the relevant gulp task in this case `build-css`
- [x] .css and .min.css are generated on the host successfully
- [ ] The browser automatically applies the new styles without requiring a full refresh

**Version and configuration information (please complete the following information):**

- Host computer OS and Version:  macOS Catalina
- Docker Desktop version `2.3.0.3`
- ddev version `v1.15.0`
- config.yaml contents for the misbehaving project `defaults for a WP project`
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? `none`

**config.yaml**

```yaml
APIVersion: v1.12.0
name: site.co.uk
type: wordpress
docroot: ""
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: true
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
hooks:
  post-import-db: []
use_dns_when_possible: true
timezone: ""
```

**Comment by graham73may** [comment]
Could be related to https://github.com/drud/ddev/issues/2361, however this has `nfs_mount_enabled: false`

**Comment by graham73may** [comment]
I have tried creating a `docker-compose.livereload.yaml` with:

```yaml
version: '3.6'

services:
  web:
    ports:
      - "35729:35729"
```

but this would cause the gulp-watch task on the host to fail, complaining that the port is not available. 

> ... Uhoh. Got error listen EADDRINUSE: address already in use :::35729 ...
> Error: listen EADDRINUSE: address already in use :::35729
