### ISSUE TITLE
Adding a pa11y Service

### ISSUE THREAD

**Issue by acouch** [drud/ddev#2414]
**Is your feature request related to a problem? Please describe.**
I'd like to run pa11y tests locally and in our travis ci.

**Describe the solution you'd like**
A link to a yaml file for this.

This is what I have so far. I've placed the file in ``.ddev/docker-compose.pa11y.yaml``:

```yml
version: '3.6'

services:
  pa11y:
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    image: prometsource/docker-pa11y-ci:0.10
    command: tail -f /dev/null
    external_links:
      - "ddev-router:${DDEV_SITENAME}.${DDEV_TLD}"
    volumes:
       - ./tests/pa11y/wcag2-config.json:/workspace/wcag2-config.json
```

I am having an issue with running the command. ``ddev exec -s pa11y ls`` does not bring up the pa11y container. Running ``docker-compose run pa11y /bin/bash -c "pa11y-ci --config /workspace/wcag2-config.json"`` doesn't work as the curl command in the container does not work.
