### ISSUE TITLE
exec-host output is not shown in console

### ISSUE THREAD

**Issue by NochEinKamel** [drud/ddev#2477]
**Describe the bug**
The output of an exec-host hook is not printed to the console.

**To Reproduce**
Add to config
```
hooks:
  post-start:
  - exec: "echo hi there && for item in 1 2 3 4 5; do echo $item: $(date); sleep 1; done"
  - exec-host: "echo host there && for item in 1 2 3 4 5; do echo $item: $(date); sleep 1; done"
```

(Re)start ddev project

Only the output of the "exec" command is show; the "exec-host" output is not shown:

> Executing post-start hook... 
=== Running task: Exec command 'echo hi there && for item in 1 2 3 4 5; do echo $item: $(date); sleep 1; done' in container/service 'web', output below 
hi there
1: Mon Aug 24 13:23:03 UTC 2020
2: Mon Aug 24 13:23:04 UTC 2020
3: Mon Aug 24 13:23:05 UTC 2020
4: Mon Aug 24 13:23:06 UTC 2020
5: Mon Aug 24 13:23:07 UTC 2020
=== Running task: Exec command 'echo host there && for item in 1 2 3 4 5; do echo $item: $(date); sleep 1; done' on the host (xxx), output below 
Restarted xxxx 
Your project can be reached at xxxx

**Expected behavior**
Output for both commands should be visible in the console

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop")
- ddev version: 1.15.3
- config.yaml: see above
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? No

**Additional context**
It's probably an side-effect from #2214 #2335 where the output was changed to stream
