### ISSUE TITLE
Adding an extra http server in web container with HTTP_EXPOSE environment variable

### ISSUE THREAD

**Issue by managume** [drud/ddev#2480]
I'm trying to add a new HTTP port to _web_ container using the following .ddev-docker-compose.env.yml file with no success:

```yaml
version: '3.6'

services:
  web:
    environment:
      - HTTP_EXPOSE=8000:8000
```
Also adding:

```yaml
ports:
 - 127.0.0.1::8000/tcp
```
Looking the comments in .ddev-docker-compose-base.yaml seems that there's an easy way to do it but dont.

```yaml
# HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
# To expose a container port to a different host port, define the port as hostPort:containerPort
- HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025
# You can optionally expose an HTTPS port option for any ports defined in HTTP_EXPOSE.
# To expose an HTTPS port, define the port as securePort:containerPort.
- HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025
```

 I've been searching in the documentation but no lucky. Any idea?

Thanks.

**Comment by rfay** [comment]
Could you please say a little about what is behind the port you're trying to expose? If it's not HTTP, it won't work, you'll need to just use the `expose` in docker-compose. 

Are you able to access the service you want on port 8000 from within the web container? `ddev ssh` and `curl http://localhost:8000` ?

**Comment by managume** [comment]
Now I'm testing it with [Sculpin dev server](https://sculpin.io/documentation/configuration/#development-and-production-environments) (port 8000), but I have the [same problem running Browsersync](https://stackoverflow.com/questions/59894698/ddev-run-browsersync-inside-the-container) (port 3000) within DDEV web container. Curl inside web container works following next steps but don't sculpin.ddev.site:8000

1. Create `.ddev-docker-compose.env.yaml`
```yaml
version: '3.6'
services:
  web:
    # ports is list of exposed *container* ports
    ports:
      - "127.0.0.1:$DDEV_HOST_WEBSERVER_PORT:80"
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:$DDEV_HOST_HTTPS_PORT:443"
    environment:
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.site:<port>
      # To expose a container port to a different host port, define the port as hostPort:containerPort
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,8000:8000
```
2. `ddev restart`
3. `ddev ssh`
   3.1. `/var/www/html/vendor/bin/sculpin generate --watch --server`
   3.2. `curl http://localhost:8000` ✅ 
4. Open `sculpin.ddev.site:8000` in browser ❌ 

Tried same project with a custom docker-compose.yml and all works fine.

**Comment by rfay** [comment]
One thing you're doing is exposing port 8000 two different ways - you don't want to do that. You are using port 8000 in the `ports` section, exposing it there, and then also trying to expose it via ddev-router. I think one or the other would work, but not both. I'm surprised you don't get an error. 

This works for me as a docker-compose.extraserver.yaml:
```
version: '3.6'
services:
  web:
    ports:
      - "8000"
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,8001:8000
```
If I then run the PHP server inside the docroot with `php -S 0.0.0.0:8000` I can `curl http://mysite.ddev.site:8001` and it works out fine. 

The way you were doing it, you were exposing the port  directly on port 8000 and *then* asking the router to also bind to port 8000 and route http traffic there.
