### ISSUE TITLE
Add config.yaml option to fail an action when hooks fail

### ISSUE THREAD

**Issue by AronNovak** [drud/ddev#2536]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/114076/94688938-87ffcf80-032e-11eb-967f-bc7a77d35fa1.png)
```yml
hooks:
  post-start:
    - exec: exit 1
    # Private files directory.
    - exec: mkdir /var/www/private

    # Install profile
    - exec: drush site-install server -y --existing-config

    # Compile theme
    - exec-host: ddev robo theme:compile

    # Generate one-time login link
    - exec: drush uli
```

Let's say we have a failing post-start command in our custom configuration.
Right now there's no trivial way to know if all the commands succeeded or not, as `ddev start` exits with code 0 even if something in the hooks failed.

**Describe the solution you'd like**
We could stop on the first failure for `post-start` and propagate the received exit code for the caller of `ddev start`.

**Describe alternatives you've considered**
As it might break existing configs, it could be a config option, like `stop_on_hook_failure: true` , with a default value false, it would ensure the backwards compatibility.
