### ISSUE TITLE
ddev auth ssh should fail if ssh-agent opted out

### ISSUE THREAD

**Issue by AronNovak** [drud/ddev#2573]
**Describe the bug**
```
travis@bar-program-web:/var/www/html/.pantheon$ git pull origin master
Failed to add the host to the list of known hosts (/home/.ssh-agent/known_hosts).
codeserver.dev.mooo-385a-4@codeserver.dev.moo-385a-4b1f-a745-32d9de56b5de.drush.in's password: 

travis@bar-program-web:/var/www/html/.pantheon$ ls -l -h /home/.ssh-agent/known_hosts
ls: cannot access '/home/.ssh-agent/known_hosts': No such file or directory
```

Before that, the `ddev auth ssh` completes successfully:
```
travis@travis-job-moo-dd2e-4b88-b445-14a9bb20a2bc:~/build/Gizra/bar-program/drupal$ ddev auth ssh
Identity added: /home/travis/.ssh/id_rsa (aaron@bar-program-web)
Identity added: /home/travis/.ssh/tmate (/home/travis/.ssh/tmate)
travis@travis-job-36598630-dd2e-4b88-b445-14a9bb20a2bc:~/build/Gizra/bar-program/drupal$ 
```

Moreover, `ssh-add` cannot list the key inside DDEV, but can outside:
```
travis@travis-job-36598630-dd2e-4b88-b445-14a9bb20a2bc:~/build/Gizra/bar-program/drupal$ ssh-add -L
ssh-rsa fdfdsfds/cfGb3c7B63sBDbh8Tiu1ChZBzIhfyQ== /home/travis/.ssh/id_rsa
travis@travis-job-36598630-dd2e-4b88-b445-14a9bb20a2bc:~/build/Gizra/bar-program/drupal$ ssh-add -l
4096 SHA256:+wrLdBvRJX0Ak /home/travis/.ssh/id_rsa (RSA)
travis@travis-job-36598630-dd2e-4b88-b445-14a9bb20a2bc:~/build/Gizra/bar-program/drupal$ pwd
/home/travis/build/Gizra/bar-program/drupal
travis@travis-job-36598630-dd2e-4b88-b445-14a9bb20a2bc:~/build/Gizra/bar-program/drupal$ ddev ssh
travis@bar-program-web:/var/www/html/web$ ssh-add -l
Error connecting to agent: No such file or directory
```

**To Reproduce**

Not well defined steps yet, at localhost, it works with the same DDEV projects. Also for other projects, `ddev auth ssh` works perfectly inside Travis.

**Expected behavior**

- Host computer OS and Version: Ubuntu 18.04.4 LTS inside Travis
- ddev version information (use `ddev version`)
```
DDEV-Local version      v1.15.3                                
commit                  v1.15.3                                
db                      drud/ddev-dbserver-mariadb-10.2:v1.15.1
dba                     phpmyadmin/phpmyadmin:5                
ddev-ssh-agent          drud/ddev-ssh-agent:v1.15.1            
docker                  19.03.13                               
docker-compose          1.25.0-rc4                             
os                      linux                                  
router                  drud/ddev-router:v1.15.1               
web                     drud/ddev-webserver:v1.15.3
```
- config.yaml contents for the misbehaving project
```
name: bar-program
type: drupal8
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "8081"
router_https_port: "8043"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.4"
provider: pantheon
hooks:
  post-import-db:
  - exec: drush config-set system.site name Bar
  - exec: drush cr
  - exec: drush uli
use_dns_when_possible: true
```

**Comment by rfay** [comment]
I don't see the command `ddev auth ssh` failing in your example. If I understand what you're saying a `git pull` is failing due to failed ssh authentication?

Is it possible that you have overridden the ~/.ssh/config using homeadditions? The ~/.ssh/config provided by default has 

```
rfay@junk-web:~/.ssh$ cat config
# Share known_hosts across all users of the ssh-agent
UserKnownHostsFile=/home/.ssh-agent/known_hosts
# In the container host key checking can be a problem with non-interactive composer, etc.
# Turn it off. When we upgrade to openssh 7.6 we can use the "accept-new" option instead of "no"
StrictHostKeyChecking=no
```

I guess what you need to do is add something to your travis scripts to debug this. 

1. Verify that in the web container ~/.ssh/config is as above
2. `ls -l /home/.ssh-agent/` to verify permissions. You should see files that are owned by the "travis" user in your case. In my case I see

```
$ ls -l /home/.ssh-agent/
total 4
-rw-r--r-- 1 rfay rfay 1326 Oct 21 14:02 known_hosts
srw-rw-rw- 1 rfay rfay    0 Oct 21 03:34 proxy-socket
srw------- 1 rfay rfay    0 Oct 21 03:34 socket
```

You should also see /home/.ssh-agent mounted:

```
$ df -T /home/.ssh-agent
Filesystem     Type 1K-blocks     Used Available Use% Mounted on
/dev/vda1      ext4 140105160 49901820  83056696  38% /home/.ssh-agent
```

Do make sure you're not running out of disk space; that df will show that problem though.

**Comment by AronNovak** [comment]
`ls: cannot access '/home/.ssh-agent/': No such file or directory`
`df: /home/.ssh-agent: No such file or directory`

That's the issue then, checking why the mount does not happen.

**Comment by AronNovak** [comment]
```yml
    - ddev-router:moo-program.ddev.site
    extra_hosts:
      host.docker.internal: 172.17.0.1
    healthcheck:
      interval: 1s
      retries: 20
      start_period: 20s
      timeout: 2m
    hostname: moo-program-web
    image: drud/ddev-webserver:v1.15.3-moo-program-built
    labels:
      com.ddev.app-type: drupal8
      com.ddev.approot: /home/travis/build/Gizra/moo-program/drupal
      com.ddev.platform: ddev
      com.ddev.site-name: moo-program
    links:
    - db
    - solr:moo-program.ddev.site
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
    restart: "no"
    user: 2000:2000
    volumes:
    - /home/travis/build/Gizra/moo-program/drupal/.ddev/apache:/etc/apache2/sites-enabled:ro
    - /home/travis/build/Gizra/moo-program/drupal/.ddev/nginx_full:/etc/nginx/sites-enabled:ro
    - ddev-global-cache:/mnt/ddev-global-cache:rw
    - /home/travis/build/Gizra/moo-program/drupal/.ddev:/mnt/ddev_config:ro
    - consistency: cached
      source: /home/travis/build/Gizra/moo-program/drupal
      target: /var/www/html
      type: bind
version: '3.6'
volumes:
  ddev-global-cache:
    name: ddev-global-cache
  mariadb-database:
    name: moo-program-mariadb
  solrdata: {}
```

A snippet from `.ddev/.ddev-docker-compose-full.yaml`, not surprisingly the volume is not listed here.
