### ISSUE TITLE
Windows: docroot mount doesn't work with explicit docroot

### ISSUE THREAD

**Issue by rfay** [drud/ddev#263]
## What happened (or feature request):

I tried to start a ddev site with our standard testing drupal8 repo (https://github.com/drud/drupal8) and did a `ddev config`. But then `ddev start` failed with

```
PS C:\Users\randy\workspace\drupal8> ddev start
Starting environment for drupal8...
You must manually add the following entry to your host file:
127.0.0.1 drupal8.ddev.local
ERROR: yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Users\randy\workspace\drupal8\.ddev\docker-compose.yaml", line 26, column 9
found unknown escape character 'd'
  in "C:\Users\randy\workspace\drupal8\.ddev\docker-compose.yaml", line 26, column 13
```

Line 26 is the docroot mount. It appears that the mount format .\docroot/ doesnt work right - it's escaping the 'd' as \d - mostly it doesn't seem like docker-compose should do that, but here we are!

```
 web:
   container_name: local-${DDEV_SITENAME}-web
   image: $DDEV_WEBIMAGE
   volumes:
     - "..\docroot/:/var/www/html/docroot"
```

Note that manually changing the mount to 
```
  - "../docroot/:/var/www/html/docroot"
```
made this work fine.

## What you expected to happen:

ddev config should create a file that ddev start can start

## Related source links or issues:
