### ISSUE TITLE
ddev v1.16.0: additional services like solr exposed with HTTP_EXPOSE cannot be accessed

### ISSUE THREAD

**Issue by rfay** [drud/ddev#2639]
**Describe the bug**

There's a regression in ddev v1.16.0 concerning additional services like solr or elasticsearch.

If you `ddev start` and then `ddev describe` and then try to access the *from-host* http URLs provided, you get "connection refused"

**To Reproduce**

* Add elasticsearch to a project by putting [docker-compose.elasticsearch.yaml](https://raw.githubusercontent.com/drud/ddev-contrib/master/docker-compose-services/elasticsearch/docker-compose.elasticsearch.yaml) in the .ddev folder
* `ddev start`
* `ddev describe` will show a URL like http://d8solr.ddev.site:9200, but that URL is not accessible (and even telnet cannot connect to port 9200)

**Expected behavior**

Should be able to use those URLs!

**Comment by rfay** [comment]
Until a fix is available, this can be worked around with a ~/.ddev/router-compose.fixports.yaml like this:
```
version: '3.6'
services:
  ddev-router:
    ports:
    - "127.0.0.1:9200:9200"
    - "127.0.0.1:9201:9201"
    - "127.0.0.1:8983:8983"
```

That one fixes the 9200/9201 ports (elasticsearch) and 8983 port (solr). But other services that may be exposed by HTTP_EXPOSE or HTTPS_EXPOSE just need their ports exposed. 

This should be fixed soon in a point release.
