### ISSUE TITLE
pre-import-files hooks not being executed before import-files

### ISSUE THREAD

**Issue by adsanz** [drud/ddev#2741]
**Describe the bug**

I had set a couple of pre-import-files hooks to download files via ftp, but it looks like they are not being executed. 

**To Reproduce**

My hook:

```
  pre-import-files:
    - exec-host: if [ -d .ddev/mrmilu-files ]; then echo "not creating dir"; else mkdir .ddev/mrmilu-db; fi
    - exec-host: curl --ftp-ssl -k -L -o .ddev/mrmilu-files/develop-files.tgz --user xxx:xxxxxxx  ftp://my-ftp/develop/drupal/develop.tgz

```

Execution:

```
 asanz@asanz~: ddev import-files --src=.ddev/mrmilu-files/develop-import.tar.gz --extract-path=src/web/sites/default/files
Failed to import files for drupal: invalid asset: file not found

```

**Expected behavior**

It should execute those pre-hooks and then try to import.

**Version and configuration information (please complete the following information):**

- Host: Ubuntu 20.04
- Docker version: 19.03.8
- Docker compose version 1.25.0
- ddev version:
```
DDEV-Local version      v1.16.5                                
db                      drud/ddev-dbserver-mariadb-10.2:v1.16.0
dba                     phpmyadmin:5                           
ddev-ssh-agent          drud/ddev-ssh-agent:v1.16.0            
docker                  19.03.8                                
docker-compose          1.25.0-rc4                             
os                      linux                                  
router                  drud/ddev-router:v1.16.2               
web                     drud/ddev-webserver:v1.16.3   
```
- config.yaml 
```
name: mrmilu-drupal
type: php
docroot: src
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- mrmilu-drupal.dev.mrmilu.com
mariadb_version: "10.5"
mysql_version: ""
provider: default
project_tld: dev.mrmilu.com
use_dns_when_possible: true
composer_version: ""

hooks:
  pre-import-db:
    - exec-host: if [ -d .ddev/mrmilu-db ]; then echo "not creating dir"; else mkdir .ddev/mrmilu-db; fi
    - exec-host: curl --ftp-ssl -k -L -o .ddev/mrmilu-db/develop-import.sql.gz --user xxx:xxxx  ftp://xxxxx/develop/mrmilu-drupal/develop.sql.gz
  post-import-db:
    - exec: cd src; drush cr
      service: web
  pre-import-files:
    - exec-host: if [ -d .ddev/mrmilu-files ]; then echo "not creating dir"; else mkdir .ddev/mrmilu-db; fi
    - exec-host: curl --ftp-ssl -k -L -o .ddev/mrmilu-files/develop-files.tgz --user xx:xxxxx  ftp://xxxxxx/develop/mrmilu-drupal/develop.tgz

webimage_extra_packages: ["lftp", "curl"]
```

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

No aditional config on images, they are the default ones.

**Comment by rfay** [comment]
Let's try starting from a simpler example, because it seems to work fine for me.

Please try this:

```yaml
hooks:
  pre-import-files:
  - exec-host: echo "pre-import-files is being run"
```

Here's what I see:

```
$ ddev import-files --src=.tarballs/d9_files.tgz
Executing pre-import-files hook...
=== Running task: Exec command 'echo "pre-import-files is being run"' on the host (rfay-mbp-2017.local), output below
pre-import-files is being run
Successfully imported files for d9
```
