### ISSUE TITLE
Services are accessible by other projects

### ISSUE THREAD

**Issue by tgaertner** [drud/ddev#2744]
**Describe the bug**
If one adds a Service to ddev like for example solr like described here: https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/typo3-solr, the service is also available in other ddev projects and probably misused by accident.

**To Reproduce**
- Setup solr service like described in the link above. 
- create or switch to an other (simular) project and use that solr core
- even if the second project has its own service (setup the same way) its hard to guess which service container is taken.

**Expected behavior**
A service container should by default somehow only be accessible by the same container stack.

**Hint**
Its of cause possible to use different ports for each solr service in each project, but thats not very practical because:
- one has to know each already used ports
- its easy to accidently take a port already used from something else on the host

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Linux
- ddev version information v1.16.5

**Comment by tgaertner** [comment]
One other hint that came to my mind:
I don't know how its done with the db-containers - but they are all configured the same way in each project and its not possible to accidently access the false container even multiple projects running...

**Comment by rfay** [comment]
Maybe you can say "is also accessible" means. If you mean it can be accessed by container name, that's true. But I'm not sure of another way.

**Comment by tgaertner** [comment]
My szenario is a TYPO3 Project with a configured solr extension. Configuration looks like
```
solr_host_read: 'solr'
solr_path_read: /solr/
solr_port_read: '8983'
solr_scheme_read: http
```
This works even if the current project does not have a solr server but an other project is up that have it.

**Comment by rfay** [comment]
So the host named "solr" is specifically available only to the web container that it's configured with. 

In another running project that doesn't have solr, can you `ping solr` ?

**Comment by gilbertsoft** [comment]
AFAIS the main issue here is the accidental access if you run multiple project at once. So my idea is to provide a feature which dynamically sets these ports on `ddev start` similar to the issue with the http ports which are already used. Instead of setting an explicit port DDEV should choose a free one on start e.g. by setting `auto` instead of a real valid port number.

@tgaertner would this solve your issue or is this port also used in a configuration in TYPO3? If yes, this could be solved by exposing the final port as environment variable.

**Comment by rfay** [comment]
Unless there's confusion about the hostname, the port doesn't matter. And I think @gilbertsoft you're talking about ports exposed on the *host*, which really shouldn't be done anyway. 

The example at hand here uses
```
    ports:
      - 8983
```

But it should really use `expose` instead, because no ephemeral port is required. Maybe that's the whole thing you're talking about. This recipe should just use `expose`.

**Comment by tgaertner** [comment]
@rfay well I setup the solr extension in a project and can access the solr core even the current project does not have a solr service.
This is the docker-compose:
```
version: '3.6'

services:
  solr:
    container_name: ddev-${DDEV_SITENAME}-solr
    image: typo3solr/ext-solr:10.0.1
    restart: "no"
    ports:
      - 8983
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8983
    volumes:
      - "./solr:/opt/solr/server/solr"
      # If you want your solr to persist over `ddev stop` and `ddev start` then uncomment the following line
      # If you uncomment it and want to flush your data you have to `ddev stop` and then
      # `docker volume rm ddev-<projectname>_solrdata` to destroy it.
  #      - solr:/var/solr
  web:
    links:
      - solr:$DDEV_HOSTNAME

volumes:
  # solr is a persistent Docker volume for this project's solr data
  # the volume will be named ddev-<project>_solr
  solr:
```

**Comment by rfay** [comment]
Again, please define what you mean by "can access the solr core".

**Comment by tgaertner** [comment]
Well I have no idea how to descibe it - not too familiar with docker insides... 
In the TYPO3 Backend I see the solr core and can fill it with index content. The Address for the core written there is `http://solr:8983/solr/core_en/`

**Comment by rfay** [comment]
Thank you.

I'll take a look. This isn't a ddev issue but an issue with the contributed recipe I think, but I'll take a look. 

Could you please say what OS you're using and what version of Docker Desktop (if on macOS or Windows)? Are you on WSL2?

**Comment by tgaertner** [comment]
Host OS is LinuxMint 20.1 - its based on Ubuntu
Docker version 20.10.2

**Comment by rfay** [comment]
What docker-compose version? `docker-compose --version` ?

**Comment by tgaertner** [comment]
docker-compose version 1.26.2

**Comment by gilbertsoft** [comment]
> 
> 
> Unless there's confusion about the hostname, the port doesn't matter. And I think @gilbertsoft you're talking about ports exposed on the _host_, which really shouldn't be done anyway.
> 
> The example at hand here uses
> 
> ```
>     ports:
>       - 8983
> ```
> 
> But it should really use `expose` instead, because no ephemeral port is required. Maybe that's the whole thing you're talking about. This recipe should just use `expose`.

Ah yeah, this sounds cool. I was not ware of that option. But this will only change the behavior the port isn't accessible from the host right? All containers can still access this port afterwards?

**Comment by rfay** [comment]
Only if they know the container's name or IP address, which they shouldn't.

**Comment by gilbertsoft** [comment]
That's great then, I guess this is exactly the solution @tgaertner is looking for!

**Comment by rfay** [comment]
No, the difference between `ports` and `expose` is only what happens on the host side, which is not related to what (I think) he's saying, which is that the web container on a separate project can "see" the solr container from a different project.

**Comment by tgaertner** [comment]
Right. I'm not talking about the host system. Web container from one project can "see" service container solr from other other project.

In general $DDEV_SITENAME and $DDEV_HOSTNAME vars should separate container stacks from each other. Lookl like this could only happen if the linking would be
```
 web:
    links:
      - solr:solr
```
in both projects (or something simular...)

**Comment by gilbertsoft** [comment]
Ah then I understood it wrong.

You can always check the final configuration in the `.ddev/.ddev-docker-compose-full.yaml` btw.

**Comment by tgaertner** [comment]
Thats the part for solr from the .ddev/.ddev-docker-compose-full.yaml if it helps... 

I cut off the pathes and replaced them with [...]
Project name is "typo3-draft"
```
solr:
    container_name: ddev-typo3-draft-solr
    environment:
      HTTP_EXPOSE: '8983'
      VIRTUAL_HOST: typo3-draft.ddev.site,typo3-draft.local
    image: typo3solr/ext-solr:10.0.1
    labels:
      com.ddev.approot: [...]/typo3-draft
      com.ddev.site-name: typo3-draft
    ports:
    - target: 8983
    restart: "no"
    volumes:
    - [...]/typo3-draft/.ddev/solr:/opt/solr/server/solr:rw
```

Let me know if you need anything else.
