### ISSUE TITLE
Using Browser-Sync via a Gulp Task with DDEV-local

### ISSUE THREAD

**Issue by TXChetG** [drud/ddev#2776]
**Describe the bug**
After creating a docker-compose.browsersync.yml file and configuring ports and environment variables, and then running my Browser Sync task from inside the container anytime I attempt to access the opened port I get the following message:

```
502: Unresponsive/broken ddev back-end site.

This is the ddev-router container: The back-end webserver at the URL you specified is not responding. You may want to use "ddev restart" to restart the site.
```

**To Reproduce**
1. Set-up a Drupal 8 DDEV project.
2. Add a docker-composer.browsersync.yml to open ports as needed.
3. Have theme set-up to use gulp, with browsersync task correctly written.
4. Run gulp task and attempt to access the URL.

**Expected behavior**
I would expect the site to load normally and connected to the browser-sync proxy.

**Version and configuration information (please complete the following information):**
ddev version = v1.17.0-alpha3 (both ddev and docker installed fresh today)

**docker-composer.browsersync.yml**
```
# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE
# This is to expose the browsersync port.
version: '3.6'
services:
  web:
    # ports are a list of exposed *container* ports
    ports:
      - '3000'
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3001:3000
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,3000:3000
```

**Browser-Sync task from Gulp**
```
const startServer = function (done) {
	// Initialize BrowserSync
	browserSync.init({
		proxy: https://project.ddev.site,
		host: project.ddev.site,
		stream: true,
		https: true,
		injectChanges: true,
		startPath: '',
		notify: true,
		open: false,
		reloadOnRestart: true,
		port: 3000,
	});

	done();
};
```

**Additional context**
I've spent a few hours now tracking down everything I can find on this particular issue, and testing out different settings and scenarios. I'm officially at brick wall status. Any advice at all will be greatly appreciated.

**Original work on this and related issues**
Edit: Original work on this:
* @mariohernandez article https://mariohernandez.io/blog/building-an-automated-ddev-based-drupal-environment
*  @mariohernandez original post on SO, https://stackoverflow.com/questions/62648434/using-docker-compose-to-expose-ddev-web-container-ports-to-host-machine/62648435#62648435
* webpack, https://stackoverflow.com/questions/64390344/accessing-webpack-dev-server-output-with-specific-port-in-ddev-docker-containe/64390755#64390755
