### ISSUE TITLE
docker-compose generation for "ports:" is invalid and breaks phpStorms CLI interpreter docker integration

### ISSUE THREAD

**Issue by marcusx** [drud/ddev#2801]
**Describe the bug**
The "ports" key in e.g.: `.ddev-docker-compose-full.yaml` is invalid and not quoted as stated in the docker compose docs. See: https://github.com/compose-spec/compose-spec/blob/master/spec.md#ports

In the docker-compose files generated by ddev ports is formatted as follows:

```yaml
    - db:db
    ports:
    - 127.0.0.1::80/tcp
    - 127.0.0.1::443/tcp
    restart: "no"
```
should be:
```yaml
    - db:db
    ports:
    - "127.0.0.1:80:80/tcp"
    - "127.0.0.1:443:443/tcp"
    restart: "no"
```

for some reason the first port number is ommited. The quotest are cosmetics only, but should be there as stated in the documentation linked above.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Catalina
- Docker Desktop version: 3.0.4
- ddev version information: ddev version v1.16.6
- config.yaml contents for the misbehaving project:

```yaml
name: ccis-cms
type: drupal8
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: ""
```

**Additional context**
The problem has no effect on daily ddev usage. Everything seems to work fine with any issues. But the missing port number (between the double :: breaks the docker-composer parser of IntelliJ / PhpStorm and spits out an Java error when trying to setup an external CLI interpreter.

![phpStorm_error_ddev_bad_compose_yaml](https://user-images.githubusercontent.com/960008/107788976-4dcd2280-6d51-11eb-9f2c-bb69e381ccab.png)
