### ISSUE TITLE
Mailhog returns server error 500 when try to release message

### ISSUE THREAD

**Issue by X-Tender** [drud/ddev#2821]
**Describe the bug**
The feature "Release message" returns a 500 http error when tried to use.

**To Reproduce**

1. Run server
2. send mail that gets catched by mailhog
3. `ddev launch -m `
4. try to release message with smtp data

**Expected behavior**
Mail gets submitted

**Screenshots**
<img width="925" alt="Bildschirmfoto 2021-02-18 um 11 56 43" src="https://user-images.githubusercontent.com/1413979/108347125-771e0080-71e0-11eb-8a12-f0ccfe662818.png">

**Version and configuration information (please complete the following information):**

- macOS Catalina
- Docker Desktop 3.1.0
- ddev version v1.16.5     
- config.yaml contents for the misbehaving project
- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?

config.yaml
```yaml
name: website
type: typo3
docroot: public
php_version: "7.3"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
  - website1.dev
  - website2.dev
  - website3.dev
  - website4.dev
provider: default
use_dns_when_possible: true
mysql_version: 8.0
timezone: "Europe/Berlin"
omit_containers: ["dba"]

hooks:
  post-start:
    - exec: bash -c "sudo mkdir -p /var/www/html/public/typo3"
    - exec: bash -c "sudo chown -R ${DDEV_UID}:${DDEV_GID} /var/www/html/public/typo3"
    - exec: bash -c "sudo mkdir -p /var/www/html/vendor"
    - exec: bash -c "sudo chown -R ${DDEV_UID}:${DDEV_GID} /var/www/html/vendor"
    - exec: bash -c "sudo mkdir -p /var/www/html/var"
    - exec: bash -c "sudo chown -R ${DDEV_UID}:${DDEV_GID} /var/www/html/var"
    - exec: composer install
    - exec: chmod +x /var/www/html/import-if-empty.sh
    - exec: /var/www/html/import-if-empty.sh
```

override yaml
```yaml
# Move typo3temp into RAM-Disk. Do not sync vendor and TYPO3-Directory.
# For MAC: 'nocopy' will only work correct, if nfs_mount_enabled is true
version: '3.6'
services:
  web:
    volumes:
      - type: tmpfs
        tmpfs:
          size: 268435456
        target: /var/www/html/var
      - type: volume
        source: typo3_source_typo3x
        target: /var/www/html/public/typo3
        volume:
          nocopy: true
      - type: volume
        source: vendor_typo3x
        target: /var/www/html/vendor
        volume:
          nocopy: true
    environment:
      DDEV_UID:
      DDEV_GID:
volumes:
  typo3_source_typo3x:
    driver: local
  vendor_typo3x:
    driver: local

# Add these lines (un-commented) to config.yaml to change restriction from root to current user
```
