### ISSUE TITLE
Magento 2 problem with static generation in developer mode

### ISSUE THREAD

**Issue by kamilmaliszewski** [drud/ddev#2822]
**Describe the bug**
Hi. I have strange problem when I use with Magento2 with ddev. Magento in developer mode generate some classes in real time at request. Additionally it generates static .js files if they do not exist yet. I get error like
```
ReflectionException: Class Magento\Store\Model\StoreFactory does not exist in /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php:34
Stack trace:
#0 /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php(34): ReflectionParameter->getClass()
```
or
```
<br />
<b>Fatal error</b>:  Uncaught ReflectionException: Class Magento\Framework\App\ResourceConnection\Proxy does not exist in /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php:24
Stack trace:
#0 /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php(24): ReflectionClass-&gt;__construct('Magento\\Framewo...')
#1 /var/www/html/ven
```
What important. Those are not always the same classes. Those are random classes which are not generated yet. This errors is visible in network tab at `.js` files. Instead correctly loaded generated .js file I have error like e.g `jquery.fileupload-video.js:1 Uncaught SyntaxError: Unexpected token '<'` and inside there is error that class do not exist. 

What important. `.js` files are also random. 

What the most important. After few (lets say 5-10) refresh of page everything works correctly. At every request some classes/files are generated correctly and it seems that any limit is reached and then I get error. When all statics/classes are generated then no errors and everything works correctly until next generation is required.

In other project (not magento 2) ddev works correctly. But other project are smaller than magento2. It seems that there is problem with too many requests? 

In ddev logs I found error. Maybe it is reason? 

```
[18-Feb-2021 14:29:06] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 0 idle, and 9 total children
httpd not running, trying to start
httpd not running, trying to start
httpd not running, trying to start
httpd not running, trying to start
httpd not running, trying to start
httpd not running, trying to start
httpd not running, trying to start

```

**To Reproduce**

1. Use developer mode in Magento
2. Remove all static files e.g with command magento setup:upgrade
3. Enter to Magento instance
4. Open page properties in browser
4. Check network tab and errors in .js files

**Expected behavior**
Generate static without errors 

**Version and configuration information (please complete the following information):**

- macOS Big Sur 2018 i5 16gb 
- docker 3.01
- ddev 1.16.1
- magento 2.4
- config.yaml 
```
name:  magento2
type: magento2
docroot: pub
php_version: "7.4"
mysql_version: 8.0
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
provider: default
use_dns_when_possible: true
composer_version: ""
project_tld: my.site
timezone: Europe/Berlin
disable_settings_management: true
hooks:
  post-start:
    - exec: if [ ! -e vendor ]; then composer install ; fi
    - exec: sudo find /var/www/html/var/cache -type d -exec chmod 0777 {} \;
    - exec: bash -c "perl -pi -e 's/pm.max_children = 8/pm.max_children = 32/' /etc/php/*/fpm/pool.d/www.conf && killall -1 php-fpm"
```
