### ISSUE TITLE
Drupal 7: drushrc.php comment coding standards

### ISSUE THREAD

**Issue by mbomb007** [drud/ddev#2849]
**Describe the bug**

The drushrc.php file created for Drupal 7 projects doesn't follow coding standards. Example:

```php
<?php
/** #ddev-generated: Automatically generated drushrc.php file (for Drush 8)
 ddev manages this file and may delete or overwrite the file unless this comment is removed.
 Remove this comment if you don't want ddev to manage this file.'
 */
if (getenv('IS_DDEV_PROJECT') == 'true') {
  $options['l'] = "https://project.ddev.site";
}
```

There is no blank line before the file comment, there's no `@file`, the middle lines of the comment are missing `*`, and there's an apostrophe at the end of the comment for some reason.

**To Reproduce**

1. Configure and start a drupal7 DDEV project.
2. A drushrc.php file like above is created in sites/default/

**Expected behavior**

It should be similar to the settings.ddev.php file (truncated example):

```php
<?php

/**
 * @file
 * #ddev-generated: Automatically generated Drupal settings file.
 * ddev manages this file and may delete or overwrite the file unless this
 * comment is removed.
 */

$host = "db";
$port = 3306;
...
```

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: **Windows 10 (2004)**
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop"): **3.2.0**
- ddev version information (use `ddev version`): **v1.17.0-alpha6**

- config.yaml contents

```yaml
name: project
type: drupal7
docroot: ""
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns:
- project.example.com
mariadb_version: "10.5"
mysql_version: ""
omit_containers: [dba]
use_dns_when_possible: true
composer_version: "2"
```
