### ISSUE TITLE
Broken pipe error (as reported in logs) when trying to generate image styles in a Drupal 8 project

### ISSUE THREAD

**Issue by cscomfort** [drud/ddev#2928]
https://gist.github.com/cscomfort/c9d077eba473a28056134dd32498bf26

**Describe the bug**
I'm not sure if this a Drupal 8 (v8.9.12) issue or DDEV, but when flushing thumbnails in my project `drush if --all` and then visiting a page that should regenerate said thumbnails, the process fails. The associated image links fail as 404s (their paths are rooted at `/var/www/html/web/sites/default/files/styles` as seen in the container). Watching the logs, I see the following when visiting the pages that should regenerate the thumbnails (seen here is a 'test' image style):

`2021/04/05 18:40:54 [info] 1670#1670: *823 writev() failed (32: Broken pipe) while sending to client, client: 172.18.0.6, server: _, request: "GET /sites/default/files/styles/test/public/images/2021-01/woman-scientist-with-fruit-in-lab.jpg HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "local.utni.org", referrer: "http://local.utni.org/admin/content/media"`

Note that I don't encounter any issue retrieving images on the public side of the site.

**To Reproduce**
I deleted (`ddev delete`) and then started the project anew, to no avail.

**Expected behavior**
Images styles should be generated.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Big Sur
- Docker Desktop version: 3.10
- ddev version information: v1.16.7
- config.yaml contents for the misbehaving project:
```yaml
name: utni-v3
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: [
    'local.utni.org'
]
provider: default
use_dns_when_possible: true
```
I disabled the one custom yaml config which simply provided a 'local' environment variable. The issue continues to persist.

Thanks in advance!
