### ISSUE TITLE
web container could not be started on MacOS Big Sur with activated virtualization.framework in Docker Desktop because of NFS

### ISSUE THREAD

**Issue by froemken** [drud/ddev#2964]
**Describe the bug**

web container could not be started on MacOS Big Sur with activated virtualization.framework in Docker Desktop because of NFS

```
Building web
Creating ddev-5160001-drs-baukasten-db ... 
Creating ddev-5160001-drs-baukasten-db ... done
Creating ddev-5160001-drs-baukasten-web ... 
Creating ddev-5160001-drs-baukasten-dba ... 
Creating ddev-5160001-drs-baukasten-web ... error

ERROR: for ddev-5160001-drs-baukasten-web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-5160001-drs-baukasten_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/froemken/htdocs/kunden/drs-baukasten:/var/lib/docker/volumes/ddev-5160001-drs-baukasten_nfsmount/_data, data: addr=192.168.64.1,hard,nolock: permission denied
Creating ddev-5160001-drs-baukasten-dba ... done

ERROR: for web  Cannot start service web: error while mounting volume '/var/lib/docker/volumes/ddev-5160001-drs-baukasten_nfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/froemken/htdocs/kunden/drs-baukasten:/var/lib/docker/volumes/ddev-5160001-drs-baukasten_nfsmount/_data, data: addr=192.168.64.1,hard,nolock: permission denied
Encountered errors while bringing up the project.'
```

My problem is very similar to this issue: https://github.com/drud/ddev/issues/2954

```
➜  drs-baukasten git:(master) ddev debug nfsmount
NFS does not seem to be set up yet, see debugging instructions at https://ddev.readthedocs.io/en/stable/users/performance/#debugging-ddev-start-failures-with-nfs_mount_enabled-true
Details: error=failed to StartContainer: API error (500): error while mounting volume '/var/lib/docker/volumes/testnfsmount/_data': failed to mount local volume: mount :/System/Volumes/Data/Users/froemken/htdocs/kunden/drs-baukasten:/var/lib/docker/volumes/testnfsmount/_data, data: addr=192.168.64.1,hard,nolock: permission denied
output=
```

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: macOS Big Sur
- Docker Desktop version if on macOS: 3.2.2 (61853)
- ddev version information: v1.17.1
- config.yaml contents for the misbehaving project (the part before the comments)

```
type: typo3
docroot: public
php_version: "7.2"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
mysql_version: ""
nfs_mount_enabled: true
hooks:
  post-import-db:
  - exec: /var/www/html/vendor/bin/typo3cms database:updateschema "*.add,*.change"
  - exec: bash -c 'echo "UPDATE sys_domain SET hidden = 1; UPDATE sys_domain SET hidden
      = 0 WHERE domainName REGEXP \".*\.ddev\.site\"" | /var/www/html/vendor/bin/typo3cms
      database:import'
  - exec: /var/www/html/vendor/bin/typo3cms cache:flush
  post-start:
  - exec: bash -c "sudo mkdir -p /var/www/html/var/Cache/Code"
  - exec: bash -c "sudo mkdir -p /var/www/html/var/Cache/Data"
  - exec: bash -c "sudo mkdir -p /var/www/html/public/typo3"
  - exec: bash -c "sudo mkdir -p /var/www/html/vendor"
use_dns_when_possible: true
timezone: Europe/Berlin
composer_version: "2"
web_environment: []
```

We exclude some directories for performance reasons from mount like described here: https://gist.github.com/froemken/bfaf227ca24af09c4d378e4f4285ccc1

Maybe it has something to do with that problem: https://www.gitmemory.com/issue/docksal/docksal/1477/803247870

Currently deactivating NFS or deactivating experimental Feature Virtualization.Framework in Docker Desktop solves this issue.

Stefan
