### ISSUE TITLE
Docker container: XDebug enabled even though explicitly disabled

### ISSUE THREAD

**Issue by simonschaufi** [drud/ddev#2978]
**Describe the Problem**

XDebug tries to connect to a server even though it is disabled through an environment variable

**To Reproduce**

My `.gitlab-ci.yml` config:

```yml
.only-default: &only-default
  only:
    - master
    - develop
    - merge_requests

build-dev:
  <<: *only-default
  variables:
    DDEV_XDEBUG_ENABLED: "false"
  stage: build
  image: drud/ddev-webserver:v1.17.2
  before_script:
    - echo "${DDEV_XDEBUG_ENABLED}"
    - composer --version
  script:
    - composer install --no-progress --no-ansi --no-interaction
  artifacts:
    name: build
    paths:
      - ./public/
      - ./vendor/
      - ./.cache/
      - ./composer.json
      - ./composer.lock
    expire_in: '1h'
  tags:
    - docker
```

results in the following output on gitlab.com:

```
Running with gitlab-runner 13.11.0 (7f7a4bb0)
  on verdi zRkhyC6s
Preparing the "docker" executor
00:02
Using Docker executor with image drud/ddev-webserver:v1.17.2 ...
Pulling docker image drud/ddev-webserver:v1.17.2 ...
Using docker image sha256:c06746f5cd03eabf5eb2655b69d6487c71041f5f642b6e594db46a2fa799bfdb for drud/ddev-webserver:v1.17.2 with digest drud/ddev-webserver@sha256:48af9655e35aab11415dd422d305f61c347ead2a755fc5c2c2441d5b39fba164 ...
Preparing environment
00:00
Running on runner-zrkhyc6s-project-23514596-concurrent-0 via verdi...
Getting source from Git repository
Fetching changes with git depth set to 50...
Reinitialized existing Git repository in /builds/xxx/xxx/.git/
Checking out de313363 as refs/merge-requests/640/head...
Removing .phplint-cache
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:27
Using docker image sha256:c06746f5cd03eabf5eb2655b69d6487c71041f5f642b6e594db46a2fa799bfdb for drud/ddev-webserver:v1.17.2 with digest drud/ddev-webserver@sha256:48af9655e35aab11415dd422d305f61c347ead2a755fc5c2c2441d5b39fba164 ...
$ echo "${DDEV_XDEBUG_ENABLED}"
false
$ composer --version
Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9000 (through xdebug.client_host/xdebug.client_port) :-(
Composer version 2.0.13 2021-04-27 13:11:08
```

As you can see, xdebug tries to make a connection so it is enabled!

Any idea how to fix it?
