### ISSUE TITLE
In WSL2, the dollar sign '$' in the path broke .ddev-docker-compose-base.yaml

### ISSUE THREAD

**Issue by liang-wap** [drud/ddev#2992]
Because 'wsl$' in the yaml file has not been escaped, Error "Invalid interpolation format" was reported in WSL2 after run 'ddev start'. 

```
  db:
    container_name: ddev-${DDEV_SITENAME}-db
    build:
      context: '\\wsl$\Ubuntu-20.04\home'
      dockerfile: '\\wsl$\Ubuntu-20.04\home'
```

```
  web:
    container_name: ddev-${DDEV_SITENAME}-web
    build:
      context: '\\wsl$\Ubuntu-20.04\home'
      dockerfile: '\\wsl$\Ubuntu-20.04\home'
```
