### ISSUE TITLE
Allow overriding PHP_IDE_CONFIG

### ISSUE THREAD

**Issue by dnaber-de** [drud/ddev#2998]
**Is your feature request related to a problem? Please describe.**
I would like to change the value of `PHP_IDE_CONFIG` environment variable in the web container. The reason is that I'd like to unify the server name for XDebug requests coming from HTTP and the CLI. 

My projects typically have a name like `acme-corp-website` and I use `acme-corp.localhost` as local domain name. So when I start a Xdebug session from the browser PHPStorm recognizes a connection from the «server» `acme-corp.localhost`. Now that DDEV sets the value of this environment variable to `serverName=acme-corp.ddev.site` any Xdebug connection stared by CLI would result in PHPStorm assuming a different server. So I have to maintain two servers in PHPStorm for the same project.

**Describe the solution you'd like**
The obvious way to solve this is something like this:

```yaml
# .ddev/docker-compose.override.yaml

version: '3.6'

services:
    web:
        environment: 
            PHP_IDE_CONFIG: serverName=acme-corp.localhost
```

I tired this with version 1.17.2 of DDEV but it seems that this very variable is somehow locked for overriding:
```
$ env | grep PHP_IDE
PHP_IDE_CONFIG=serverName=acme-corp.ddev.site
```

**Describe alternatives you've considered**
I could try to set  this variable via a custom Dockerfile or via a post-start hook in `.ddev/config.yaml` or even inside `.ddev/homeadditions/.bashrc` but all of these are not really convenient.
