### ISSUE TITLE
Does ddev-local require a local dockerd instance?

### ISSUE THREAD

**Issue by syssi** [drud/ddev#3052]
**Describe the Problem**

I'm trying to execute ddev-local at Gitlab CI. If I use docker:19-dind as service (providing a dockerd instance) and docker:19 as ddev-local host (plus docker-compose) a `ddev start` call fails here:

```
$ ddev start
[...]
usually on start, use 'ddev restart' if you're not seeing it take effect.
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Running  Command=ip address show dev docker0
The Compose file '/builds/groupname/project/.ddev/.ddev-docker-compose-base.yaml' is invalid because:
services.db.ports contains an invalid type, it should be a number, or an object
services.web.ports contains an invalid type, it should be a number, or an object
services.web.ports contains an invalid type, it should be a number, or an object
```

The generated `.ddev/.ddev-docker-compose-base.yaml` looks like this:

```
    user: "$DDEV_UID:$DDEV_GID"
    hostname: project-db
    ports:
      - "docker:$DDEV_HOST_DB_PORT:3306"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
[...]
    environment:
      - [...]
      - DOCKER_IP=docker
```

I assume the important / problematic part is the "docker" hostname of the remote dockerd instead of the IP address (127.0.0.1) which is normally used.

**To Reproduce**

```
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DDEV_DEBUG: 1

services:
  - docker:19.03-dind

stages:
  - tests

codeception:
  <<: *only-default
  image: registry.gitlab.com/groupname/containers/ddev:latest
  stage: tests
  before_script:
    - sudo brctl addbr docker0
    - sudo ip addr add 192.168.5.1/24 dev docker0
    - sudo ip link set dev docker0 up
    - docker ps
    - docker info
  script:
    - ddev start
    - ddev describe
    - ddev stop
  after_script:
    - cat /builds/groupname/project/.ddev/.ddev-docker-compose-base.yaml
  tags:
    - dind
```

Does ddev-local require a local dockerd instance? Did I miss something?

**Comment by rfay** [comment]
ddev has never been designed or used with a remote docker instance, like with $DOCKER_HOST. 

You might be interested in how Github Actions is used for testing with ddev, see https://github.com/marketplace/actions/setup-ddev

I think @husssainweb may be trying to do something like you're doing in https://github.com/drud/ddev/issues/3025

**Comment by syssi** [comment]
If I use docker:19-dind as ddev host and start dockerd manually the `DOCKER_IP` points to `127.0.0.1` and the default bridge is created. I will stick to this solution instead using a service (container).

I've inspected the GitHub action already but it looks like the docker-in-docker setup isn't required here or I missed the tricky part of the code.

**Comment by rfay** [comment]
I hope you'll write up your technique for others, in a repo, in github.com/drud/ddev-contrib, or on Stack Overflow. I know people will want it. 

No extra docker-in-docker is required on github - github actions run inside a VM that has docker working there.

**Comment by syssi** [comment]
My question is solved. Thanks for your speedy support!

**Comment by GertjanJ** [comment]
Im also having the same issue, . I copied these parts of @syssi example to my gitlab.yml:

`variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DDEV_DEBUG: 1

services:
  - docker:19.03-dind`

and

`  before_script:
    - sudo brctl addbr docker0
    - sudo ip addr add 192.168.5.1/24 dev docker0
    - sudo ip link set dev docker0 up
    - docker ps
    - docker info`


But it seems I can't get it to work because I do not understand what is happening here :)
Gitlab is giving me this error: **Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?** What am I missing here?

This is my full gitlab.yml

`image: registry.gitlab.com/group/container

services:
  - docker:19.03-dind

stages:
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DDEV_DEBUG: 1

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  - brctl addbr docker0
  - ip addr add 192.168.5.1/24 dev docker0
  - ip link set dev docker0 up
  - ip addr show docker0
  - env | grep DOCKER_HOST
  - docker ps
  - docker info
  - sh ./ci-scripts/install-ddev.sh

test:
  stage: test
  only:
    - master
  script:
    - ddev start
  environment: production`

**Comment by rfay** [comment]
I have no experience at all with gitlab and it's setup. If you have a way to ssh into a test maybe you can debug this? You don't mention what you see as the output of the before_script; As stated above, ddev has never been tested with or designed for use of an arbitrary DOCKER_HOST. It might be possible to support it, but it's never been tried.

**Comment by GertjanJ** [comment]
Thanks for your quick reply! I know ddev is not designed for this kind of environment. Locally it works perfectly.

That said, I'm not a CI/CD/docker expert, but I need a way to point the DOCKER_IP to 127.0.0.1 instead of "docker" (the service name of the container) and it seems @syssi has solved that problem? I tried copy-pasting his solution and can't get it to work. ( i cannot ssh into test as i'm using a shared runner from gitlab )

This is the output of my before_script:

```
$ echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded
$ brctl addbr docker0
$ ip addr add 192.168.5.1/24 dev docker0
$ ip link set dev docker0 up
$ ip addr show docker0
2: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN qlen 1000
    link/ether 0a:42:45:66:ac:bb brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.1/24 scope global docker0
       valid_lft forever preferred_lft forever
$ env | grep DOCKER_HOST
DOCKER_HOST=tcp://docker:2375
$ docker ps
Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by syssi** [comment]
It is tricky but it's possible and ugly too because you have to run an privileged docker-in-docker setup. I will try to provide a proof of concept: As first step I've build a debian based dind image because I'm more familiar with debian systems:

```
# dind-debian/Dockerfile

FROM debian:buster-slim

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
      apt-transport-https \
      ca-certificates \
      gnupg2 \
      curl \
      git \
      make \
      kmod \
      procps && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    echo "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" | tee /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install --no-install-recommends -y docker-ce && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

# Switch to use iptables instead of nftables (to match the CI hosts)
# TODO use some kind of runtime auto-detection instead if/when
# nftables is supported (https://github.com/moby/moby/issues/26824)
RUN update-alternatives --set iptables  /usr/sbin/iptables-legacy || true && \
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || true && \
    update-alternatives --set arptables /usr/sbin/arptables-legacy || true

# Set up subuid/subgid so that "--userns-remap=default" works
# out-of-the-box.
RUN set -x && \
    addgroup --system dockremap && \
    adduser --system --ingroup dockremap dockremap && \
    echo 'dockremap:165536:65536' >> /etc/subuid && \
    echo 'dockremap:165536:65536' >> /etc/subgid

ENV container docker
```

As second step I've assembled an `ddev` container base on the dind container:

```
# ddev/Dockerfile

FROM registry.gitlab.com/XXX/containers/dind-debian:latest

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Berlin
RUN apt-get update && \
    apt-get -y install curl sudo tzdata && \
    apt-get autoclean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -SL "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod 755 /usr/local/bin/docker-compose

COPY sudoers /etc/sudoers
RUN chmod 0440 /etc/sudoers

RUN useradd -m -p ddev-user -d /home/ddev-user -s /bin/bash -G docker,sudo ddev-user && id ddev-user

RUN curl -SL https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh -o /usr/local/bin/install_ddev.sh && \
    chmod 755  /usr/local/bin/install_ddev.sh && \
    sudo -u ddev-user bash /usr/local/bin/install_ddev.sh

RUN sudo -u ddev-user ddev config global --instrumentation-opt-in=false --omit-containers=dba,ddev-ssh-agent

RUN curl -SL https://raw.githubusercontent.com/drud/ddev/master/scripts/test_ddev.sh -o /usr/local/bin/test_ddev.sh && \
    chmod 755 /usr/local/bin/test_ddev.sh

COPY test-project /home/ddev-user/test-project

USER ddev-user

ENV HOME=/home/ddev-user/

WORKDIR /home/ddev-user/
```

```
# ddev/sudoers 

Defaults env_reset
Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
Defaults !authenticate

root    ALL=(ALL:ALL) ALL
%sudo   ALL=(ALL:ALL) ALL
```

The last step is an example project using the ddev container at the CI:

```
# .gitlab-ci.yml 
codeception:
  image: registry.gitlab.com/XXX/containers/ddev:latest
  before_script:
    - sudo dockerd -H unix:///var/run/docker.sock -H tcp://127.0.0.1:2375 &
    - sleep 10
    - docker info
  script:
    - ddev start
    - ddev describe
    - ddev stop
  tags:
    - dind
```

```
# .ddev/config.yaml
name: setup-ddev
type: php
docroot: ""
php_version: "7.4"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
provider: default
use_dns_when_possible: true
```

The ugly part of this setup: A self managed gitlab-runner with `privileged = true` enabled is required:

```
# /etc/gitlab-runner/config.toml
[[runners]]
  ...
  [runners.docker]
    privileged = true

```
