### ISSUE TITLE
Docker desktop 3.5+: "network default: network.external.name is deprecated in favor of network.name"

### ISSUE THREAD

**Issue by HeineDeelstra** [drud/ddev#3069]
Docker (Windows 10 Home/WSL2) just updated to 3.5.0 (66024). Projects on ddev 1.17.6 generate a warning "network default: network.external.name is deprecated in favor of network.name". Projects with varnish (ddev contrib) generate an error, "services.varnish.ports must be a list" and fail. Updating to Docker 3.5.1 did not solve or change the issue.

Currently unsure of the cause and working around it.

The start log:

```
14:55 $ ddev start
Starting XYZ...
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Running   Command=ip address show dev docker0
time="2021-06-25T14:55:25+02:00" level=warning msg="network default: network.external.name is deprecated in favor of network.name"
services.varnish.ports must be a list
Failed to start XYZ: Failed to run docker-compose [-f /home/heine/sites/XYZ/.ddev/.ddev-docker-compose-base.yaml -f /home/heine/sites/XYZ/.ddev/docker-compose.environment.yaml -f /home/heine/sites/XYZ/.ddev/docker-compose.redis.yaml -f /home/heine/sites/XYZ/.ddev/docker-compose.solr.yaml -f /home/heine/sites/XYZ/.ddev/docker-compose.varnish.yaml config], err='exit status 15', stdout='', stderr='time="2021-06-25T14:55:25+02:00" level=warning msg="network default: network.external.name is deprecated in favor of network.name"
services.varnish.ports must be a list'
```

Our varnish compose:

```
14:55 $ cat .ddev/docker-compose.varnish.yaml
# DDev Varnish recipe file.
#
# To use this in your own project:
# 1. Copy this file to your project's ".ddev" directory.
# 2. Create the folder path ".ddev/varnish/".
# 3. Make a file with the following content at
#    ".ddev/varnish/default.vcl".
#
# vcl 4.0;
#
# backend default {
#   .host = "web:80";
# }
#
# Notes:
# - The configuration files must be present before running "ddev start".
# - Changes to the configuration files will not be automatically applied.
#
# To access the site through Varnish after it is installed simply visit the ddev
# site as usual. To avoid going through varnish visit the the novarnish. subdomain.

version: '3.6'

services:
  # This is the service name used when running ddev commands accepting the
  # --service flag.
  varnish:
    # This is the name of the container. It is recommended to follow the same
    # name convention used in the main docker-compose.yml file.
    container_name: ddev-${DDEV_SITENAME}-varnish
    image: "varnish:6.2"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      # This defines the host name the service should be accessible from. This
      # will be sitename.ddev.site.
      # This is the first half of the trick that puts varnish "in front of" the
      # web container, just by switching the names
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      # This defines the ports the service should be accessible from at
      # sitename.ddev.site.
      - HTTPS_EXPOSE=443:80,8026:8025
      - HTTP_EXPOSE=80:80,8025:8025
      - SIZE=256M
    volumes:
      # This exposes a mount to the host system `.ddev/varnish` directory where
      # your default.vcl should be
      - ./varnish:/etc/varnish
      - ".:/mnt/ddev_config"
    ports: []
    links:
      - web:web
  # This is the second half of the trick that puts varnish "in front of" the web
  # container, just by switching the names
  web:
    environment:
      - VIRTUAL_HOST=novarnish.$DDEV_HOSTNAME
```
