### ISSUE TITLE
Project with type=php creates mutagen config for TYPO3, not syncing "var"

### ISSUE THREAD

**Issue by susannemoog** [drud/ddev#3124]
**Run a Diagnostic and Paste Link Here**

https://gist.github.com/susannemoog/7a9be8437997b81152084ad6c750b25e

**Describe the bug**

Latest alpha release, enabled mutagen support in an existing PHP (symfony) based project. Mutagen.yml has been created with the following content:

```
sync:
  defaults:
    mode: "two-way-resolved"
    ignore:
      paths:
        # /var/www/html/var does not need to sync in TYPO3
        - "var"
        - ".ddev"
      vcs: true
    symlink:
      mode: "portable"
```
While it is true that the sync is not necessary in TYPO3, in my symfony project of type "PHP" var is quite important to be synced, because I keep the sqlite database there.

**To Reproduce**
ddev config:

```
name: intercept
type: php
docroot: public
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
mysql_version: ""
nfs_mount_enabled: false
mutagen_enabled: true
hooks:
  pre-start:
  - exec-host: php -r "file_exists('.ddev/keycloak-gatekeeper.conf') || copy('.ddev/keycloak-gatekeeper.conf.tmpl',
      '.ddev/keycloak-gatekeeper.conf');"
omit_containers: [dba]
webimage_extra_packages: [php7.4-gmp, ssh]
use_dns_when_possible: true
composer_version: 2.0.0
web_environment: []
```
see also https://github.com/TYPO3GmbH/site-intercept/blob/develop/.ddev/config.yaml (old config, bug occurred after "ddev config --mutagen-enabled && ddev start")

**Expected behavior**

var is not excluded if it is not a TYPO3 project - or: make it more obvious that the user has to take care of this decision.

**Version and configuration information (please complete the following information):**

- see Gist and links above

**Additional context**

I'm not sure this is even considered to be a bug, maybe it's just expected behaviour I didn't expect ;)
