### ISSUE TITLE
Error Message : Unable to read global_config.yaml: control characters not allowed.

### ISSUE THREAD

**Issue by zedd9165** [drud/ddev#3138]
**Describe the Problem**

**I was trying to install drupal 9 as a new project and suddenly the installation failed. Due to which I had to close my powershell and re-open in with admin rights. However, upon running the DDev command Im receiving the error mentioned below.** 

PS C:\Users\User> ddev
time="2021-08-03T15:46:54+05:30" level=fatal msg="unable to read global config: yaml: control characters are not allowed

***To Reproduce*****

Create a directory (mkdir my-new-project)
Change to the new directory (cd my-new-project)
Run ddev config
Then choose Drupal 9 and then installation failed.
I thought of creating a new installation, went back to the Users/User directory and found the project and deleted it. 
Came back to Powershell and ran Ddev command and received the above mentioned error. 
Went back to recycle and restored the deleted project.
Came back to powershell and ran the came command and I hit the same error again.

**Screenshots**
![image](https://user-images.githubusercontent.com/57957114/128000160-ef7220d9-f08e-46d0-a3f6-29a9231a5ce6.png)

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: [e.g. Windows 10, macOS Big Sur, Linux (distro), WSL2 (distro)]
-Windows 10 - WSL2(UBUNTU) 
- Docker Desktop version if on macOS or Windows (from "About Docker Desktop")
- 3.5.2 (66501) 
- ddev version information (use `ddev version`)
- Latest version as its a fresh installation and Im unable to run any ddev commands to check the extact version. 
- config.yaml contents for the misbehaving project

 ```yaml
name: BTev
type: drupal9
docroot: ""
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
use_dns_when_possible: true
composer_version: ""
web_environment: []
```
