### ISSUE TITLE
Use `working_dir` in generated docker-compose instead of dynamically setting working_dir on launch

### ISSUE THREAD

**Issue by mstrelan** [drud/ddev#3158]
I've been following along with https://github.com/drud/ddev/issues/3130 and https://drupalize.me/blog/debug-any-drupals-phpunit-tests-phpstorm-ddev-local-environment but ran in to an issue when running [Drupal Test Traits](https://gitlab.com/weitzman/drupal-test-traits).

When phpstorm runs the test via `docker exec` it runs from `/` instead of `/var/www/html` and therefore DrupalFinder can't find Drupal. This is because [the working directory is dynamically added](https://github.com/drud/ddev/blob/07954280aaf2adc98613e6984f1aeeaf568d8ab1/pkg/ddevapp/ddevapp.go#L1217-L1219) to the ddev exec commands. Would it be possible to add the working_dir to the docker-compose file instead or as well?

To get around the issue for now I'm adding a custom docker compose file to set this:

.ddev/docker-compose.env.yml:

```
version: '3.6'
services:
  web:
    # This makes sure the working dir is set for running tests via phpstorm
    working_dir: /var/www/html
```
