### ISSUE TITLE
Unable to run ddev pull with mutagen enabled

### ISSUE THREAD

**Issue by deviantintegral** [drud/ddev#3189]
**Run a Diagnostic and Paste Link Here**

**Describe the bug**

When mutagen is enabled, `.ddev` is not synced into the container, which means that `ddev pull` scripts are likely to break.

**To Reproduce**

```
name: drupal8-mutagen-test
type: drupal8
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
nfs_mount_enabled: false
mutagen_enabled: true
use_dns_when_possible: true
composer_version: ""
web_environment: []
```

And then, using any one of the example providers, such as:

```
db_pull_command:
  command: |
    # set -x   # You can enable bash debugging output by uncommenting
    ls /var/www/html/.ddev >/dev/null # This just refreshes stale NFS if possible
    pushd /var/www/html/.ddev/.downloads >/dev/null
    terminus backup:get ${project} --element=db --to=db.sql.gz
```

**Expected behavior**

Switching the sync method shouldn't require changes in other configuration files.

**Version and configuration information (please complete the following information):**

- macOS 11.5.2
- Docker Desktop 3.5.2
- ddev version v1.18.0-alpha4

**Additional context**

It doesn't appear this can be resolved without changing `mutagen.yml` somehow to allow syncing of .ddev/downloads, or to store downloaded files elsewhere.

**Comment by deviantintegral** [comment]
Aside - `ddev mutagen status` is working perfectly as compared to the first alpha when I was last testing this 🙌

**Comment by deviantintegral** [comment]
I tried removing `#ddev-generated` from `mutagen.yml` and adding an ignore rule for downloads, but the file is being rewritten anyways on `ddev start` 🤔

**Comment by rfay** [comment]
I ran across this - it's due to .ddev not being copied into the container. Take over the mutagen.yml and remove the exclusion of .ddev. 

This is fixed in next prerelease.

**Comment by rfay** [comment]
Since you're an expert, would you mind checking out the latest master build, https://github.com/drud/ddev/actions/runs/1149450035 - See if
1. The problem is fixed
2. You can take over the mutagen.yml

I know I had to take over the mutagen.yml in testing, so not sure what happened with your situation.

**Comment by deviantintegral** [comment]
1. It is!
2. I thought this was possibly caused by me removing `.ddev` from the mutagen ignore list while trying to get database pulls working. However, I can replicate after running `ddev delete`:

```
cat .ddev/mutagen.yml; ./ddev start -y; cat .ddev/mutagen.yml;
# To override this file remove the #ddev-generated line above
# and add your own configuration. If you override it you will
# probably want to check it in.
# See ddev mutagen docs at
# https://ddev.readthedocs.io/en/latest/users/performance/#using-mutagen
# For detailed information about mutagen configuration options, see
# https://mutagen.io/documentation/introduction/configuration
sync:
  defaults:
    mode: "two-way-resolved"
    ignore:
      paths:
        - "/.ddev"
        - "/.vagrant"
        # The top-level .git directory is ignored to encourage git actions on the host
        # side, but if you need it inside the container you can remove this
        - "/.git"
        # For example /var/www/html/var does not need to sync in TYPO3
        # - "var"
      # vcs like .git can be ignored for safety, but then some
      # composer operations may fail if they use git.
      # vcs: true
    symlink:
      mode: "portable"

Starting dailyreport...
Pushed mkcert rootca certs to ddev-global-cache/mkcert
Creating volume "dailyreport_project_mutagen" with default driver
Building db
Building web
Creating ddev-dailyreport-db ...
Creating ddev-dailyreport-db ... done
Creating ddev-dailyreport-dba ...
Creating ddev-dailyreport-web ...
Creating ddev-dailyreport-dba ... done
Creating ddev-dailyreport-web ... done
Starting mutagen sync process... This can take some time.

Status: Reconciling changes
Status: Staging files on beta
Status: Applying changes
Status: Saving archive
Status: Watching for changes
Status: Scanning files
Status: Reconciling changes
Status: Saving archive
Status: Watching for changes
Mutagen sync flush completed in 24s.
For details on sync status 'ddev mutagen status dailyreport --verbose'
Status: Scanning files
Creating ddev-router ...
Creating ddev-router ... done
Ensuring write permissions for dailyreport
Existing settings.php file includes settings.ddev.php
Ensuring write permissions for dailyreport
Successfully started dailyreport
Project can be reached at https://dailyreport.ddev.site https://127.0.0.1:63118
# To override this file remove the #ddev-generated line above
# and add your own configuration. If you override it you will
# probably want to check it in.
# See ddev mutagen docs at
# https://ddev.readthedocs.io/en/latest/users/performance/#using-mutagen
# For detailed information about mutagen configuration options, see
# https://mutagen.io/documentation/introduction/configuration
sync:
  defaults:
    mode: "two-way-resolved"
    ignore:
      paths:
        - "/.ddev"
        - "/.vagrant"
        # The top-level .git directory is ignored to encourage git actions on the host
        # side, but if you need it inside the container you can remove this
        - "/.git"
        # For example /var/www/html/var does not need to sync in TYPO3
        # - "var"
      # vcs like .git can be ignored for safety, but then some
      # composer operations may fail if they use git.
      # vcs: true
    symlink:
      mode: "portable"
```

But if I wait another 10 seconds or so (mutagen status is showing activity), the file is reverted. I think something is creating mutagen.yml in the container (which I can see) which then gets synced back.
