### ISSUE TITLE
`ddev pull` changes public/fileadmin to a directory (project type: typo3) 

### ISSUE THREAD

**Issue by jonaseberle** [drud/ddev#3216]
**Run a Diagnostic and Paste Link Here**
https://gist.github.com/jonaseberle/01aa87572b248d093109180e997d04b1

**Describe the bug**

In my case, `public/fileadmin` and `public/uploads` are symlinks.
After running `ddev pull`, the symlink `public/fileadmin` is replaced by an empty directory.

**To Reproduce**

```sh
ddev config --docroot=public --create-docroot --project-type=typo3

mkdir -p data/files/fileadmin data/files/uploads
ln --symbolic --relative data/files/* public/

ddev start

cat > .ddev/providers/test.yaml <<EOF
files_pull_command:
  command:  
EOF

ddev pull test --skip-db -y

# the former symlink `fileadmin` is now a folder
ls -als public/
```

**Expected behavior**

The symlink stays in place

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Linux (Ubuntu)
- ddev version information: v1.18.0-rc1

**Comment by rfay** [comment]
Thanks for the report. This is an unusual situation, right? What should the correct behavior be, just follow the symlink (if it's relative and also inside the filespace?) Pretty sure this behavior is a result of the lower-level utilities we use to copy directories, and I think they ignore symlinks.

Would it be possible to share your pull yaml?

**Comment by jonaseberle** [comment]
Hi Randy, the content of the pull yaml:

The used commands are those from ddev-contrib.
These commands don't do anything with `public/fileadmin`

```
environment_variables:
  target: live

auth_command:
  command: |
    ssh-add -l >/dev/null || ( echo "Please 'ddev auth ssh' before running this command." && exit 1 )

db_pull_command:
  command: |
    # Dumps and downloads from server
    /var/www/html/.ddev/commands/web/dump-db "${target}" -y
    # ddev only supports single-file-gzipped here currently so we gzip the downloaded SQL for ddev to consume it...
    cat /var/www/html/data/sql/struct/* /var/www/html/data/sql/records/* | gzip > /var/www/html/.ddev/.downloads/db.sql.gz

files_pull_command:
  command: |
    # This rsyncs to ./data/files/fileadmin and ./data/files/uploads because the default ddev location
    # is cleared before pulling
    # in our case, ./data/files/* is symlinked to appropriate locations in a post-start hook
    /var/www/html/.ddev/commands/web/dump-files "${target}" -y
```

What do I think it should do?
* It should not assume that fileadmin is the ONLY location where volatile filesystem data that needs downloading to dev instances is stored in a TYPO3 system
* I like to have a symlink there. One reason is that I have symlinks for volatile data (shared between releases) on production, too and I want to make sure that any code handles that well. - At least it should not change a symlink to something else.
* I do not put anything into the hardcoded expected path `.ddev/.downloads/files` - so it also should not do anything

Basically I think my problem is that `ddev pull` is extremely opinionated for TYPO3. 

I don't think it should need any knowledge about the used framework.

In my opinion a `pull` provider should be allowed to handle importing into database and putting files in the correct locations his/herself. This would open up so much more possibilities. Maybe an option like `automatic_import: false` would help.
