### ISSUE TITLE
502: Unresponsive/broken back-end site.

### ISSUE THREAD

**Issue by nerdstein** [drud/ddev#322]
## What happened (or feature request):

I am getting the following screenshot: https://www.evernote.com/l/AEhV8B_-O95GBom4chIQvtuDhFa4lo5RFzo

Message:

```
502: Unresponsive/broken ddev back-end site.

This is the ddev-router container: The back-end webserver at the URL you specified is not responding. You may want to use "ddev restart" to restart the site.
```

## What you expected to happen:

I expected this to load the code found at `docroot` (which I assumed to be the default)

## How to reproduce it (as minimally and precisely as possible):

I followed the `ddev config` step and performed an override of the port (from 80 to 8089) in docker-composer.yml.

I went to the browser and loaded the URL generated in the terminal output: `Your application can be reached at: http://core.ddev.local` and appended the port number specified (which was not in the output).

## Related source links or issues:

**Comment by rfay** [comment]
Thanks so much for the report! Could you please gist your docker-compose.yml for us?

**Comment by nerdstein** [comment]
```
version: '2'

services:
  db:
    container_name: ddev-${DDEV_SITENAME}-db
    image: $DDEV_DBIMAGE
    volumes:
      - "./data:/db"
    restart: always
    ports:
      - "3306"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: drupal8
      com.ddev.docroot: $DDEV_DOCROOT
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_URL
  web:
    container_name: ddev-${DDEV_SITENAME}-web
    image: $DDEV_WEBIMAGE
    volumes:
      - "../:/var/www/html/docroot:cached"
    restart: always
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8089"
      - "8025"
    working_dir: "/var/www/html/docroot"
    environment:
      - DDEV_UID=$DDEV_UID
      - DDEV_GID=$DDEV_GID
      - DEPLOY_NAME=local
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.local:<port>
      # To expose a container port to a different host port, define the port as hostPort:containerPort
      - HTTP_EXPOSE=8089,8025
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: drupal8
      com.ddev.docroot: $DDEV_DOCROOT
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_URL
  dba:
    container_name: ddev-${DDEV_SITENAME}-dba
    image: $DDEV_DBAIMAGE
    restart: always
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.platform: ddev
      com.ddev.app-type: drupal8
      com.ddev.docroot: $DDEV_DOCROOT
      com.ddev.approot: $DDEV_APPROOT
      com.ddev.app-url: $DDEV_URL
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8089"
    environment:
      - PMA_USER=db
      - PMA_PASSWORD=db
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      # HTTP_EXPOSE allows for ports accepting HTTP traffic to be accessible from <site>.ddev.local:<port>
      - HTTP_EXPOSE=8036
networks:
  default:
    external:
      name: ddev_default

```
