### ISSUE TITLE
VSCode + “Remote - Containers” extension + no_project_mount: true = speed

### ISSUE THREAD

**Issue by ultimike** [drud/ddev#3316]
I've been experimenting with using the VSCode [Remote - Containers](https://github.com/Microsoft/vscode-remote-release) extension in combination with DDEV's `no_project_mount` setting and the end result so far is freakin' fast!

I have things mostly working, but am having an issue with using my SSH key pair once all is set up - I'll get to that in a moment. First, here's my setup:

- Mac OS X Big Sur
- Docker for Mac 3.6.0
- VSCode 1.61.1
- DDEV 1.18.0

## DDEV config changes/additions

- config.yaml - added `no_project_mount: true`
- config.yaml - added:

```
hooks:
  post-start:
    - exec-host: "docker cp ./web/sites/default/settings.php ddev-${DDEV_PROJECT}-web:/var/www/html/web/sites/default/"
    - exec-host: "docker cp ./web/sites/default/settings.local.php ddev-${DDEV_PROJECT}-web:/var/www/html/web/sites/default/"
    - exec-host: "docker cp ./web/sites/default/.gitignore ddev-${DDEV_PROJECT}-web:/var/www/html/web/sites/default"
```

The above copies the Drupal settings files that DDEV touches into the container.

- Created new `docker-compose.web.yaml` file with the following:

```
version: "2"

services:
  web:
    volumes:
      - web:/var/www
  
volumes:
  web:
```

The above creates a Docker volume for the code to persist through container stops and starts. 

## Current results

So far, the overwhelming takeaway from this is speed. So much speed. In a totally unscientific test, I compared a `drush cr` on a standard DDEV config with Drupal 9 with the same command using the setup above. It was about an 80% speed improvement!

## Current challenges

- When VSCode connects to the project web container, the Terminal only knows about the container - nothing outside of it. This means that the VSCode Terminal cannot run DDEV commands. In my initial testing, I've kept a standard Mac Terminal open to the project directory for running DDEV command, while using the VSCode Terminal to run Git/Drush/Composer commands inside the web container. Side note: Git inside the container is totally useable when the codebase isn't mounted to Mac OS X. Side note 2: Composer (2.x) is freakin' fast as well.
- **Main issue** - I haven't figured out how to run `git clone` (ssh) from inside the VSCode Terminal when it is connected directly to the container and have my keys work.

From the Mac OS X Terminal, I can `ddev ssh` and then run `git clone` without an issue. From the VSCode Terminal, when I try to run the same command:

```
michael@moddev-web:/var/www/html/web/modules/custom$ git clone git@github.com:ultimike/user_blocker.git
Cloning into 'user_blocker'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

So, there appears to be some something that `ddev ssh` is doing to pass in my keypair that is missing when VSCode is directly connected to the web container. Is there anything I can do to get around this? I've run `ddev auth ssh` prior to this testing.

-mike
