### ISSUE TITLE
Customize info per service in `ddev describe`

### ISSUE THREAD

**Issue by saitho** [drud/ddev#3354]
**Is your feature request related to a problem? Please describe.**
I saw the new INFO section in the `ddev describe` output that shows basic information about the services, e.g. the database passwords. I really like that and I'd like to add additional information for the services, e.g. credentials for accessing the admin panel of the application running in the web container.

**Describe the solution you'd like**

A new section in `.ddev/config.yml` would work for that, allowing to specify additional info text per service.

```yaml
additional_info:
# Syntax:   <name of service>: "Information about the service"
  web: "Admin password:\nddevisawesome"
  solr: "Nifty hint for\nthe Solr container\ngoes here"
```

The text written in there would be appended below the built-in texts, but also allow setting INFO texts for custom containers now present in the default DDEV environment.

**Describe alternatives you've considered**

Keeping the credentials in Markdown files inside the project documentation.

**Additional context**
