### ISSUE TITLE
DDEV with Mutagen enabled should automatically not sync upload_dir

### ISSUE THREAD

**Issue by rfay** [drud/ddev#3357]
Most people don't need mutagen to sync the `upload_dir` (for example, sites/default/files on Drupal). 

Since Mutagen seems to be working out OK, we can just generate the docker-compose to Docker-mount the upload_dir as described in https://ddev.readthedocs.io/en/latest/users/performance/#advanced-mutagen-configuration-options

* Add the upload_dir to .mutagen.yml
* Add the docker-compose to directly docker-mount the upload_dir

**Comment by garvinhicking** [comment]
I've just added a PR after our small Twitter discussion (thanks again). Please see if that's an acceptable addition to the docs.

I'm having issues though getting this to work properly - I hope this is the right place to discuss this. 

I think I progressed as outlined, but my mounted "fileadmin" and "uploads" directories don't seem to be /connected/.  I guess that's because the default mount is a "one-way" direction, even though the mount doesn't read like it? So if I create a file on my host, the guest (ddev) doesn't see that file. Only after a ddev poweroff and ddev start cycle the files appear there. I am not experienced enough yet in how the docker mounts are performed, could you give me a hint what I'm doing wrong?

My mount shows up as:

````
grpcfuse on /var/www/html/htdocs/web/uploads type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
grpcfuse on /var/www/html/htdocs/web/fileadmin type fuse.grpcfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)
````

(Creating files outside these directories on anything that mutagen watches, it works)

What I'm basically trying to achieve is this:

I want to be able to use mutagen on a project where multiple other developers are involved (which use mac but with nfs, or windows, or linux).

So ideally I do not want a fork of the project base for mutagen-users, but rather make changes locally. 
So within git, the `.ddev/config.yaml` sets mutagen_enabled: false. Any developer that wants to enable mutagen on the project would need to copy over some template files:

````
ddev poweroff
cp mutagen-template/config.mutagen.yml ./config.mutagen.yml
cp mutagen-template/mutagen.yml ./mutagen/mutagen.yml
cp mutagen-template/mutagen.yml ./mutagen/mutagen.yml
ddev mutagen reset
ddev start
````

My template files are these:

*.ddev/config.mutagen.yml*:
```
mutagen_enabled: true
```

*.ddev/mutagen/mutagen.yml*:
```
sync:
  defaults:
    mode: "two-way-resolved"
    stageMode: "neighboring"
    ignore:
      paths:
      - "/.git"
      - "/.tarballs"
      - "/.ddev/db_snapshots"
      - "/.ddev/.importdb*"
      - ".DS_Store"
      - ".idea"
      - "/htdocs/var"
      - "/htdocs/web/fileadmin"
      - "/htdocs/web/uploads"
      - "/htdocs/web/typo3temp"
    symlink:
      mode: "posix-raw"
```

*.ddev/docker-compose.mutagen.yml*
````
    version: "3.6"
    services:
      web:
        volumes:
          - "./htdocs/web/fileadmin:/var/www/html/htdocs/web/fileadmin"
          - "./htdocs/web/uploads:/var/www/html/htdocs/web/uploads"
````

(I specifically do not mount var and typo3temp, because I do want to let those only live on the project volume as it's only temporary)
