### ISSUE TITLE
.ddev/commands/.gitattributes won't recreate itself after deleting it

### ISSUE THREAD

**Issue by iammati** [drud/ddev#3449]
**Describe the bug**
Configuring a new project using `ddev config` it generates by default the `.ddev/commands/.gitattributes` file.
When deleting the `.ddev/commands/.gitattributes` file, it won't ever be regenerated.

**To Reproduce**
`ddev config`
`ls -la .ddev/commands/`
`rm .ddev/commands/.gitattributes`
`ddev restart`
`ls -la .ddev/commands/`

**Expected behavior**
That ddev checks the existence of the `.gitattributes` file and if necessary recreates it.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: WSL2 Debian GNU/Linux 11 (bullseye)
- Docker Desktop version: 4.1.1
- ddev version v1.18.2
- config.yaml
```
name: ze
type: typo3
docroot: public
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
nfs_mount_enabled: false
mutagen_enabled: false
hooks:
  post-start:
  - exec: composer install -d /var/www/html
  - exec: cd /var/www/html/app/frontend && pnpm i && pnpm run prod
use_dns_when_possible: true
composer_version: "2"
web_environment: []
```

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? If so, have you tried without them?
No.

**Additional context**
-
