### ISSUE TITLE
`import-db` fails if gzip file has trailing garbage

### ISSUE THREAD

**Issue by mbomb007** [drud/ddev#3500]
**Run a Diagnostic and Paste Link Here**

https://gist.github.com/mbomb007/4e1424a484e6fa7105dca849f78b0afa

Yes, I know I'm a couple versions behind, however, that's because I need to use xdebug, and that wasn't working after upgrading. However, I checked and nothing was in the changelog regarding `import-db`.

**Describe the bug**

Drupal Backup and Migrate module sometimes creates gzip files with trailing garbage, (or an invalid header?) If I use 7-zip or `gunzip` , they will unzip the file anyway, and show a warning. However, when using `import-db`, it fails with an error:

> Failed to import database db for PROJECT: failed to extract provided archive: gzip: invalid header

So I need to use `gunzip *.gz && ddev import-db < *.mysql`

**To Reproduce**

Try importing a DB backup with trailing garbage in the gzip.

To test whether a gzip has that, run `gzip -t`

> gzip -t backup-2022-01-01T10-04-18.mysql.gz 
> gzip: backup-2022-01-01T10-04-18.mysql.gz: decompression OK, trailing garbage ignored

**Expected behavior**

The file should be unzipped and imported successfully, despite it not conforming to standards.

**Version and configuration information (please complete the following information):**

- Host computer OS and Version: Windows 10 (20H2), WSL 2 (Ubuntu 20.04)
- Docker Desktop version: N/A, I installed on Linux
- ddev version information (use `ddev version`): v1.18.0
- config.yaml contents for the misbehaving project (the part before the comments)

```yaml
name: PROJECT
type: drupal9
docroot: web
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
mariadb_version: "10.5"
mysql_version: ""
nfs_mount_enabled: false
mutagen_enabled: false
hooks:
  post-start:
  - composer: install -d /var/www/html
omit_containers: [dba]
webimage_extra_packages: [build-essential, nodejs, ruby-full, rubygems, freetds-bin,
  freetds-dev, php-sybase, php-snmp, php-apcu, php-gd, php-uploadprogress]
use_dns_when_possible: true
composer_version: "2"
web_environment:
- max_input_vars=3000
```

- Do you have any custom configuration (nginx, php, mysql) in the .ddev folder? Not anything relevant

**Additional context**
