### ISSUE TITLE
Regression: (docker) manifest unknown

### ISSUE THREAD

**Issue by jonaseberle** [drud/ddev#3621]
I do get 
```
Error response from daemon: manifest for drud/ddev-dbserver-mariadb-10.3:20220102_gzip_snapshots-t3 not found: manifest unknown: manifest unknown
Unable to pull docker images: exit status 1 
```
In a project named `t3-main` and with the old-style `mariadb_version: "10.3"` setting on `ddev start`. 

Bisecting reveals 0192d0c98fc7e4a1e682899eef657e4381f68041

**Comment by jonaseberle** [comment]
It has nothing to do with the old `mariadb_version:` format. I was mislead by the shown image name.

Actually deleting `.ddev/.ddev-docker-compose-full.yaml` removes the error, but on subsquent starts (when this file is present), the error is shown.

The DB is available in any case, so it seems to be something in the UI only.

**Comment by rfay** [comment]
Wow, thanks for using and testing latest HEAD. That commit only went in yesterday. 

So this only happens (and predictably happens) when you use the `mariadb_version: 10.3` format? Happens in a dummy project?

**Comment by rfay** [comment]
Could you please share the .ddev/config.yaml, `docker-compose.*.yaml` you might be using? I wasn't able to recreate this with a trivial test. 

I see it's trying to pull "drud/ddev-dbserver-mariadb-10.3:20220102_gzip_snapshots-t3" instead of "drud/ddev-dbserver-mariadb-10.3:20220102_gzip_snapshots". 

What is the name of the project?

**Comment by jonaseberle** [comment]
Project name has `-` in it. 
I can reproduce with many projects. Just `ddev start` twice.
```
name: t3-main
type: typo3
docroot: ""
php_version: "8.1"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.3"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "16"
```
