### ISSUE TITLE
Access a localhost:1234 resource from inside a DDEV container

### ISSUE THREAD

**Issue by Moongazer** [drud/ddev#3644]
After hours of searching around and reading the Docs, it seems to be impossible to access a host-resource (e.g. running at `localhost:1234`) from inside a DDEV container.

**The (pretty common) use-case:**
Lets say a tool like [Mockoon](https://mockoon.com/) is installed to mock API endpoints (On Ubuntu this is a Snap package). It opens a server e.g. at `localhost:3001` which is accessible through the browser, but not from PHP services running inside DDEV. ~~cURL throws error 6 because it can't resolve `http://localhost:3001/my-endpoint-test`.~~

Is it somehow possible to configure the DDEV router to map certain host:port addresses to the local host machine?
Any help very appreciated!

**Edit:**
Playing around with the ports/expose/hosts configs, now cURL saying "_error 7: Failed to connect to localhost port 3001: Connection refused_". This is great I think, because it gives me hope that somehow it could be configured to reach port 3001.

Also I found [docker-host](https://github.com/qoomon/docker-host), but is it really so complicated to archive this, or is there a better way built into DDEV already?

**Comment by rfay** [comment]
Hi and welcome @Moongazer -

If you're working with an http service, the easy way to do this is with HTTP_EXPOSE and HTTPS_EXPOSE in a `docker-compose.*.yaml` file, https://ddev.readthedocs.io/en/latest/users/extend/custom-compose-files/

The only issue if you're actually running it inside the *web* container, you have to override the existing values because there are existing values.

The default values are 
```yaml
  web:
     environment:
       HTTP_EXPOSE: 80:80,8025:8025
        HTTPS_EXPOSE: 443:80,8026:8025
```

So you'd need to add your service to that (unless you're running it in a different container). 

So a `docker-compose.mockoon.yaml` might contain
```yaml
version: 3.6
services:
  web:
    environment:
      HTTP_EXPOSE: 80:80,8025:8025,1234:1234
      HTTPS_EXPOSE: 443:80,8026:8025,1235:1234
```
It's not essential that you have the HTTPS_EXPOSE.

This only works with HTTP, as it's exposing via ddev-router.

If you have a non-http service, you'll have to use a `ports` statement,
```yaml
    ports:
      - 1234
```

or 
```yaml
    ports:
    - 1234:1234
```

The latter one will conflict if you try to run it in more than one project at a time.
