### ISSUE TITLE
Inability to create upload_dir should get a warning instead of a failure

### ISSUE THREAD

**Issue by andreashager** [drud/ddev#3688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

https://gist.github.com/andreashager/3927320cef35963cdd3dbcf6a49c7b49

### Current Behavior

DDEV tries to create the fileadmin folder but the fileadmin folder is already there. The fileadmin folder is NFS Mount to a storage folder that contains our uploaded files.

The structure:
- public/fileadmin --> Symlink to ../shared/fileadmin
- shared/fileadmin --> Symlink to /mnt/nfsstorage/

`.ddev/docker-compose.override.yaml`
```yml
version: '3.6'
volumes:
  nfsstorage:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.1.5,vers=3,rw"
      device: ":/volume2/limestorage"
services:
  web:
    volumes:
      - "nfsstorage:/mnt/nfsstorage/"
```

### Expected Behavior

DDEV should not fail because the file or folder is there but its a symlink to a NFS Share.
When i remove the symlink to the NFS share in shared/fileadmin and create a fileadmin folder there than it works without problems. Maybe the filemount is not yet active when DDEV checks if the file/folder exists.

### Steps To Reproduce

1. Create `docker-compose.override.yaml` with NFS filemount
2. Symlink fileadmin folder to the NFS Share
3. ddev start
4. Start process will fail with `Failed to restart project: failed to write settings file /project/public/typo3conf/AdditionalConfiguration.php: Unable to create upload directory: mkdir /project/public/fileadmin: file exists`
