### ISSUE TITLE
Web container should depend on db container readiness unless omit_containers[db]

### ISSUE THREAD

**Issue by andreasfernandez** [drud/ddev#3702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have a supervisor configuration that executes a Symfony message consumer when starting the project. The boot process tends to fail in case the `db` container is not ready yet.

The message related to this issue found in the logs is as follows:
```
An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused
```

### Describe the solution you'd like

The following configuration stored in `.ddev/docker-compose.overwrite.yaml` workarounds the issue:
```
services:
  web:
    depends_on:
      - "db"
```

This could be done automatically by ddev, unless `omit_containers[db]` is set.

**Comment by jonaseberle** [comment]
Just want to note that `depends_on` is not a 100% solution either. Yes, it waits until the other container is about to start its PID 1, but it does not check if that started service is now ready to serve requests on any of its ports.

In the worst case this might just slow down project startup slightly.

We have a snippet here that actually waits for the service to be ready which I think is an ingenious solution (thanks to lolli): 
https://github.com/TYPO3/typo3/blob/main/Build/testing-docker/local/docker-compose.yml#L77-L79

I think doing that (or similar in PHP) in that app startup script would get you there, too.

**Comment by rfay** [comment]
I *think* that it should wait until the healthcheck is happy, and if the healthcheck is working on db container, that should be OK. It's possible the healthcheck needs to be improved though.

**Comment by jonaseberle** [comment]
@andreasfernandez how is that startup script run? `post-start` hooks should actually run after the health check, shouldn't they?

**Comment by rfay** [comment]
He has it in the supervisord config

**Comment by mikebarkas** [comment]
I added depends_on to the web container if no omit db.

Started a new d9simple and verified the compose file.
```
  web:
    build:
      args:
        BASE_IMAGE: drud/ddev-webserver:v1.19.2
        gid: "20"
        uid: "501"
        username: mike.barkas
      context: /Users/mike.barkas/ddev-dev/d9simple-project/d9simple/.ddev/.webimageBuild
      dockerfile: Dockerfile
    cap_add:
    - SYS_PTRACE
    container_name: ddev-d9simple-web
    depends_on:
      db:
        condition: service_started
    environment:
      COLUMNS: "135"
```
