### ISSUE TITLE
Allow ENV Variables in docker-compose.* definition

### ISSUE THREAD

**Issue by solverat** [drud/ddev#3938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Using env variables in docker-compose.* should be possible, like docker compose does.

### Describe the solution you'd like

In my default `docker-compose.yml` I was able to use imported variables like this:

```yaml
# docker-compose.yml
version: '3.6'
services:
    web:
        env_file:
            - .env
        volumes:
            - ${MY_VARIABLE}:/var/www/public
```

Doing this within the ddev context:

```yaml
# .ddev/docker-compose.env-file.yaml
version: '3.6'
services:
    web:
        env_file:
            - ../.env
``` 

```yaml
# .ddev/docker-compose.mounts.yaml
version: '3.6'
services:
    web:
        volumes:
            - ${MY_VARIABLE}:/var/www/public
``` 

will return

> The \"MY_VARIABLE\" variable is not set. Defaulting to a blank string." 

I also tried to merge `docker-compose.env-file.yaml` and `docker-compose.mounts.yaml` with no luck. 

It would be great to have this feature in ddev context!
