### ISSUE TITLE
Support "base" config files to be loaded always before config.yaml

### ISSUE THREAD

**Issue by davereid-pfg** [drud/ddev#3992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

We provide a standard DDEV config file for many different sites that is scaffolded out with [Drupal's composer scaffolding](https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold). With Lando we were able to use a `.lando.upstream.yml` file that was always loaded first, and then the individual's site configuration then overrides that, then the `.lando.local.yml`.

Right now a `config.upstream.yml` file is loaded **after** the `config.yaml` file, making it impossible for a site to override specific configurations in our upstream configuration. There appears to be specific logic allowing `config.local.yaml` to be always loaded last, so that part works currently.

### Describe the solution you'd like

I'd love to have DDEV match the config ordering that Lando uses with https://docs.lando.dev/config/.

Specifically, these files will always be loaded first:
```
config.base.yaml
config.dist.yaml
config.upstream.yaml
```

Then load the rest alphabetically, then load `config.local.yaml` last as per the current behavior.

### Example files

```yaml
# config.upstream.yaml
# Across all of our sites we generally support the LTS version of NodeJS:
nodejs_version: 16
```

```yaml
# config.yaml
# A site has opted-in to a newer version of NodeJS:
nodejs_version: 18 
```

#### Expected result of running `ddev debug configyaml`:
```yaml
nodejs_version: 16
```

#### Current result of running `ddev debug configyaml`:
```yaml
nodejs_version: 18
```

**Comment by rfay** [comment]
@davereid-pfg could you please give a practical example of why you would do this, instead of just having the `config.yaml` as the base file? 

I'm sure you already know that
* https://github.com/drud/ddev/pull/3983

will provide the ability to *merge* `config.*.yaml` instead of just overwriting.

/cc @torenware

**Comment by torenware** [comment]
One use case, which may or may not be relevant to @davereid-pfg 

I've developed a ddev add-on (torenware/ddev-viteserve), which could use a safe place for its default settings. The new config merger would be a good way to do this.  But since a config.ddev-viteserve.yaml file would get read after config.yaml, this means that a user, who might think she could override my add-on settings in config.yaml, would find this would not work. 

This is not a big deal; the docs for an add-on could say: "please edit config.MYADDON.yaml" to change my add-on settings. 

But if there was a class of config yaml files that were read *before* config.yaml, then the user's expectation as to how to configure DDEV would be better met.  

I'm also interested to hear how @davereid-pfg  would use each of the config file types.  I assume that for a project using DDEV, config.yaml would live in source control, so there is already a project-level config file.  I would guess that a config-base.yaml file would have shop level settings (component versions, server types, etc.). 

Am I understanding how you intend to use this?

**Comment by davereid-pfg** [comment]
Yeah, our config.base.yaml file has all of our shop-level settings, and is scaffolded using Composer from our install profile automatically:

#### `config.base.yaml`
```yaml
# Do not modify this file. To override this file use https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#toc_6

type: drupal9
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.3"
nfs_mount_enabled: false
mutagen_enabled: true
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
nodejs_version: 14
hooks:
  pre-start:
    # Ensure minimum version of DDEV being used.
    - exec-host: (ddev debug capabilities | grep pre-dockerfile-insertion >/dev/null) || (echo "Please upgrade ddev to v1.19.5+ to support necessary features for local environments.")
  post-start:
    # Install Terminus secrets plugin.
    - exec: terminus self:plugin:install terminus-secrets-plugin
    # Ensure authentication is ready for composer and npm to download dependencies.
    - exec: .ddev/scripts/auth.sh
    # Run the build process.
    - exec: robo setup:build
  post-import-db:
    # Sanitize the database after import.
    - exec: drush sql:sanitize -y --sanitize-email=no --sanitize-password=no
```

Sites also have their own config.yaml file to source control but all it contains is the following one line:

#### `config.yaml`
```yaml
name: my-pantheon-site-name
```
