### ISSUE TITLE
Enforce a minimum version of DDEV from config

### ISSUE THREAD

**Issue by davereid-pfg** [drud/ddev#4036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

We have a shared config file we provide to a network of sites, and I would like to enforce that everyone's local DDEV at least uses the latest version to take advantage of the preDockerfile feature.

### Describe the solution you'd like

It would be nice to enforce this via our config.base.yaml file like this:

```yaml
ddev_minimum_version: 1.19.5
```

### Describe alternatives you've considered

I could also possibly do this myself in the pre-start exec-host hook, but it would be nice to have this supported upstream.

**Comment by rfay** [comment]
Hi @davereid-pfg - the way I've been doing this is with `ddev debug capabilities` - just create a pre-start exec-host hook that checks capabilities, something like

```yaml
hooks:
  pre-start:
    exec-host: (ddev debug capabilities | grep ddev-get-yaml-interpolation >/dev/null) || (echo "Please upgrade ddev to v1.19.4+ to support yaml interpolation")
```
