### ISSUE TITLE
host-side environment variable interpolation in docker-compose.*.yaml 

### ISSUE THREAD

**Issue by torenware** [drud/ddev#4043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm updating my [ddev-viteserve plugin](https://github.com/torenware/ddev-viteserve) to work with Vite 3 (different port for the dev server) and for the `config-star-yaml-merging` capability that is currently in HEAD and is scheduled for ddev 1.20. I'm working with HEAD right now, installed via homebrew.  I'd like to do something like this in a config.vite.yaml file:

```yaml
# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE
# Derived from the browsersync addition.
# This is to expose the vite dev port.
version: '3.6'
services:
  web:
    environment:
      # Expose the vite dev server's port (default 3000) here.
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,${VITE_HTTP_PORT}::${VITE_HTTP_PORT}
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,${VITE_HTTPS_PORT}:${VITE_HTTP_PORT}
```

I'm trying to inject the VITE_HTTP_PORT and VITE_HTTPS_PORT into the HTTP_EXPOSE and HTTPS_EXPOSE environment strings the way you do with DDEV_ROUTER_HTTP_PORT and friends.

This currently does not work, since there's no obvious place to define VITE_HTTP_PORT etc. where it will be available to DDEV when you run `ddev start`, unlike the `DDEV_*` variables which are populated very early in the bootstrap process. I get an error like this when I run `ddev restart`, for example:

```sh
Pushed mkcert rootca certs to ddev-global-cache/mkcert
The VITE_HTTP_PORT variable is not set. Defaulting to a blank string.
The VITE_HTTPS_PORT variable is not set. Defaulting to a blank string.
Creating network "ddev-phpunit-course_default" with the default driver
```

An interesting work-around that tells you what's going on: if you make the variables available when `ddev start` or `ddev restart` runs, things *do* work:

```sh
VITE_HTTP_PORT=5173  VITE_HTTPS_PORT=5174  ddev restart
```

as I might want to do for a Vite 3 project.  If I do this, I do not get the above error, and interpolation will work at startup time.

I initially tried to put definitions for VITE_HTTP_PORT and VITE_HTTPS_PORT into a `.ddev/docker-compose.viteserve.yaml` file, but this is processed too late to be available when config.vite.yaml would be processed.  I also tried using config.yaml, but again, I get a "variable is not set. Defaulting to a blank string" error at restart. 

This is not something we discussed when we implemented the config-star-yaml-merging feature, and it probably would not have been in-scope for that PR in any case.  It makes sense why this would not work right now; there's neither chicken nor egg at this point of the bootstrapping process :-) 

But is there currently a way to get a given environment variable to define earlier, so it is available to the interpolation process?

### Describe the solution you'd like

Any type of file that would allow for environment variables that were loaded into the ddev process before config.yaml and the various config.*.yaml files are loaded.  This is very specific to environment variables, since they are the only things that have syntax for interpolation in any case. I don't know if ddev support dotenv files or if there's a way to get an add-on to run early enough to process something into ddev's environment.  But IIRC the [golang joho/godotenv module](https://github.com/joho/godotenv) _does_ support loading a sequence of files, which would allow a base user dotenv file + things like add-on overrides.  If dotenv loads before the config files are bootstrapped, then this would probably work.

### Describe alternatives you've considered

The alternative is to have users manually edit things like the HTTP_EXPOSE and HTTPS_EXPOSE, which is what they need to do now. This is error prone, and if I could avoid asking them to do this, it would improve their experience of using the add-on.
