### ISSUE TITLE
Postgres dump problem with postgres 14

### ISSUE THREAD

**Issue by elrokket** [drud/ddev#4082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i execute dump (with **drush sql-dump** or **pg_dump -h db -p 5432 -U db -f backup.sql db**) return following error:

`pg_dump: error: server version: 14.3 (Debian 14.3-1.pgdg110+1); pg_dump version: 13.5 (Debian 13.5-0+deb11u1)`

### Expected Behavior

The same version is necessary in server and cli to use psql commands.

### Steps To Reproduce

configure config.yml with this data:

```
name: proyectname
type: drupal9
docroot: web
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: postgres
  version: "14"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
disable_settings_management: true
web_environment: []
nodejs_version: "14"
```

into container execute:

`drush sql-dump > database.sql 
`
or

`pg_dump -h db -p 5432 -U db -f backup.sql db
`
