### ISSUE TITLE
1.21.1 - Can't start project: "the configured database type does not match the current actual database"

### ISSUE THREAD

**Issue by garvinhicking** [drud/ddev#4129]
TL;DR: Fix in https://github.com/drud/ddev/issues/4129#issuecomment-1220070181

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

(need to check)

### Current Behavior

ddev project does not start, shows error:

`Failed to start fe-kuerschnersmart: Unable to start project fe-kuerschnersmart because the configured database type does not match the current actual database. Please change your database type back to “” and start again`

### Expected Behavior

Project getting booted

### Steps To Reproduce

Environment: MacOS
Previous ddev: 1.18.2
Installed via homebrew

config.yaml of project:

```yaml
name: fe-kuerschnersmart
router_http_port: "80"
router_https_port: "443"
mailhog_port: "15007"
type: typo3
docroot: htdocs/web/
nodejs_version: 16
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames:
  ['bundestag.fe-kuerschnersmart', 'bw.fe-kuerschnersmart', 'home.fe-kuerschnersmart', 'relaunch.fe-kuerschnersmart']
additional_fqdns: []
mariadb_version: "10.2"
php_version: "7.4"
#mysql_version: "" # was previously contained, but doesn't matter if we leave it in or out
use_dns_when_possible: true
mutagen_enabled: false
composer_version: "2"
web_environment:
- SURF_WORKSPACE=/var/www/html/deployment/workspace
- SURF_HOME=/var/www/html/deployment
- GIT_SSH_COMMAND=ssh -i /var/www/html/deployment/ssh/id_rsa
- TYPO3_CONTEXT=Development/Ddev
hooks:
  post-start:
  - exec: bash /var/www/html/.ddev/scripts/vagrant-compat.sh
  - exec: bash /var/www/html/.ddev/scripts/sanity-check.sh
  - exec: nvm install
  - exec: nvm use
disable_settings_management: true
webimage_extra_packages: [build-essential, joe]
```

### Anything else?

A colleage had ddev 1.18.2 and upgraded to ddev - expecting version 1.20 that we others had, but he got the new version.

Since then he cannot boot up the project that was working previously. The changelog contains:

`ddev start now checks on startup to see if the existing database binary information is compatible with the configured database version and fails if it is not the same.``

which I believe could be the culprit here. We didn't change the mariadb_version in the project. Without the project starting, we don't know how to inspect the actual db volume, or what an error could be. Especially the error message with an empty string ""  strikes our mind. We ruled out the empty 'mysql_version' yaml string being the culprit.

Any ideas how we can debug this further or what could be an issue? I don't want to upgrade my working environment to stumble into the same situation because of important client work, so I'm not sure if I could reproduce it on my machine, too.

I've asked for the `ddev debug` output, but that may take some time.
