### ISSUE TITLE
Next.js (Nodejs app) not properly proxied through nginx

### ISSUE THREAD

**Issue by hchonov** [drud/ddev#4208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

The nextjs will be properly proxied through nginx.

### Actual Behavior

The nextjs app is not properly proxied through nginx - 403 Forbidden.

### Steps To Reproduce

I have an nginx app that I start with the following ddev config:

```
name: app
project_tld: localdomain.com
type: php
webserver_type: nginx-fpm
omit_containers: ['db', 'dba']
nodejs_version: 14
disable_settings_management: true
web_extra_daemons:
  - name: "node-app"
    command: "NODE_ENV=development PORT=3000 node server.js"
    directory: /var/www/html
web_extra_exposed_ports:
  - name: "node-app"
    container_port: 3000
    http_port: 80
    https_port: 443
```

I can confirm that the app starts properly, but nginx does not forward it correctly when visting https://app.localdomain.com and I get 403 response.

I can get it working only with a custom nginx config as it was already suggested in https://github.com/drud/ddev/issues/3456 that is configured to act as reverse proxy:

```
# ddev default (Node project type) config

# If you want to take over this file and customize it, remove the line above
# and ddev will respect it and won't overwrite the file.
# See https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-nginx-configuration

server {
    listen 80 default_server;
    listen 443 ssl default_server;

    root /var/www/html;

    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;

    include /etc/nginx/monitoring.conf;

    # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
    sendfile off;
    error_log /dev/stdout info;
    access_log /var/log/nginx/access.log;

    location / {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass https://localhost:3000;
        proxy_pass_request_headers on;
        proxy_http_version 1.1;

        # Allow websocket upgrade.
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Prevent clients from accessing hidden files (starting with a dot)
    # This is particularly important if you store .htpasswd files in the site hierarchy
    # Access to `/.well-known/` is allowed.
    # https://www.mnot.net/blog/2010/04/07/well-known
    # https://tools.ietf.org/html/rfc5785
    location ~* /\.(?!well-known\/) {
        deny all;
    }

    # Prevent clients from accessing to backup/config/source files
    location ~* (?:\.(?:bak|conf|dist|fla|in[ci]|log|psd|sh|sql|sw[op])|~)$ {
        deny all;
    }

    include /etc/nginx/common.d/*.conf;
    include /mnt/ddev_config/nginx/*.conf;
}
```

**Comment by rfay** [comment]
You can't use ports 80 and 443 because nginx is already using those. You have to use ports that aren't already in use... Please try 3000 and 3001 or something.

**Comment by rfay** [comment]
I imagine the problem is that you were trying to force ports 80 and 443 which are already in use (by default) in your system. 

No response from you in 10 days, so I imagine that solves your problem, but I'll close this. Happy to continue the conversation here or elsewhere.

**Comment by hchonov** [comment]
> No response from you in 10 days, so I imagine that solves your problem, but I'll close this. Happy to continue the conversation here or elsewhere.

I was at two conferences in the past week :).

> I imagine the problem is that you were trying to force ports 80 and 443 which are already in use (by default) in your system.

With the default nginx config and with the following ddev config I get the error below:

config:
```
web_extra_daemons:
  - name: "node-app"
    command: "NODE_ENV=development PORT=3000 node server.js"
    directory: /var/www/html
web_extra_exposed_ports:
  - name: "node-app"
    container_port: 3000
    http_port: 3000
    https_port: 3001
```
error:
`2022/09/27 11:04:08 [error] 2213#2213: *18 directory index of "/var/www/html/" is forbidden, client: 172.18.0.7, server: , request: "GET / HTTP/1.1", host: "blog.local.hq.unity.com"`
