### ISSUE TITLE
Missing AdditionalConfiguration.php with TYPO3 v8 non-composer mode

### ISSUE THREAD

**Issue by liayn** [drud/ddev#4326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

`AdditionalConfiguration.php` is generated.

### Actual Behavior

The file is missing, hence the site does not work.

### Steps To Reproduce

- classic installation of TYPO3 v8 (https://github.com/TYPO3/typo3/blob/TYPO3_8-7/INSTALL.md#installation)

- `typo3_src` folder being mounted into the container like below

docker-compose.local.yaml:
```
      - type: bind
        source: '/mnt/c/TYPO3/CMS/TYPO3_8-7/'
        target: '/var/www/html/typo3_src'
```

### Anything else?

ddev 1.21.3

ddev config:

```
name: redacted
type: typo3
docroot: html
php_version: "7.3"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.3"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
timezone: Europe/Vienna
composer_version: "2"
web_environment:
  - TYPO3_CONTEXT=Development/ddev
nodejs_version: "16"
```
