### ISSUE TITLE
(CraftCMS) When omit_containers: [”db", "dba"] is set don't create /home/user/.my.cnf

### ISSUE THREAD

**Issue by jan-thoma** [drud/ddev#4389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

When working with external Databases by disabling the DB container with  `omit_containers: [”db", "dba"]` in c`onfig.yml `, `~/.my.cnf` should be empty or omited. so CraftCMS can pick up the correct DB settings from it's `.env` file when running the `mysqldump` command

### Actual Behavior

When `~/.my.cnf`is created even when `omit_containers: [”db", "dba"]` is present the `./craft db/backup` command exits whit an error

```
Backing up the database ... error: The shell command "mysqldump --defaults-extra-file="/tmp/xwecxbjielux.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --single-transaction --no-data --result-file="/var/www/html/storage/backups/tkf--2022-11-18-134826--v4.3.3.sql" tkf && mysqldump --defaults-extra-file="/tmp/xwecxbjielux.cnf" --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --default-character-set=utf8 --set-charset --triggers --no-tablespaces --no-create-info --ignore-table=tkf.assetindexdata --ignore-table=tkf.imagetransformindex --ignore-table=tkf.resourcepaths --ignore-table=tkf.sessions --ignore-table=tkf.cache tkf >> "/var/www/html/storage/backups/tkf--2022-11-18-134826--v4.3.3.sql"" failed with exit code 2: mysqldump: Got error: 2005: "Unknown MySQL server host 'db' (-2)" when trying to connect
```

### Steps To Reproduce

1. Create a new CraftCMS Project as described in the docs
```
mkdir my-craft-project
cd my-craft-project
ddev config --project-type=craftcms
ddev composer create -y --no-scripts --no-install craftcms/craft
ddev start
ddev composer update
ddev craft install
ddev launch
```

2. Change the config to the following
```
name: myname
type: craftcms
docroot: web
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.4"
disable_settings_management: true
nfs_mount_enabled: false
mutagen_enabled: false
omit_containers: ["db", "dba"]
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "16"
```

3. SSH into the container and run
```
./craft db/backup
```

### Anything else?

Creating an empty `~/.my.cnf` file resolves the issue
