### ISSUE TITLE
curl request results in: LibreSSL SSL_connect: SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by froemken** [drud/ddev#4427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Run a Diagnostic and Paste Link Here

ddev version v1.21.3

Docker Desktop for Mac: 4.15.0 (93002)
Docker Desktop for Mac: Compose: v2.13.0

Mac OS Version: 13.0.1 (22A400)
Apple M1

DDEV config:

```
name: typo3git
type: typo3
docroot: ""
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.3"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "16"
```

### Expected Behavior

Get a curl response from my DDEV project without SSL error

### Actual Behavior

curl results into an error:

```
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to typo3git.ddev.site:443 
```

### Steps To Reproduce

curl -vvv -X 'POST' 'https://typo3git.ddev.site' 

*   Trying ::1:443...
* connect to ::1 port 443 failed: Connection refused
*   Trying 127.0.0.1:443...
* Connected to typo3git.ddev.site (127.0.0.1) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to typo3git.ddev.site:443 
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to typo3git.ddev.site:443 

### Anything else?

If I try requesting my DDEV project with generated SSL port it works:

```
curl -vvv -X 'POST' '127.0.0.1:50234'
```

Seems that somekind of DNS does not work correctly.

```
Trying 127.0.0.1:443
```

is IMO totally wrong.
