### ISSUE TITLE
`ddev exec` doesn't pick up new nvm-defined node version

### ISSUE THREAD

**Issue by jamesmacwhite** [drud/ddev#4499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

Through a post-start hook I want to call yarn start, but this fails because it does not meet the required node version defined in package.json of a project. Switching the web container to use the required node version works, but yarn start does not seem pickup this and instead continues to use the `nodejs_version` set in `config.yaml`.

### Actual Behavior

I am trying to use a different version of node in the web container and setup a post-start hook for `yarn start`. The version provisioned is `14` however a project needs a lower version "10.16". I setup a post-start hook command like so:

```yaml
hooks:
  post-start:
    - exec-host: ddev nvm install 10.16.0 && ddev nvm use
    - exec: yarn start
```

exec-host is needed for the nvm commands as otherwise it fails.

This outputs:

```
v10.16.0 is already installed.
Now using node v10.16.0 (npm v6.9.0)
Found '/var/www/html/.nvmrc' with version <10.16.0>
Now using node v10.16.0 (npm v6.9.0)
yarn run v1.22.19
error example-project@1.0.0: The engine "node" is incompatible with this module. Expected version "^10.16.0". Got "14.21.1"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The `node --version` command returns the original node version provisioned in config.yaml `14.21.1` when run via a hook, however if I `ddev ssh` and then run `node --version` it is set to `v10.16.0` and yarn runs fine.

**Comment by jamesmacwhite** [comment]
I've also tried calling yarn start with `exec-host: ddev yarn start` in a post-start hook but the node version conflict still occurs with the same issue. Only when I SSH into the web container and then `yarn start` within does it work.

**Comment by rfay** [comment]
I think the problem is you're missing a step here. Please see https://github.com/drud/ddev/issues/4376#issuecomment-1312300592

**Comment by jamesmacwhite** [comment]
@rfay Thanks, I did see this, unfortunately, node --version does not return the set value when doing the alias command, it remains at: 14.21.1

**Comment by rfay** [comment]
I don't know what `yarn start` does, of course. Does it use the current environment? Could you please demonstrate this with something that can be demonstrated more easily? Like use a `node --version` in the second hook?

**Comment by jamesmacwhite** [comment]
It seems after running all the nvm commands and then doing `ddev exec node --version`, the node version hasn't in fact changed, you can see that v14.21.1 was output on that example above. That's why yarn is failing. That should be 10.16.0, based on the nvm commands before it.

`yarn start` is just an alias to `yarn run xxxxx` in this project, but basically there's a specific engines definition in the package.json for 10.16.0, which is why yarn just stops because it's an engine conflict. The yarn run commands need to have a lower version of Node as it uses an older setup.

If that makes sense.

**Comment by jamesmacwhite** [comment]
If it helps:

```yaml
hooks:
  post-start:
    - exec-host: ddev nvm install 10.16.0 && ddev nvm use && ddev nvm alias default 10.16.0
    - exec-host: ddev exec node --version
```

```
v10.16.0 is already installed.
Now using node v10.16.0 (npm v6.9.0)
Found '/var/www/html/.nvmrc' with version <10.16.0>
Now using node v10.16.0 (npm v6.9.0)
default -> 10.16.0 (-> v10.16.0)
v14.21.1
```

The fact node --version returned 14.21.1, is the issue.

**Comment by rfay** [comment]
The PATH isn't getting picked up with `ddev exec` and company:

```
$ ddev exec 'echo $PATH'
~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/html/vendor/bin:/var/www/html/bin:/var/www/html/vendor/bin
rfay@rfay-tag1-m1:~/workspace/d9$ ddev ssh
rfay@d9-web:/var/www/html$ echo $PATH
~/bin:/home/rfay/.nvm/versions/node/v10.16.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/html/vendor/bin:/var/www/html/bin:/var/www/html/vendor/bin
```

**Comment by jamesmacwhite** [comment]
That would explain why the container is set correctly but ddev commands fail.

**Comment by jamesmacwhite** [comment]
Confirmed. As a test, manually specifying the path:

```
hooks:
  post-start:
    - exec-host: ddev nvm install 10.16.0 && ddev nvm use && ddev nvm alias default 10.16.0
    - exec: /home/jameswhite/.nvm/versions/node/v10.16.0/bin/node --version
```

```
v10.16.0 is already installed.
Now using node v10.16.0 (npm v6.9.0)
Found '/var/www/html/.nvmrc' with version <10.16.0>
Now using node v10.16.0 (npm v6.9.0)
default -> 10.16.0 (-> v10.16.0)
v10.16.0
```

**Comment by rfay** [comment]
Even this doesn't do it:
`ddev exec 'bash -il -c "echo $PATH"'`

However, this will do it for you temporarily, although this is a bug.
`ddev exec 'export PATH=~/.nvm/versions/node/v10.16.0/bin:$PATH; node --version'`

Mostly this is a chase caused by nvm's totally weird implementation as bash nonsense instead of as a real command.

**Comment by jamesmacwhite** [comment]
Thank you for the workaround, I was about to suggest potentially modifying the path, so that seems like the workable solution for now!

Yeah, nvm is certainly not easy to work with when it's not really "installed", plenty of stackoverflow posts around it being a bit of a pain!

**Comment by rfay** [comment]
Will try to chase this down in upcoming release cycle.

**Comment by jamesmacwhite** [comment]
Thank you! For reference for anyone else coming across this issue, adding the nvm version to the PATH followed by whatever command need works, in my case `yarn start`

```
hooks:
  post-start:
    - exec-host: ddev nvm install 10.16.0 && ddev nvm use
    - exec-host: ddev exec 'export PATH=~/.nvm/versions/node/v10.16.0/bin:$PATH; yarn start'
```

It must be run with the ddev exec command that modifies the PATH, otherwise it will fail given it cannot see the node version.
