### ISSUE TITLE
Traefik does not properly handle $VIRTUAL_HOST

### ISSUE THREAD

**Issue by stmh** [drud/ddev#4537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

I do have a special setup to mimic our production environment. A regular drupal installation `app.ddev.site` and a special service hosting a node application at `ws.app.ddev.site`

This works without problems with the "old" router but fails for traefik. HTTP traffic gets routed to the node application, and HTTPS traffic to the drupal installation, regardless of the hostname in the URL.

Here's my snippet for the node service:

```yaml
version: '3.6'

services:
  web:
    environment:
      WS_PUBLISH_URL: http:/ws:3000/publish
      WS_SUBSCRIBE_URL: wss://ws.${DDEV_HOSTNAME}/subscribe
  ws:
    image: our.private.registry:8443/a/path/ws:main
    container_name: ddev-${DDEV_SITENAME}-ws
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    ports:
      - 3000
    environment:
      - VIRTUAL_HOST=ws.${DDEV_HOSTNAME}
      - HTTP_EXPOSE=80:3000
      - HTTPS_EXPOSE=443:3000
 ```

I'd expect that the traffic gets routed to the right containers, depending on the VIRTUAL_HOST-setting, similar to what the old router does.

### Actual Behavior

The traffic to `app.ddev.site:80` gets handled by the service `ws`, traffic to `app.ddev.site:443` is handled by the container `web`.
The traffic to `ws.app.ddev.site:80` gets handled by the service `ws`, traffic to `ws.app.ddev.site:443` is handled by the container `web`.

So it seems that `VIRTUAL_HOST` is ignored for traefik setups.

**Comment by rfay** [comment]
VIRTUAL_HOST is explicitly supported, see https://github.com/drud/ddev/blob/02b52a3d07af1df981c3e3310009e71c74a108a6/pkg/ddevapp/traefik.go

But that doesn't mean there's not a bug. 

Would you be willing create a simple demonstration repository that demonstrates this, with instructions?

**Comment by stmh** [comment]
Hi @rfay here's the minimal repo: https://github.com/stmh/reproduce-traefik-virtualhost

It will create the ddev standard PHP setup serving `index.php` and an additional container using `nginx` to serve the default page from nginx. With the old router, it works as expected. With traefik as the router, the nginx subdomain is not reachable. See the readme of the repo for a step-by-step guide.

**Comment by rfay** [comment]
That was quick, thanks so much! 

You may want to consider poking around at configuring traefik directly, since VIRTUAL_HOST handling is just a crutch/workaround to try to implement  the new traefik config in terms of VIRTUAL_HOST. You can look at the config that actually gets generated in your .ddev/traefik directory.

**Comment by stmh** [comment]
yeah, I inspected them, and they do not mention my custom hostnames, e.g.` nginx.reproduce-traefik-virtualhost.ddev.site`, just the main one.

**Comment by rfay** [comment]
It looks to me like there are a couple of problems. 

1. It walks app.GetHostnames() when populating the template values, when it should be walking `hostnames`, which was derived above - https://github.com/drud/ddev/blob/02b52a3d07af1df981c3e3310009e71c74a108a6/pkg/ddevapp/traefik.go#L335
2. It seems to think that all hostnames are created equal (and not assigned to particular services), so doesn't direct the specific VIRTUAL_HOST here to the right service even when we use `hostnames` above.

**Comment by rfay** [comment]
Here's something close to what we want to have:

<details>
<summary>.ddev/traefik/config/reproduce-traefik-virtualhost.yaml</summary>
```yaml
http:
  routers:


    reproduce-traefik-virtualhost-dba-80-http:

      rule: HostRegexp(`reproduce-traefik-virtualhost.ddev.site`)

      service: "reproduce-traefik-virtualhost-dba-80-http"
      tls: false
      entrypoints:
        - http-8036



    reproduce-traefik-virtualhost-nginx-80-http:

      rule: HostRegexp(`reproduce-traefik-virtualhost.ddev.site`)

      service: "reproduce-traefik-virtualhost-nginx-80-http"
      tls: false
      entrypoints:
        - http-80



    reproduce-traefik-virtualhost-web-80-http:

      rule: HostRegexp(`reproduce-traefik-virtualhost.ddev.site`)

      service: "reproduce-traefik-virtualhost-web-80-http"
      tls: false
      entrypoints:
        - http-80


    reproduce-traefik-virtualhost-web-8025-http:

      rule: HostRegexp(`reproduce-traefik-virtualhost.ddev.site`)

      service: "reproduce-traefik-virtualhost-web-8025-http"
      tls: false
      entrypoints:
        - http-8025





    reproduce-traefik-virtualhost-dba-80-https:
      # UseLetsEncrypt=false

      rule: HostRegexp(`reproduce-traefik-virtualhost.ddev.site`)

      service: "reproduce-traefik-virtualhost-dba-80-https"

      tls: true

      entrypoints:
        - http-8037



    reproduce-traefik-virtualhost-nginx-80-https:
      # UseLetsEncrypt=false

      rule: HostRegexp( `nginx.reproduce-traefik-virtualhost.ddev.site`)

      service: "reproduce-traefik-virtualhost-nginx-80-https"

      tls: true

      entrypoints:
        - http-443




    reproduce-traefik-virtualhost-web-80-https:
      # UseLetsEncrypt=false

      rule: HostRegexp(`reproduce-traefik-virtualhost.ddev.site`)

      service: "reproduce-traefik-virtualhost-web-80-https"

      tls: true

      entrypoints:
        - http-443


    reproduce-traefik-virtualhost-web-8025-https:
      # UseLetsEncrypt=false

      rule: HostRegexp(`reproduce-traefik-virtualhost.ddev.site`)

      service: "reproduce-traefik-virtualhost-web-8025-https"

      tls: true

      entrypoints:
        - http-8026



  services:

    reproduce-traefik-virtualhost-dba-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-reproduce-traefik-virtualhost-dba:80

    reproduce-traefik-virtualhost-dba-80-https:

      loadbalancer:
        servers:
          - url: http://ddev-reproduce-traefik-virtualhost-dba:80

    reproduce-traefik-virtualhost-nginx-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-reproduce-traefik-virtualhost-nginx:80

    reproduce-traefik-virtualhost-nginx-80-https:

      loadbalancer:
        servers:
          - url: http://ddev-reproduce-traefik-virtualhost-nginx:80

    reproduce-traefik-virtualhost-web-80-http:
      loadbalancer:
        servers:
          - url: http://ddev-reproduce-traefik-virtualhost-web:80

    reproduce-traefik-virtualhost-web-8025-http:
      loadbalancer:
        servers:
          - url: http://ddev-reproduce-traefik-virtualhost-web:8025

    reproduce-traefik-virtualhost-web-80-https:

      loadbalancer:
        servers:
          - url: http://ddev-reproduce-traefik-virtualhost-web:80

    reproduce-traefik-virtualhost-web-8025-https:

      loadbalancer:
        servers:
          - url: http://ddev-reproduce-traefik-virtualhost-web:8025



tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/reproduce-traefik-virtualhost.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/reproduce-traefik-virtualhost.key
```
</details>
