### ISSUE TITLE
File nginx_full/nginx-site.conf not copied

### ISSUE THREAD

**Issue by fpoirier1** [drud/ddev#4557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

When `ddev ssh` and running `ls /etc/nginx`, it is expected to find the file `nginx-site.conf`

### Actual Behavior

Instead, Nginx's default config file `nginx-site-default.conf` is found with the default rule `root /var/www/html`.

### Steps To Reproduce

1. `ddev delete -O project`
2. `ddev start`
3. `ddev ssh`
4. `ls /etc/nginx/sites-enabled`

Config file 

```
name: ddev-debug
type: drupal9
docroot: docroot
php_version: "8.0"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.4"
nfs_mount_enabled: false
mutagen_enabled: false
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "16"
```
Versions 
macOS Monterey 12.6
`colima version 0.5.2`
`docker 20.10.11`
`ddev 1.21.4`

### Anything else?

When I run `ls /var/www/html/docroot`, I see all the project files. 

Thank you in advance !
