### ISSUE TITLE
Unable to start DDEV with `nodejs_version: 18` (upstream problem, fix with nodejs 16)

### ISSUE THREAD

**Issue by davereid-pfg** [drud/ddev#4614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

For startup to succeed without fail.

### Actual Behavior

```
Preparing to unpack .../nodejs_18.14.0-deb-1nodesource1_amd64.deb ...
Unpacking nodejs (18.14.0-deb-1nodesource1) ...
Setting up nodejs (18.14.0-deb-1nodesource1) ...
npm ERR! `unsafe-perm` is not a valid npm option
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-06T18_20_13_278Z-debug-0.log
ERROR: executor failed running [/bin/sh -c bash /tmp/setup_node.sh && apt-get install nodejs && npm config set unsafe-perm true && npm install --global gulp-cli yarn]: exit code: 1
------
 > [drud/ddev-webserver:v1.21.4-houston-built  9/12] RUN bash /tmp/setup_node.sh && apt-get install nodejs && npm config set unsafe-perm true && npm install --global gulp-cli yarn:
```

### Steps To Reproduce

* ddev version v1.21.4
* Macbook M1 - OS X Ventura
* Github Actions `ubuntu-latest` - Ubuntu 22.04

In config.yaml:

```yml
type: drupal9
docroot: web
php_version: "8.0"
webserver_type: nginx-fpm
database:
  type: mariadb
  version: "10.3"
php_version: 8.1
nodejs_version: 18
```

### Anything else?

This job used to succeed four days ago and started failing three days ago. I can confirm this in GIthub Actions as well as my local machine.
