### ISSUE TITLE
Output from config.yaml hooks (especially exec) is lost

### ISSUE THREAD

**Issue by rfay** [drud/ddev#606]
## What happened (or feature request):

We support some very nice hooks in config.yaml, that can take action like post-import-db.

However, currently if you add something like 
```
  post-import-db:
    - exec: "drush cc all"
    - exec: "drush vdel site_live_domain"
    - exec: "drush uli"
```
the actions execute, but their output is lost. This isn't as important with the first two lines here (although important) but it's super important with drush uli, as it's only there for output.
