### ISSUE TITLE
Allow Users to Create and Trigger Arbitrary Hooks

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#638]
## What happened (or feature request):

Feature Request

## What you expected to happen:

* End-users have been using our pre/post hook functionality (documented here https://ddev.readthedocs.io/en/latest/users/extending-commands/)
* Additional use cases are popping up where end-users wish to trigger a predetermined series of commands that are not specifically tied to an existing DDEV event like starting the containers OR importing a database.
* It would be ideal to allow for additional entries that could be invoked stand-alone, such as an installation profile (see #5) or for triggering a series of unit or integration tests.
* A sample command might be something like `ddev hook insert-task-key` where "insert-task-key" would be stored in .ddev/config.yml under the "hooks" key.

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)

3

**Comment by tmotyl** [comment]
The other approach would be to allow to extend ddev commands pool, or to create aliases for complex ddev exec.

Our use case is e.g. to be able to easily run  tests (unit/functional...) in the container.
right now I need to call:
```
ddev exec ./bin/phpunit -d memory_limit=1G -c vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml
```
and I would love to be able to shorten that to:

```
ddev exec unitTests
```
or sth similar.

Yet another solution would be to allow creating custom shell aliases from configuration, this way the command would be available in both ssh console (`ddev ssh`) or `ddev exec <alias>`

**Comment by kaystrobach** [comment]
just to provide an idea how we would might use it:

```
commands:
    gerritStart:
      - exec-host: "ddev run gerritConfig"
      - exec-host: "ddev run gerritCommitMesssageHook"
      - exec-host: "ddev run gerritPreCommitHook"
      - exec-host: "ddev run gerritReset"

    gerritConfig:
      - exec-host: "git config user.name \"Your Name\""
      - exec-host: "git config user.email \"your-email@example.com\""

    gerritCommitMesssageHook:
      - exec-host: "mkdir .git/hooks"
      - exec-host: "cp Build/git-hooks/commit-msg .git/hooks/commit-msg"
      - exec-host: "chmod +x .git/hooks/commit-msg"

    gerritPreCommitHook:
      - exec-host: "mkdir .git/hooks"
      - exec-host: "cp Build/git-hooks/unix+mac/pre-commit .git/hooks/"
      - exec-host: "chmod +x .git/hooks/pre-commit"

    gerritReset:
      - exec-host: "git reset --hard origin/master"
      - exec-host: "git pull"

    validateRst:
      - exec: "Build/Scripts/validateRstFiles.php"

    unitTests:
      - exec: "bin/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml"

    functionalTest:
      - exec: "export typo3DatabaseName=\"func\" typo3DatabaseUsername=\"db\" typo3DatabasePassword=\"db\" typo3DatabaseHost=\"localhost\" typo3InstallToolPassword=\"klaus\" && bin/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml"

    # enableXdebug:
    # disabledXdebug:
    # https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/DebuggingTypo3/Index.html

    openGerrit:
      - exec-host: "open https://review.typo3.org"

    openContribGuide:
      - exec-host: "open https://docs.typo3.org/typo3cms/ContributionWorkflowGuide/"
```

This would make it very easy for developers to onboard, as very common tasks are abstracted into a very transparent way
