### ISSUE TITLE
As a developer I want to use blackfire.io to profile my application

### ISSUE THREAD

**Issue by haassie** [drud/ddev#653]
I'm new to ddev and what I have seen so far is really awesome, but I do (think I) miss something and thats one of my favorite tools at the moment: blackfire.io. Is it possible to add this feature?

**Comment by rickmanelius** [comment]
Hi @haassie! I've never personally worked with blackfire.io, but it looks like from the installation instructions (https://blackfire.io/docs/up-and-running/installation) that it's mostly a series of apt-get installs. Now we could add this by default, but we would want to evaluate this solution in terms of its general need/appeal before inclusion. That said, you could adopt this approach as a post-start hook to run those commands and store it in version control so that you always had these available. See https://github.com/drud/ddev/issues/655#issuecomment-366557008 for an example on how you would go about that.

**Comment by rickmanelius** [comment]
It looks like there is some relation to this issue. https://github.com/drud/ddev/issues/691

**Comment by mglaman** [comment]
I realized that's only half of it.

The image would need

```
RUN export VERSION=`php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;"` \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/${VERSION} \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp \
    && mv /tmp/blackfire-*.so `php -r "echo ini_get('extension_dir');"`/blackfire.so \
    && echo "extension=blackfire.so\nblackfire.agent_socket=\${BLACKFIRE_PORT}" > $PHP_INI_DIR/conf.d/blackfire.ini
```

**Comment by mglaman** [comment]
OK, here's my end result.

docker-composer.blackfire.yaml
```
version: '3'
services:
  blackfire:
    container_name: ddev-${DDEV_SITENAME}-blackfire
    image: blackfire/blackfire
    ports: ['8707']
    environment:
      BLACKFIRE_SERVER_ID: d97e69fc-a4bb-4b92-b9f3-70d3bef0c2ef
      BLACKFIRE_SERVER_TOKEN: 8deefb5b9e948c1674b14778c65c5a657b8232fba754d04a3208f18e00fdaea1
  web:
    links:
      - blackfire:$DDEV_HOSTNAME
```

config.yaml change
```
webimage: drud/nginx-php-fpm-local:2018-06-20_exec-sudo
```

install-blackfire.sh
```
#!/usr/bin/env bash
wget -q -O - https://packagecloud.io/gpg.key | sudo apt-key add -
echo "deb http://packages.blackfire.io/debian any main" | sudo tee /etc/apt/sources.list.d/blackfire.list
sudo apt-get update
sudo apt-get install blackfire-php
```

I manually ran install-blackfire.sh, could be a hook command.

**Comment by mglaman** [comment]
Egh, and changing `blackfire.agent_socket = tcp://blackfire:8707`

**Comment by mglaman** [comment]
I'm not sure if its the project or config, but my profiles with this setup is not uploading (weird error I've never seen.)

**Comment by dahaupt** [comment]
@mglaman I've applied your configuration and the upload of the profiles works fine!

**Comment by sven-carstens** [comment]
Or you could add the blackfire integration via post-start hooks:
```yaml
hooks:
  post-start:
    - exec: "sh -c 'curl -A \"Docker\" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/`echo $DDEV_PHP_VERSION|sed \"s/\\.//\"`'"
    - exec: "mkdir -p /tmp/blackfire"
    - exec: "tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp/blackfire"
    - exec: "sh -c 'sudo mv /tmp/blackfire/blackfire-*.so `php -r \"echo ini_get(\\\"extension_dir\\\");\"`/blackfire.so'"
    - exec: "sh -c 'sudo printf \"extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n\" > /etc/php/$DDEV_PHP_VERSION/mods-available/blackfire.ini'"
    - exec: "sh -c 'ln -s /etc/php/7.3/mods-available/blackfire.ini /etc/php/$DDEV_PHP_VERSION/fpm/conf.d/30-blackfire.ini'"
    - exec: "sudo killall -HUP php-fpm"
```
