### ISSUE TITLE
Add bcmath to default PHP container

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev#655]
## What happened (or feature request):

Requested from @alexburrows in the #ddev Drupal Slack channel. This was similar to the #644 request.

**Comment by rfay** [comment]
I mentioned this alternate config.yaml technique to @alexburrows in slack:
```
hooks:
    post-start:
      - exec: "apt-get update && apt-get install php7.2-bcmath"
```

It's actually a nice little way to add on little one-off tidbits, doesn't take too terribly long to run. Probably worth adding to the docs for the many times we'll have one-off needs.

**Comment by rfay** [comment]
Edit: It turns out you can't use things like '&&', '||', or '|' in there. This actually works:

```
hooks:
    post-start:
      - exec: "apt-get update"
      - exec: "apt-get install php7.2-bcmath"
```
