### ISSUE TITLE
`DDEV_PRIMARY_URL` inside container is empty when `ddev-router` is disabled

### ISSUE THREAD

**Issue by stasadev** [drud/ddev#7221]
### Preliminary checklist

- [x] I am using the latest stable version of DDEV (see [upgrade guide](https://ddev.readthedocs.io/en/stable/users/install/ddev-upgrade/))
- [x] I have searched [existing issues](https://github.com/ddev/ddev/issues)
- [x] I have checked the [troubleshooting guide](https://ddev.readthedocs.io/en/stable/users/usage/troubleshooting/)
- [x] I have run `ddev debug test` to include output below

### Output of `ddev debug test`

<details><summary>Expand `ddev debug test` diagnostic information</summary>

```
[COPY-PASTE HERE THE OUTPUT OF `ddev debug test`]
```
</details>

### Expected Behavior

`DDEV_PRIMARY_URL` should have a value.

### Actual Behavior

```
$ ddev config global --omit-containers=ddev-router && ddev restart
...
host DDEV_PRIMARY_URL=http://127.0.0.1:32861
container DDEV_PRIMARY_URL=
...
```

```
$ ddev config global --omit-containers= && ddev restart
...
host DDEV_PRIMARY_URL=https://d11.ddev.site
container DDEV_PRIMARY_URL=https://d11.ddev.site
...
```

### Steps To Reproduce

Using this config:

```yaml
hooks:
    post-start:
        - exec-host: echo "host DDEV_PRIMARY_URL=$DDEV_PRIMARY_URL"
        - exec: echo "container DDEV_PRIMARY_URL=$DDEV_PRIMARY_URL"
```

1. `ddev config global --omit-containers=ddev-router && ddev restart`
2. `ddev config global --omit-containers= && ddev restart`
