### ISSUE TITLE
Hook post-start commands permission denied for apt-*

### ISSUE THREAD

**Issue by scotteuser** [drud/ddev#773]
## What happened:
Was attempting to follow the comment [here](https://github.com/drud/ddev/issues/723#issuecomment-372190453) to try out running tests via ddev. Added this to the config.yaml:
````
hooks:
  post-start:
    - exec: apt-get update
    - exec: apt-get install bzip2 fontconfig
    - exec: wget -qO /tmp/phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - exec: tar -jxf /tmp/phantomjs.tar.bz2 -C /usr/local
    - exec: ln -fs /usr/local/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
````

And received the following permission denied error when running `ddev start`:
````
scott@scott-eurocom-shark-4:/var/www/ddev-drupal8$ ddev start
Starting environment for ddev-drupal8... 
Starting ddev-ddev-drupal8-db ...  
Starting ddev-ddev-drupal8-db ... done
Starting ddev-ddev-drupal8-dba ...  
Starting ddev-ddev-drupal8-web ...  
Starting ddev-ddev-drupal8-web 
Starting ddev-ddev-drupal8-web ... done
 
Network ddev_default is external, skipping 
Creating ddev-router ...  
Creating ddev-router ... done
 
Executing post-start commands... 
--- Running exec command: apt-get update --- 
Failed to start ddev-drupal8: post-start exec failed: Failed to run docker-compose [-f /var/www/ddev-drupal8/.ddev/docker-compose.yaml exec -T web apt-get update], err='exit status 100', stdout='E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
', stderr='', stderr='' 
````

Similarly, if I run `ddev ssh` and then `apt-get update` within the container, I get the same error.

I browsed through + searched your documentation for file system permissions or user groups but did not see anything.

````
docker-compose version 1.17.1, build 6d101fb
Docker version 17.09.0-ce, build afdb6d4
domain	ddev.local                     
cli   	v0.16.0                        
web   	drud/nginx-php-fpm-local:v1.2.1
db    	drud/mariadb-local:v0.9.0      
dba   	drud/phpmyadmin:v0.2.0         
router	drud/ddev-router:v0.5.0        
commit	v0.16.0 
````

## What you expected to happen:
Able to follow the steps in the comment to get phantomjs in place to run browser tests.

## How to reproduce this:
`ddev start` with the specified setup.

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

````
APIVersion: "1"
name: ddev-drupal8
type: drupal8
docroot: web
php_version: "7.1"
webimage: drud/nginx-php-fpm-local:v1.2.1
dbimage: drud/mariadb-local:v0.9.0
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "80"
router_https_port: "443"
provider: default

hooks:
  post-start:
    - exec: apt-get update
    - exec: apt-get install bzip2 fontconfig
    - exec: wget -qO /tmp/phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    - exec: tar -jxf /tmp/phantomjs.tar.bz2 -C /usr/local
    - exec: ln -fs /usr/local/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs
````

## Anything else do we need to know:
I do have phantomjs installed on my local machine. I'm also able to run tests from within containers in wodby's setup (https://github.com/wodby/docker4drupal/issues/61#issuecomment-322682993) so I don't think it's an issue with my machine.

## Related source links or issues:
https://github.com/drud/ddev/issues/723#issuecomment-372190453

## Please use a complexity rating of 1-5 (5 is high) for a feature request. (High complexity implies more PR planning)
1 - Would imagine this is probably something I didn't see in the docs.
