### ISSUE TITLE
Running sudo without password in web

### ISSUE THREAD

**Issue by nadavoid** [drud/ddev#783]
## What happened:
Running sudo in the web service prompts for the password of uid_501.

## What you expected to happen:
Running sudo in the web service executes without prompting for a password.

## How to reproduce this:
```bash
# SSH into web.
ddev ssh
# Use sudo inside the web container.
sudo ls
```

## Version:
ddev version: 0.17.0
docker version: 18.03.0-ce (Recent download for OS X from docker.com)
.ddev/config.yaml:
```yaml
APIVersion: "1"
name: my-site
type: drupal7
docroot: web
php_version: "7.1"
webimage: drud/nginx-php-fpm-local:v1.2.2
dbimage: drud/mariadb-local:v0.9.0
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "8001"
router_https_port: "8444"
additional_hostnames: []
provider: default
```

## Other notes
In version 0.13.0, we were able to run sudo in the web service without having to enter a password.
