### ISSUE TITLE
Running unit tests for TYPO3 inside container throws exception

### ISSUE THREAD

**Issue by sypets** [drud/ddev#797]
## What happened (or feature request):

Running unit tests with phpunit inside the container on TYPO3 testsuite throws an exception. 

`PHP Warning:  include(): file:// wrapper is disabled in the server configuration in /var/www/html/vendor/composer/ClassLoader.php on line 444`

see Stacktrace:

[stacktrace.txt](https://github.com/drud/ddev/files/1924810/stacktrace.txt)

## What you expected to happen:

Unit tests to finish with ok exit code. 

## How to reproduce this:

```
ssh ddev
ddev> bin/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml
```

## Version: Please include the output of `ddev version`, `docker version` and the project's .ddev/config.yaml.

```
ddev version
commit	v0.17.0                        
domain	ddev.local                     
cli   	v0.17.0                        
web   	drud/nginx-php-fpm-local:v1.2.2
db    	drud/mariadb-local:v0.9.0      
dba   	drud/phpmyadmin:v0.2.0         
router	drud/ddev-router:v0.5.0      
```
```
docker version
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:17:53 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:16:25 2018
  OS/Arch:	linux/amd64
  Experimental:	false

```
cat .ddev/config.yaml
```
APIVersion: "1"
name: ddev
type: typo3
docroot: ""
php_version: "7.2"
webimage: drud/nginx-php-fpm-local:v1.2.2
dbimage: drud/mariadb-local:v0.9.0
dbaimage: drud/phpmyadmin:v0.2.0
router_http_port: "80"
router_https_port: "443"
additional_hostnames: []
provider: default

hooks:
  post-start:
    - exec: "composer install -d /var/www/html"
    - exec: enable_xdebug

```

## Anything else do we need to know:

TYPO3 current 9.3.0 development
