### ISSUE TITLE
Add rsync utility to web container

### ISSUE THREAD

**Issue by rfay** [drud/ddev#867]
**Is your feature request related to a problem? Please describe.**

The web container should have rsync in it!

Note that this request is for `drush rsync` to work, which would require more than just adding rsync; It would require:

* ssh auth inside the container as discussed in other issues
* drush aliases somehow mounted or available inside the container.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rfay** [comment]
For drush aliases stored in ~/.drush/aliases on the host, at the discretion of the user, add a .ddev/docker-compose.drush.yaml with these contents:

```
version: '3'
services:
  web:
    volumes:
      - "$HOME/.drush/aliases:/home/.drush/aliases"
```
