### ISSUE TITLE
Support setting environment variables directly from config.yaml

### ISSUE THREAD

**Issue by rfay** [drud/ddev#871]
**Is your feature request related to a problem? Please describe.**

TYPO3 uses environment variables (in php) for various uses that are important to development, especially TYPO3_CONTEXT=Development. 

We have various ways to set these but they're pretty twiddly. See https://stackoverflow.com/questions/50109020/how-can-i-set-environment-variables-inside-ddevs-containers and https://stackoverflow.com/questions/49997842/how-to-set-typo3-context-in-ddev

**Describe the solution you'd like**

Add environment variable spec to config.yaml:
```
environment:
  web:
    - WEBVAR1=value1
    - WEBVAR2=value2:
  db:
    - DBVAR1=value1
```

Related PR that does this in a more complicated way: https://github.com/drud/ddev/pull/870

Note: After this is addressed the related Stack Overflow articles should be addressed.
