### ISSUE TITLE
DB Container - Upgrade MariaDB to 10.2

### ISSUE THREAD

**Issue by mficzel** [drud/ddev#947]
When using DDEV with recent versions of Neos the mariadb version that comes with ddev is not sufficient since Maria 10.2 is requried.

I suggest to raise the version of the alpine-linux the db-container is based on from 3.7 to 3.8. Alpine 3.8 comes with MariaDB 10.2.15.

Alternatively some documentation on how a default mariadb:10.2 container can be used in ddev could solve the problem aswell.

**Comment by mficzel** [comment]
As a sidenote, this docker-compose.db.yaml worked for me to get mariadb 10.2
```
version: '3'

services:
  db:
    image: mariadb:10.2
    healthcheck:
      test: "/usr/bin/mysql --user=db --password=db --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
```
