### ISSUE TITLE
How to give user privileges to create more databases in phpMyAdmin?

### ISSUE THREAD

**Issue by Gonzalo2683** [drud/ddev#996]
Hello, I have accessed phpMyAdmin, but I have not been able to create additional databases in this instance, as I must configure the container or somewhere to have the privileges to create more databases.

regards

**Comment by rfay** [comment]
I don't know how to do it in phpmyadmin, but https://stackoverflow.com/questions/49785023/how-can-i-create-and-load-a-second-database-in-ddev tells how to do it (and links to how to do it automatically)

**Comment by rfay** [comment]
It may be that giving full privs to the 'db' user (using the 'root') user would accomplish that.

**Comment by rfay** [comment]
You can accomplish what you want this way:

```
ddev ssh -s db
mysql 
GRANT ALL to 'db'@'%';
```
Then the "Create" button will appear in phpmyadmin.

**Comment by rfay** [comment]
Marking this resolved, follow up if there's more we can do, thanks!

**Comment by Gonzalo2683** [comment]
Yes, thanks, this solve my problem.

**Comment by ruby232** [comment]
@Gonzalo2683 you can add in config.yaml a hook
```yml
hooks:
  post-start:
    - exec: mysql -uroot -proot -hdb -e "CREATE DATABASE IF NOT EXISTS you_db; GRANT ALL ON you_db.* TO 'db'@'%';"
```
